Gemfile, Gemfile.lock, spec/spec_helper.rb
Fixed https://github.com/GSA/search-gov/issues/37
=> Removed webrat

app/models/searchgov_domain.rb, app/models/sitemap_indexer.rb, spec/models/searchgov_domain_spec.rb, spec/models/sitemap_indexer_spec.rb
- add SearchgovDomain#index_sitemap method
- add SearchgovDomain#scheme method
=> [#157487414] set correct scheme for sitemap urls

app/models/searchgov_crawler.rb, spec/models/searchgov_crawler_spec.rb
@noremmie , I ran this regex against all the existing searchgov URL records, and found zero false positives.
=> [#156343590] improve expanding URL regex

app/jobs/searchgov_domain_indexer_job.rb, app/jobs/sitemap_indexer_job.rb, app/models/searchgov_domain.rb, app/models/searchgov_url.rb, app/models/sitemap_indexer.rb, config/environments/development.rb, config/environments/test.rb, db/migrate/20180608190543_add_lastmod_to_searchgov_url.rb, db/structure.sql, spec/jobs/searchgov_domain_indexer_job_spec.rb, spec/jobs/sitemap_indexer_job_spec.rb, spec/models/searchgov_domain_spec.rb, spec/models/searchgov_url_spec.rb, spec/models/sitemap_indexer_spec.rb
urls
- raise mass assignment error in dev & test environments
=> [#158225026] refactor SitemapIndexer to create & update but not fetch

config/initializers/load_resque.rb
Let's discuss this at our meeting today.
=> [#158531268] raise default Resque timeout

Gemfile.lock
This PR is intended to stop Airbrake from whining about our old version.
=> bump airbrake

db/email_templates/welcome_to_new_user.html.erb, db/email_templates/welcome_to_new_user_added_by_affiliate.html.erb
I updated the getting started video that we include in the Welcome emails, to include both branding updates and a notice that before they launch we want to talk to them about indexing. This PR is just a tiny update to point at the new video instead of the old one.
=> Update video link

app/models/sitemap.rb, spec/models/sitemap_spec.rb
SRCH-48 index sitemaps upon creation
=> Release 1.1.0

features/mobile_searches.feature, features/step_definitions/job_steps.rb, spec/models/api_bing_docs_search_spec.rb, spec/models/api_bing_search_spec.rb
SRCH-135 improve cucumber test for jobs module
SRCH-165 increase re-record interval for Bing specs
=> Release 1.1.1

Gemfile.lock
SRCH-157 - Upgrade loofah to version 2.2.3
=> SRCH-157 - Upgrade loofah to version 2.2.3

app/models/searchgov_crawler.rb, spec/models/searchgov_crawler_spec.rb
- warn if entire site is disallowed
=> SRCH-156 stub www.agency.gov/robots.txt response

app/models/searchgov_crawler.rb, spec/models/api_bing_docs_search_spec.rb, spec/models/api_bing_search_spec.rb, spec/models/searchgov_crawler_spec.rb
SRCH-156 stub www.agency.gov/robots.txt response
SRCH-157 - Upgrade loofah to version 2.2.3
=> Release 1.1.2

app/concerns/fetchable.rb, app/models/searchgov_url.rb, spec/models/searchgov_url_spec.rb, spec/vcr_cassettes/searchgov_url_fetch/when_the_url_points_to_a_txt_doc_/txt_.yml
This PR adds support for indexing TXT files into the `searchgov` index.
=> SRCH-38 index TXT files

Gemfile.lock, app/concerns/fetchable.rb, app/models/searchgov_url.rb, spec/models/searchgov_url_spec.rb, spec/vcr_cassettes/searchgov_url_fetch/when_the_url_points_to_a_txt_doc_/txt_.yml
[SRCH-210] - update rack to address security vulnerability
[SRCH-38] - index TXT files
=> Release 1.4.0

app/controllers/admin/affiliates_controller.rb, app/models/govbox_set.rb, db/migrate/20181025225740_remove_nutshell_columns.rb, db/structure.sql, features/vcr_cassettes/Searches_using_mobile_device/Job_search.yml, lib/jobs.rb, spec/controllers/admin/affiliates_controller_spec.rb, spec/lib/jobs_spec.rb, spec/models/govbox_set_spec.rb, spec/vcr_cassettes/govbox_set/new_query_/affiliate_geoip_info_when_the_affiliate_has_the_jobs_govbox_enabled.yml, spec/vcr_cassettes/jobs/search_options_.yml
[SRCH-202] - scrub job keywords from query
[SRCH-21] - migration to remove nutshell_id columns
=> Release 1.5.0

app/models/searchgov_url.rb, config/secrets.yml.dev, spec/fixtures/searchgov_urls.yml, spec/jobs/searchgov_domain_destroyer_job_spec.rb, spec/lib/tasks/searchgov_spec.rb, spec/models/searchgov_url_spec.rb, spec/models/sitemap_indexer_spec.rb, spec/support/fetchable_behavior.rb, spec/vcr_cassettes/jobs/search_options_.yml, spec/vcr_cassettes/search/gov/tasks_searchgov_bulk_index.yml, spec/vcr_cassettes/search/gov/tasks_searchgov_bulk_index_when_a_url_has_already_been_indexed.yml, spec/vcr_cassettes/search/gov/tasks_searchgov_promote.yml
[SRCH-111] - Update search.gov secrets.yml.dev to reference where to obtain jobs api key
[SRCH-183] - update the SearchgovUrl#fetch method to set that boolean to false
[SRCH-181] - Update the SearchgovURL.fetch_required scope to look for records where that boolean is true
=> Release 1.7.0

features/vcr_cassettes/Searches_using_mobile_device/Job_search.yml, lib/jobs.rb, spec/lib/jobs_spec.rb, spec/models/govbox_set_spec.rb, spec/vcr_cassettes/govbox_set/new_query_/affiliate_geoip_info_when_the_affiliate_has_the_jobs_govbox_enabled.yml, spec/vcr_cassettes/jobs/search_options_.yml, spec/vcr_cassettes/jobs/search_options_/when_the_search_is_within_the_default_radius_but_in_a_different_city.yml
[SRCH-215] - Job results by location
=> Release 1.8.0

app/assets/stylesheets/searches/_results.less, app/models/govbox_set.rb, app/views/searches/_jobs.mobile.haml, app/views/searches/index.mobile.haml, config/locales/en.yml, config/locales/es.yml, config/secrets.yml.dev, features/mobile_searches.feature
[SRCH-234] - More jobs link displayed when job results do not return results.
[SRCH-246] - filter USAJOBS secrets from VCR cassettes
=> Release 1.9.0

app/models/searchgov_url.rb, db/migrate/20181213153332_add_canonical_domain_to_searchgov_domains.rb, db/structure.sql, spec/fixtures/searchgov_urls.yml, spec/models/searchgov_url_spec.rb, spec/support/fetchable_behavior.rb
[SRCH-283] - add canonical_domain to searchgov_urls table
[SRCH-126] - automate reindexing (404 checking)
=> Release 1.10.0

app/controllers/user_sessions_controller.rb, app/models/user.rb, app/models/user_session.rb, features/user_sessions.feature, spec/models/user_spec.rb
- set admin interface to time out after 1 hour of inactivity
- cleanup code
=> SRCH-305 - Set admin session timeout to 1 hour

Gemfile, Gemfile.lock
[SRCH-352] - Upgrade rake gem for search-gov
=> Release 1.12.1

.rubocop.yml, config/initializers/filter_parameter_logging.rb, spec/controllers/user_sessions_controller_spec.rb, spec/controllers/users_controller_spec.rb
=> SRCH-376 - passwords and password confirmations

.rubocop.yml, config/initializers/filter_parameter_logging.rb, spec/controllers/user_sessions_controller_spec.rb, spec/controllers/users_controller_spec.rb
=> Release 1.12.2

app/assets/healthcheck
Add healthchecker to ensure cloudfront can access assets
=> add healthchecker to ensure cloudfront can access assets

app/assets/stylesheets/searches/custom_bootstrap/_sprites.less, deploy/before_symlink.rb
[SRCH-431] - Search Type-Ahead Issue
[SRCH-438] - Search icon missing from search field
=> Release 1.13.1

Gemfile, Gemfile.lock, app/models/searchgov_domain.rb, spec/models/searchgov_domain_spec.rb
[SRCH-104] - Searchgov domain should be validated
=> Release 1.14.1

app/models/elastic_federal_register_document.rb, app/models/elastic_news_item.rb, app/models/elastic_sayt_suggestion.rb, app/models/elastic_tweet.rb, lib/elastic_mappings.rb
SRCH-422 - remove not_analyzed as it does not have any effect
=> SRCH-422 - not_analyzed does not have any effect

app/models/elastic_boosted_content.rb, app/models/elastic_featured_collection.rb, app/models/elastic_federal_register_document.rb, app/models/elastic_indexed_document.rb, app/models/elastic_news_item.rb, app/models/elastic_sayt_suggestion.rb, app/models/elastic_tweet.rb, lib/elastic_mappings.rb, lib/elastic_settings.rb
SRCH-416-update queries to use text/keywords instead of string
=> SRCH-416 - Feature/es string to text keyword

app/models/click_counter.rb, spec/models/click_counter_spec.rb
[SRCH-455] - ClickCounter logs errors for missing I14y documents
=> Release 1.14.2

.circleci/config.yml, .circleci/images/primary/Dockerfile, Gemfile.lock, app/assets/stylesheets/searches/_main_menu.less
[SRCH-560] - fix hover highlight
[SRCH-343] - use shared Docker image for CircleCi
[SRCH-457] - run Elasticsearch 5.6 in CircleCi
=> Release 1.14.3

app/models/i14y_search.rb, app/views/searches/i14y.mobile.haml, features/mobile_searches_bing_v7.feature, features/searchgov_search.feature, features/step_definitions/search_steps.rb, features/support/webmock.rb, features/vcr_cassettes/SearchGov_search/Search_with_site_limits.yml, spec/models/i14y_search_spec.rb
- display matching site limit partial on I14y SERP
- improve cucumber test for searching with sitelimits
=> SRCH-609 display matching site limit partial on I14y SERP

app/controllers/application_controller.rb, config/secrets.yml.dev, features/admin_center_manage_content.feature, features/step_definitions/rss_feed_steps.rb, spec/controllers/help_docs_controller_spec.rb, spec/controllers/human_sessions_controller_spec.rb, spec/controllers/image_searches_controller_spec.rb, spec/controllers/searches_controller_spec.rb
[SRCH-648] - stub responses for RSS feeds in cucumber tests
[SRCH-613] - Search-gov should redirect bad requests to www.usa.gov/search-error
=> Release 1.15.3

Gemfile, Gemfile.lock, app/helpers/admin/associations_helper.rb, app/models/affiliate.rb, app/models/i14y_membership.rb, app/models/med_synonym.rb, app/models/med_topic.rb, app/models/routed_query.rb, app/models/routed_query_keyword.rb, spec/controllers/admin/affiliates_controller_spec.rb, spec/models/affiliate_spec.rb, spec/models/i14y_membership_spec.rb, spec/models/med_synonym.rb, spec/models/med_topic_spec.rb, spec/models/routed_query_keyword_spec.rb, spec/models/routed_query_spec.rb, spec/models/sayt_suggestion_spec.rb, spec/models/site_domain_spec.rb, spec/models/superfresh_url_spec.rb
[SRCH-595] - upgrade active scaffold to 3.5.0
[SRCH-670] - Rails 5 new behavior when uploading files in test
=> Release 1.15.4

app/models/application_document.rb, app/models/html_document.rb, app/models/language.rb, app/models/web_document.rb, spec/models/language_spec.rb
This PR simplifies and refactors the language code handling to ensure consistent parsing of various language code formats. It also cleans up some Rubocop offenses in the `Language` class.
=> SRCH-674 parse alternate language metadata formats

app/models/application_document.rb, app/models/html_document.rb, app/models/language.rb, app/models/web_document.rb, spec/models/language_spec.rb
[SRCH-674] - parse alternate language metadata formats
=> Release 1.15.5

lib/jobs.rb, spec/lib/jobs_spec.rb
SRCH-655 - Remove specific USAJOBS trigger words - "federal" "gobierno"
=> Remove federal and gobierno as trigger words, add rspec test

lib/jobs.rb, spec/lib/jobs_spec.rb
[SRCH-655] - Remove federal and gobierno as trigger words, add rspec test
=> Release 1.15.7

app/views/searches/i14y.mobile.haml, features/searchgov_search.feature, features/vcr_cassettes/SearchGov_search/Video_news_search.yml
This PR ensures that the video module is displayed on the I14y SERP.
=> SRCH-659 display videos on I14y SERP

spec/controllers/searches_controller_spec.rb
- Fix rspec error for searches controller spec
=> SRCH-607 - Rails 5 fix SearchesController rspec errors

Gemfile, Gemfile.lock, app/views/searches/i14y.mobile.haml, features/searchgov_search.feature, features/vcr_cassettes/SearchGov_search/Video_news_search.yml
[SRCH-659] - display videos on I14y SERP
[SRCH-700] - update sitemaps gem to 0.2.3
=> Release 1.15.8

Gemfile, Gemfile.lock
This reverts commit 672024dcfb0d3fefca28a6ea34354d0753aef88d.
=> Revert "SRCH-700 update sitemaps gem to 0.2.3 (#298)"

app/models/user_session.rb, app/views/searches/i14y.mobile.haml, config/locales/authlogic.en.yml, config/locales/dynamic_form.yml, features/searchgov_search.feature, features/user_sessions.feature, features/vcr_cassettes/SearchGov_search/Video_news_search.yml, spec/controllers/password_resets_controller_spec.rb
[SRCH-689] - update generalized unauthorized message
[SRCH-659] - display videos on I14y SERP (removed by a previous rollback)
=> Release 1.15.10

lib/importers/twitter_data.rb, spec/lib/importers/twitter_data_spec.rb
SRCH-722 - Fix rspec errors for the twitter_data_spec
=> SRCH-722-Fix twitter data rspec errors

Gemfile, Gemfile.lock
[SRCH-700] update sitemaps gem to 0.2.3
=> Release 1.15.11

lib/tasks/user.rake, spec/fixtures/users.yml, spec/lib/tasks/user_spec.rb
[SRCH-726] - Bug/account approval
=> Release 1.15.12

spec/support/filterable_search_behavior.rb
Typo in filterable_search_behavior.rb
=> Filterable search behavior

app/helpers/featured_collections_helper.rb, app/helpers/federal_register_documents_helper.rb, spec/helpers/federal_register_documents_helper_spec.rb
Cucumber test fails for sites with federal register docs
=> SRCH-750-cucumber test fails for sites with federal register docs

app/helpers/featured_collections_helper.rb, app/helpers/federal_register_documents_helper.rb, spec/helpers/federal_register_documents_helper_spec.rb
SRCH-750 - Cucumber test fails fixes
One for feature collection helper.
One for federal register docs helper.
=> SRCH-750 - add test for federal register document info

lib/extensions/active_record_extension.rb
SRCH-783 admin_center_manage_content cucumber test
=> cucumber admin center manage content test failing

spec/helpers/federal_register_documents_helper_spec.rb
Add rspec test for link_to_federal_register_advanced_search
=> SRCH-775 - rspec test for link_to_federal_register_advanced_search

app/models/affiliate.rb, spec/models/sitemap_indexer_spec.rb
Just had to tweak where the to_h was. Related to SRCH-797
=> SRCH-797 - add to_h to the saved_template_schema

app/helpers/analytics/home_helper.rb
SRCH-786 - sanitize the referer links
=> SRCH-786 - sanitize referer links

app/models/elastic_sayt_suggestion_query.rb, spec/models/elastic_sayt_suggestion_spec.rb
This PR fixes phrase filtering for SAYT searches, and re-enables the relevant spec.
=> SRCH-838 fix SAYT phrase filtering

spec/helpers/federal_register_documents_helper_spec.rb
This is to cleanup the spec. Rspec test was in there twice.
=> SRCH-830 - Rails 5 - spec cleanup

features/vcr_cassettes/Dashboard/Performing_site_autodiscovery.yml, spec/vcr_cassettes/searchgov_domain_check_status/when_the_domain_is_available.yml, spec/vcr_cassettes/searchgov_domain_check_status/when_the_domain_is_redirected_when_the_redirect_is_to_another_domain.yml, spec/vcr_cassettes/searchgov_domain_check_status/when_the_domain_is_redirected_when_the_redirect_is_to_https.yml, spec/vcr_cassettes/searchgov_domain_check_status/when_the_domain_returns_an_error_code.yml, spec/vcr_cassettes/searchgov_domain_indexer_job/when_a_domain_has_outdated_urls.yml, spec/vcr_cassettes/searchgov_domain_indexer_job/when_a_domain_has_unfetched_urls.yml, spec/vcr_cassettes/searchgov_domain_indexer_job/when_a_domain_has_unfetched_urls_when_the_domain_has_multiple_unfetched_urls.yml, spec/vcr_cassettes/searchgov_domain_preparer_job.yml, spec/vcr_cassettes/searchgov_domain_sitemap_urls/when_the_domain_has_sitemap_records.yml, spec/vcr_cassettes/sitemap_indexer_index.yml, spec/vcr_cassettes/sitemap_indexer_index/when_a_searchgov_url_already_exists_when_lastmod_is_not_specified_in_the_sitemap.yml, spec/vcr_cassettes/sitemap_indexer_index/when_a_searchgov_url_already_exists_when_when_lastmod_is_specified_in_the_sitemap.yml, spec/vcr_cassettes/sitemap_indexer_index/when_a_searchgov_url_record_raises_an_error.yml, spec/vcr_cassettes/sitemap_indexer_index/when_fetching_the_sitemap_raises_an_error.yml, spec/vcr_cassettes/sitemap_indexer_index/when_the_sitemap_contains_whitespace_around_the_elements.yml, spec/vcr_cassettes/sitemap_indexer_index/when_the_sitemap_specifies_a_lastmod_value.yml, spec/vcr_cassettes/sitemap_indexer_index/when_the_sitemap_urls_do_not_have_the_same_scheme_as_the_domain.yml, spec/vcr_cassettes/sitemap_indexer_index/when_urls_are_from_a_different_domain.yml
This PR updates the VCR cassettes used in our automated tests.
=> SRCH-874 re-record VCR cassettes

.rubocop.yml, config/secrets.yml.dev, features/vcr_cassettes/Dashboard/Performing_site_autodiscovery.yml, lib/es.rb, spec/lib/es_spec.rb, spec/support/shared_vcr_setup.rb, spec/vcr_cassettes/searchgov_domain_check_status/when_the_domain_is_available.yml, spec/vcr_cassettes/searchgov_domain_check_status/when_the_domain_is_redirected_when_the_redirect_is_to_another_domain.yml, spec/vcr_cassettes/searchgov_domain_check_status/when_the_domain_is_redirected_when_the_redirect_is_to_https.yml, spec/vcr_cassettes/searchgov_domain_check_status/when_the_domain_returns_an_error_code.yml, spec/vcr_cassettes/searchgov_domain_indexer_job/when_a_domain_has_outdated_urls.yml, spec/vcr_cassettes/searchgov_domain_indexer_job/when_a_domain_has_unfetched_urls.yml, spec/vcr_cassettes/searchgov_domain_indexer_job/when_a_domain_has_unfetched_urls_when_the_domain_has_multiple_unfetched_urls.yml, spec/vcr_cassettes/searchgov_domain_preparer_job.yml, spec/vcr_cassettes/searchgov_domain_sitemap_urls/when_the_domain_has_sitemap_records.yml, spec/vcr_cassettes/sitemap_indexer_index.yml, spec/vcr_cassettes/sitemap_indexer_index/when_a_searchgov_url_already_exists_when_lastmod_is_not_specified_in_the_sitemap.yml, spec/vcr_cassettes/sitemap_indexer_index/when_a_searchgov_url_already_exists_when_when_lastmod_is_specified_in_the_sitemap.yml, spec/vcr_cassettes/sitemap_indexer_index/when_a_searchgov_url_record_raises_an_error.yml, spec/vcr_cassettes/sitemap_indexer_index/when_fetching_the_sitemap_raises_an_error.yml, spec/vcr_cassettes/sitemap_indexer_index/when_the_sitemap_contains_whitespace_around_the_elements.yml, spec/vcr_cassettes/sitemap_indexer_index/when_the_sitemap_specifies_a_lastmod_value.yml, spec/vcr_cassettes/sitemap_indexer_index/when_the_sitemap_urls_do_not_have_the_same_scheme_as_the_domain.yml, spec/vcr_cassettes/sitemap_indexer_index/when_urls_are_from_a_different_domain.yml
[SRCH-874] - re-record VCR cassettes
[SRCH-859] - use basic auth for elasticsearch client
=> Release 1.15.18

lib/elastic_indexer.rb, spec/lib/elastic_indexer_spec.rb
The purpose of this PR is to rescue errors that may occur while indexing custom index data into Elasticsearch. Currently, a rake task such as `rake usasearch:elasticsearch:index_all[FeaturedCollection]` will blow up completely if it encounters a single error. This PR will allow the process to proceed after an error occurs, while logging the information for a developer to resolve. (Note: I've only run into indexing errors in demo, due to some corrupted data. I deliberately put the `rescue` high up in the flow, so that it will catch any weirdness in lower levels of the indexing process.)
=> SRCH-887 rescue Elasticsearch indexing errors

lib/elastic_indexer.rb, spec/lib/elastic_indexer_spec.rb
[SRCH-887] - rescue Elasticsearch indexing errors
=> Release 1.15.19

db/migrate/20190920181828_add_omniauth_to_users.rb, db/structure.sql, spec/models/user_spec.rb
[SRCH-857] - add uid to users table
=> Release 1.15.20

config/elasticsearch_client.yml, config/secrets.yml.dev, lib/es.rb, spec/lib/es_spec.rb, spec/support/elasticsearch_client_behavior.rb
[SRCH-955] - pass an array of hosts to Elasticsearch client
=> Release 1.15.21

app/controllers/clicked_controller.rb
SRCH-978 fixed `DEPRECATION WARNING: env is deprecated and will be removed from Rails 5.1` warning
=> SRCH 978 env deprecation

Makefile, README.markdown
I think long (and even short) term this will be easier to use and maintain.  People are under no obligation to use this.  They can keep doing things exactly the way they currently are.
=> added make file to facilitate some complex docker commands.

app/models/logstash_queries/module_sparkline_query.rb, app/models/logstash_queries/overall_sparkline_query.rb, lib/analytics_dsl.rb, spec/models/logstash_queries/module_sparkline_query_spec.rb, spec/models/logstash_queries/overall_sparkline_query_spec.rb
SRCH-1023 update OverallSparklineQuery for Elasticsearch 5.6
SRCH-1042 update ModuleSparkline Query
=> SRCH-1023 SRCH-1042 update Sparkline queries for Elasticsearch 5.6

app/models/logstash_queries/monthly_histogram_query.rb, spec/models/logstash_queries/monthly_histogram_query_spec.rb
Updates the  MonthlyHistogramQuery to run on Elasticsearch 5.6.
=> SRCH-1043 update MonthlyHistogramQuery

app/models/logstash_queries/top_query_match_query.rb, app/models/rtu_queries_request.rb, spec/fixtures/json/rtu_dashboard/top_query_match_query.json, spec/models/logstash_queries/top_query_match_query_spec.rb, spec/models/rtu_queries_request_spec.rb
- SRCH-1046 update TopQueryMatchQuery
- SRCH-1049 update RtuQueriesRequest
=> Update TopQueryMatchQuery to run on ES 5.6

config/routes.rb, features/users.feature
SRCH-update register link to redirect the user to security notification.
=> SRCH-861 - update signup to redirect to security notification

app/controllers/api_controller.rb
SRCH-977 resolve deprecation re. `render :text`
=> SRCH-977 resolve deprecation re. `render :text`

app/models/logstash_queries/trending_terms_query.rb, spec/models/logstash_queries/trending_terms_query_spec.rb
SRCH-1047 update TrendingTermsQuery to run on Elasticsearch 5.6
=> SRCH-1047 update TrendingTermsQuery to run on Elasticsearch 5.6

db/migrate/20191113214448_change_uid_index.rb, db/structure.sql, spec/models/user_spec.rb
[SRCH-1059] - remove uniq index from UID
=> Release 1.15.26

config/initializers/omniauth.rb
SRCH-1062 - update all non dev servers to use https: the rest http.
=> SRCH-1062 - add omniauth protocol

app/models/logstash_queries/site_breakdown_for_module_query.rb, spec/models/logstash_queries/site_breakdown_for_module_query_spec.rb
SRCH-1074 update SiteBreakdownForModuleQuery for Elasticsearch 5.6
=> SRCH-1074 update SiteBreakdownForModuleQuery for Elasticsearch 5.6

app/models/logstash_queries/low_ctr_query.rb, spec/models/logstash_queries/low_ctr_query_spec.rb
This PR updates the LowCTRQuery for Elasticsearch 5.6.
=> SRCH-1072 update LowCTRQuery for Elasticsearch 5.6

app/controllers/sites/click_drilldowns_controller.rb, app/controllers/sites/query_drilldowns_controller.rb, app/models/logstash_queries/drilldown_query.rb, spec/controllers/sites/click_drilldowns_controller_spec.rb, spec/controllers/sites/query_drilldowns_controller_spec.rb, spec/models/logstash_queries/drilldown_query_spec.rb
- update DrilldownQuery for Elasticsearch 5.6
- update controllers using the DrilldownQuery
=> SRCH-1070 update DrilldownQuery for Elasticsearch 5.6

app/mailers/emailer.rb, db/email_templates/new_affiliate_site.html.erb, db/email_templates/new_user_to_admin.html.erb, db/email_templates/user_approval_removed.erb, spec/mailers/emailer_spec.rb
[SRCH-1081] - Feature/update blanks in email
=> Release 1.16.2

.rubocop.yml, app/controllers/sites/analytics_controller.rb, app/controllers/sites/click_queries_controller.rb, app/controllers/sites/query_clicks_controller.rb, app/controllers/sites/query_downloads_controller.rb, app/controllers/sites/query_referrers_controller.rb, app/controllers/sites/referrer_queries_controller.rb, app/models/click_counter.rb, app/models/logstash_queries/rtu_date_range_query.rb, app/models/rtu_dashboard.rb, app/models/rtu_monthly_report.rb, app/models/rtu_queries_request.rb, app/models/rtu_query_stat.rb, app/models/sayt_suggestion_discovery.rb, spec/controllers/sites/query_downloads_controller_spec.rb, spec/models/rtu_dashboard_spec.rb, spec/models/rtu_query_stat_spec.rb, spec/models/sayt_suggestion_discovery_spec.rb
This PR:
- cleans up some Rubocop issues
- updates the field names in arguments passed to analytics queries
=> SRCH-464 update field names in method args, clean up rubocop issues

config/application.rb
Issue in Rails 5 autoloading.  Went with the option of setting it back to the way it was done in rails 4 for now. But will revisit better solution.
=> autoload issue in rails 5

config/initializers/email.rb, config/newrelic.yml
Secrets in rails 5.1 are symbols not string.
=> secrets must be symble not string

config/initializers/airbrake.rb, config/initializers/load_resque.rb
=> updated 2 more secrets files that need to be symbols

.rubocop.yml, lib/analytics_dsl.rb, lib/watcher_dsl.rb
This PR resolves the remaining Rubocop failures for the analytics upgrade:
https://github.com/GSA/search-gov/pull/448
=> SRCH-1125 resolve rubocop failures

app/models/youtube_profile.rb, spec/fixtures/affiliates.yml, spec/fixtures/youtube_profiles.yml, spec/models/youtube_profile_spec.rb
[SRCH-1165] - Youtube rake tasks should run successfully
=> Release 1.16.6

app/mailers/emailer.rb, app/models/email_template.rb, db/email_templates/account_deactivated.html.erb, db/email_templates/account_deactivation_warning.html.erb, spec/mailers/emailer_spec.rb
[SRCH-1192] - add emailer templates that notifies the user that their account is going to get deactivated
[SRCH-1193] - add emailer template that notifies user their account is de-activated
=> Release 1.16.12

db/migrate/20200121220041_remove_user_unused_columns.rb, db/structure.sql, lib/user_approval.rb, spec/lib/user_approval_spec.rb
[SRCH-855] - remove unused columns from user table
[SRCH-1194] - Add notify_user_inactivity method
=> Release 1.16.13

app/controllers/admin/admin_controller.rb, app/controllers/admin/home_controller.rb, app/controllers/concerns/accountable.rb, app/controllers/sites/base_controller.rb, app/controllers/user_sessions_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, db/migrate/20200212183209_add_firstname_lastname_to_users.rb, db/structure.sql, spec/controllers/admin/home_controller_spec.rb, spec/controllers/omniauth_callbacks_controller_spec.rb, spec/controllers/sites/sites_controller_spec.rb, spec/controllers/sites/users_controller_spec.rb, spec/fixtures/users.yml, spec/models/user_spec.rb, spec/support/shared_concern_accountable.rb
[SRCH-1258] - Create Method to check if user's account info is complete
[SRCH-1266] - Create first_name last_name column in users table
=> Release 1.16.16

lib/tasks/user.rake, spec/lib/tasks/user_spec.rb
[SRCH-1281] - update rake task to take a number for how many days ago to warn user
=> Release 1.16.17

lib/tasks/user.rake, spec/fixtures/users.yml, spec/lib/tasks/user_spec.rb
[SRCH-1304] - warn only approved users
=> Release 1.16.18

Gemfile.lock
[SRCH-1313] - Bump puma from 3.12.2 to 3.12.3
=> Release 1.16.19

lib/tasks/populate_user.rake, spec/fixtures/csv/users.csv, spec/fixtures/users.yml, spec/lib/tasks/poplate_user_spec.rb, spec/lib/tasks/user_spec.rb
This pull request is a rake task that when passed the path of a csv file it will parse it and populate first name and last name for the given email addresses.
=> SRCH-1282 - raketask populate first last name

lib/tasks/populate_user.rake, spec/fixtures/csv/users.csv, spec/fixtures/users.yml, spec/lib/tasks/poplate_user_spec.rb, spec/lib/tasks/user_spec.rb
[SRCH-1282] - Write script to populate first name last name from given spreadsheet
=> Release 1.16.21

app/mailers/emailer.rb, db/email_templates/account_deactivation_warning.html.erb, spec/mailers/emailer_spec.rb
[SRCH-1300] - Update 90-day deactivation email copy
=> Release 1.16.23

app/controllers/sites/click_drilldowns_controller.rb, app/controllers/sites/query_drilldowns_controller.rb, app/models/logstash_queries/drilldown_query.rb, app/models/request_drilldown.rb, lib/analytics_dsl.rb, spec/controllers/sites/click_drilldowns_controller_spec.rb, spec/controllers/sites/query_drilldowns_controller_spec.rb, spec/models/logstash_queries/drilldown_query_spec.rb, spec/models/request_drilldown_spec.rb
This PR updates the `DrilldownQuery` to filter by the `type` field.
=> SRCH-1305 fix drilldown query

app/controllers/sites/click_drilldowns_controller.rb, app/controllers/sites/query_drilldowns_controller.rb, app/models/logstash_queries/drilldown_query.rb, app/models/request_drilldown.rb, lib/analytics_dsl.rb, spec/controllers/sites/click_drilldowns_controller_spec.rb, spec/controllers/sites/query_drilldowns_controller_spec.rb, spec/models/logstash_queries/drilldown_query_spec.rb, spec/models/request_drilldown_spec.rb
[SRCH-1305] -  update drilldowns to query by `type` field
=> Release 1.16.25

.rubocop.yml, app/models/rtu_date_range.rb, app/models/rtu_queries_request.rb, app/models/rtu_referrers_request.rb
This PR resolves several Rubocop style offenses in the `release/analytics_es6` branch.
=> SRCH-1391 resolve Rubocop offenses

app/models/link_popularity.rb, app/models/logstash_queries/elastic_link_popularity_query.rb, spec/models/link_popularity_spec.rb, spec/models/logstash_queries/elastic_link_popularity_query_spec.rb
[SRCH-1384] - update LinkPopularity query to search by `type` field
=> Release 1.16.27

app/controllers/omniauth_callbacks_controller.rb, app/controllers/user_sessions_controller.rb, app/models/user.rb, features/admin.feature, features/step_definitions/user_steps.rb, features/user_sessions.feature, spec/controllers/omniauth_callbacks_controller_spec.rb, spec/controllers/user_sessions_controller_spec.rb, spec/support/omniauth_helpers.rb
=> SRCH-1515 logout

spec/lib/document_fetcher_spec.rb
This PR fixes a spec that has been failing intermittently.
=> fix DocumentFetcher redirection spec

app/jobs/sitemap_indexer_job.rb, app/jobs/sitemap_monitor_job.rb, spec/jobs/sitemap_indexer_job_spec.rb, spec/jobs/sitemap_monitor_job_spec.rb, spec/support/sitemap_job_behavior.rb
[SRCH-1356] - Separate sitemap and searchgov queues
=> Release 1.16.36

app/controllers/clicked_controller.rb, app/models/api_click.rb, app/models/click.rb, spec/models/api_click_spec.rb, spec/models/click_spec.rb, spec/requests/clicked_spec.rb, spec/support/shared_vcr_setup.rb, spec/system/click_tracking_spec.rb
SRCH-1635 add referrer to click log line
- update click log for consumption by Logstash
- add 'api' tag to click JSON
- configure VCR to ignore webdriver hosts
=> SRCH-1635 add referrer to click log line

app/models/click.rb, spec/models/click_spec.rb
[SRCH-1687] - log clicks on encoded URLs
=> Release 1.17.1

lib/middlewares/filtered_cors.rb, spec/controllers/human_sessions_controller_spec.rb, spec/lib/middlewares/filtered_cors_spec.rb
- fix flakey human sessions controller spec (for real this time)
- robocop-based spec refactoring
=> SRCH-1695 add CORS support to click API

app/controllers/api/v2/click_controller.rb, app/controllers/clicked_controller.rb, config/routes.rb, lib/middlewares/filtered_cors.rb, spec/controllers/human_sessions_controller_spec.rb, spec/lib/middlewares/filtered_cors_spec.rb, spec/requests/api/v2/click_spec.rb, spec/requests/clicked_spec.rb, spec/support/click_tracking_behavior.rb, spec/system/click_tracking_spec.rb
This is the release branch for two click tracking changes:
- SRCH-1697 extract browser info from client-side click api requests 
- SRCH-1695 add CORS support to click API
=>  SRCH-1693 Click tracking updates

config/initializers/cors.rb
SRCH-1795 fix CORS for api/v2/search/i14y endpoint (#643)
=> Release 1.19.0

config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, lib/tasks/searchgov.rake, spec/lib/tasks/searchgov_spec.rb, spec/requests/api/v2/search_spec.rb, spec/vcr_cassettes/api/v2/search/_i14y_behaves_like_a_request_with_cors_support_when_the_request_originates_from_an_external_domain.yml
SRCH-1796 add CORS specs for additional search API endpoints https://github.com/GSA/search-gov/pull/645
SRCH-1760 remove searchgov:bulk_index rake task https://github.com/GSA/search-gov/pull/642
SRCH-1768 secure session cookies https://github.com/GSA/search-gov/pull/648
=> Release 1.19.1

app/models/sayt_suggestion_discovery.rb, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, lib/tasks/searchgov.rake, spec/lib/tasks/searchgov_spec.rb, spec/models/sayt_suggestion_discovery_spec.rb, spec/requests/api/v2/search_spec.rb, spec/vcr_cassettes/api/v2/search/_i14y_behaves_like_a_request_with_cors_support_when_the_request_originates_from_an_external_domain.yml
SRCH-1866 increase suggestion threshold to 100 (#651)
The other three were already committed in https://github.com/GSA/search-gov/commit/3c31360c3c9cc3ef4e95c77d9bc94d7f85cdeb06 but github doesn't know that because I did a merge and squash for that PR.  Won't do that any more on Release PRs since it makes it difficult to trace actual deltas.
=> Release 1.19.2

app/controllers/sites/click_tracking_api_instructions_controller.rb, app/views/sites/api_instructions/_show_tos_md.html.haml, app/views/sites/click_tracking_api_instructions/_show_md.html.haml, app/views/sites/shared/_activate_search_sub_nav.html.haml, features/admin_center_activate_search.feature
=> SRCH-1680 add instructions for click tracking API (#650)

app/models/routed_query_keyword.rb, spec/models/routed_query_keyword_spec.rb, spec/models/routed_query_spec.rb
SRCH-1771 - block html injection https://github.com/GSA/search-gov/pull/656
=> Release 1.20.4

app/models/sayt_suggestion.rb, db/migrate/20210323175952_add_index_on_sayt_suggestions_updated_at_is_protected.rb, db/structure.sql, spec/models/sayt_suggestion_spec.rb
SRCH-1951 fix SaytSuggestion.expire (#675)
=> Release 1.20.7

features/legacy_search.feature, features/searches.feature, features/vcr_cassettes/Legacy_Search/Searching_a_domain_with_Bing_results_that_match_a_specific_news_item.yml, features/vcr_cassettes/Search/Searching_a_domain_with_Bing_results_that_match_a_specific_news_item.yml
- update legacy feature & cassette
=> SRCH-2018 update and enable features re. searching for news items matching web results

Gemfile, Gemfile.lock, app/models/html_document.rb, app/models/searchgov_crawler.rb, spec/models/html_document_spec.rb, spec/models/searchgov_crawler_spec.rb, spec/support/web_document_behavior.rb
- upgrade Medusa
- upgrade Loofah
- resolve several 2.7 deprecation warnings
=> SRCH-2034 make the SearchgovCrawler compatible with Ruby 2.7

.rubocop.yml, app/controllers/admin/affiliates_controller.rb, app/models/affiliate.rb, features/admin.feature, features/mobile_searches.feature, features/mobile_searches_bing_v7.feature, features/step_definitions/agency_steps.rb, features/step_definitions/job_steps.rb, features/vcr_cassettes/Searches_using_mobile_device/Agency_job_search.yml, spec/controllers/admin/affiliates_controller_spec.rb, spec/helpers/news_search_helper_spec.rb, spec/models/affiliate_spec.rb
Functional
SRCH-2057 remove Super Admin controls for legacy SERP features (#731)
Testing only
SRCH-2308 add specs for NewsSearchHelper#current_time_filter_descript…
SRCH-2299 add integration test for agency job search (#734)
=> Release 5.0.0

.circleci/config.yml, .rubocop.yml, app/controllers/sites/rss_feeds_controller.rb, app/models/affiliate.rb, app/models/rss_feed.rb, app/views/sites/rss_feeds/_form.html.haml, docker-compose.yml, spec/controllers/sites/rss_feeds_controller_spec.rb
* SRCH-2260 Update affiliate.rss_feed_urls for MySQL 5.7
=> Release 6.1.0

config/i18n-tasks.yml, spec/i18n_spec.rb
This PR updates the `i18n-tasks` config and adds the default specs provided by the gem: https://github.com/glebm/i18n-tasks#installation. I've set a couple of the specs to be skipped temporarily, as I'll be making translation-related changes in `SRCH-649`. I may make additional config changes as part of that story, but for this ticket, I'm implementing/updating the vanilla defaults from the current version of the gem.
=> SRCH-2548 update i18n-tasks config

app/views/sites/no_results_pages/edit.html.haml, config/locales/en.yml, features/mobile_searches.feature, features/searches.feature
- Updated no results text to refer to "search term" rather than "query" in the en localization file
- Updated hardcoded text to reflect this language change
- Updated cucumber specs to reflect the new language
- [N/A] Code is functional. - Can't confirm and run locally, but it is only content changes.
- [N/A] If your changes will be tested manually, you have run `bundle update` and committed your changes to Gemfile.lock.
- [N/A] If your target branch is NOT `master` or `main`, specify the reason:
=> SRCH-2537 Update "Query" to "Search Term" for Clarity

.circleci/images/primary/Dockerfile.ruby274
This PR:
- removes the Dockerfile for Ruby 2.5.5
- adds a Dockerfile for 2.7.4
=> SRCH-2646 add Dockerfile for Ruby 2.7.4

app/controllers/sayt_controller.rb
- Removes the override for Rails logging in `app/controllers/sayt_controller.rb` for logging consistency/ease of debugging.
N/A
N/A
=> SRCH-2678_sayt_controller_logging

features/searches.feature
This PR resolves a cucumber failure that was caused by a BBT with a `publish_end_on` date that is now in the past: `2022-01-01`
=> SRCH-2711 fix time-based cucumber failure

config/logindotgov.pem, config/secrets.yml.dev
This PR updates the Login.gov configuration for local development:
- use the new `search_dev` application, which will replace the old and confusing `search_local`/`local_search` app
- add a note to the `config/logindotgov.pem` file
=> SRCH-2732 update login.gov configuration

features/admin_center_dashboard.feature, features/vcr_cassettes/Dashboard/Adding_a_new_site.yml
This PR resolves the following cucumber failure that started occurring after the search.gov website relaunch:
```
expected: /https:\/\/d3qcdigd1fhos0.cloudfront.net\/blog\/img\/favicon.ico/
got: "" (using =~)
Diff:
@@ -1 +1 @@
-/https:\/\/d3qcdigd1fhos0.cloudfront.net\/blog\/img\/favicon.ico/
+""
(RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/web_steps.rb:160:in `block (2 levels) in <top (required)>'
./features/step_definitions/web_steps.rb:29:in `with_scope'
./features/step_definitions/web_steps.rb:156:in `/^the "([^"]*)" field(?: within (.*))? should contain "(.*)"$/'
./features/support/hooks.rb:22:in `block (2 levels) in <top (required)>'
./features/support/hooks.rb:21:in `block in <top (required)>'
./features/support/env.rb:66:in `block in <top (required)>' …
```
=> SRCH-2750 fix "Adding a new site" feature

app/models/custom_index_queries/elastic_boosted_content_query.rb
- SRCH-2828 Minimum should match in boosted contents
Was determined that manual testing was not needed.
=> Release - SRCH-2828

README.md
This PR updates the README to use a cleaner, more concise series of steps to set up a development machine.
=> SRCH-2945 update README

Gemfile
This PR notes that twitter/tweetstream are blockers to upgrading the `elasticsearch` gem any further.
=> SRCH-2771 add comment re. elasticsearch gem version

.circleci/config.yml, .codeclimate.yml, Gemfile, Gemfile.lock, README.md, app/models/logstash_queries/module_sparkline_query.rb, app/models/logstash_queries/monthly_histogram_query.rb, config/secrets.yml.dev, docker-compose.yml, spec/models/logstash_queries/module_sparkline_query_spec.rb, spec/models/logstash_queries/monthly_histogram_query_spec.rb, spec/models/logstash_queries/overall_sparkline_query_spec.rb, spec/support/indexable_behavior.rb
Functional
- SRCH-2862 resolve deprecation warnings re. year format
Testing/Documentation
- SRCH-2771 add comment re. elasticsearch gem version
- SRCH-2772 run CircleCi against multiple Elasticsearch versions
- SRCH-2920 specify rubocop version & channel
- SRCH-2945 update README
=> Release - SRCH-2862

Gemfile.lock, app/models/html_document.rb, spec/models/html_document_spec.rb
- SRCH-3161 Parse and extract og:image
=> Release - SRCH-3161

.github/pull_request_template.md
- Updating PR Checklist based off team conversation
- Modeling after changes in https://github.com/GSA/i14y/pull/195
- Not running bundle update as part of this push; this is just a markdown file change, not a functional change.
:warning: You have run `bundle update` and committed your changes to Gemfile.lock.  - Not doing this, reasons above.
=> SRCH-3170 update PR template

.github/pull_request_template.md, app/models/html_document.rb, spec/fixtures/html/page_with_dc_metadata.html, spec/fixtures/html/page_with_og_metadata.html, spec/models/application_document_spec.rb, spec/models/html_document_spec.rb, spec/models/searchgov_url_spec.rb
- [SRCH-3158 update parsing logic for tags field](https://github.com/GSA/search-gov/commit/3acf65ebb06ef18521b863cc9a48b0a880515ff4)
- [SRCH-3297 remove squash requirement](https://github.com/GSA/search-gov/commit/0d9c0b479da5bf3595f3fc96225aef7e1b02f08c)
=> Release - SRCH-3158, SRCH-3297

db/migrate/20220715232211_drop_affiliates_instagram_profiles.rb, db/migrate/20220715232531_drop_instagram_profiles.rb, db/schema.rb
- SRCH-505 remove any database tables or columns related to Instagram…
=> Release - SRCH-505

app/models/application_document.rb, app/models/i14y_document.rb, app/models/searchgov_url.rb, spec/models/i14y_document_spec.rb, spec/models/searchgov_url_spec.rb
- SRCH-3374 Update searchgov for new i14y fields (#1018)
=> Release - SRCH-3374

Gemfile, Gemfile.lock
- SRCH-2554 Add bootsnap to dev and test environments (#1041)
=> Release - SRCH-2554

app/models/i14y_search.rb, spec/fixtures/json/i14y/web_search/marketplace.json, spec/models/i14y_search_spec.rb
- SRCH-3469 Add aggregations to i14y_search response (#1047)
=> Release - SRCH-3469

.circleci/config.yml
- Update Redis version to 6.2 which is a latest supported version in CircleCI config
=> SRCH-3265 update CircleCI config to Redis 6.2

.circleci/config.yml, app/controllers/admin/searchgov_domains_controller.rb, app/models/searchgov_domain.rb, db/migrate/20221111205138_change_default_is_bing_image_search_enabled_on_affiliates_to_false.rb, db/schema.rb, features/admin.feature, features/admin_center_manage_display.feature, features/searches.feature, features/step_definitions/web_steps.rb, spec/controllers/admin/searchgov_domains_controller_spec.rb, spec/models/image_search_spec.rb
- [SRCH-2606 Disable Bing image search by default](https://github.com/GSA/search-gov/commit/769a2f0563fba20733a5c4bc9f3aac19af56aae9)
- [SRCH-3265 update CircleCI config to Redis 6.2](https://github.com/GSA/search-gov/commit/02e66a627dd4dc840f6db246b259b27efba04fc9)
- [SRCH-3434 expose JS indexing option to domains table for super admins](https://github.com/GSA/search-gov/commit/dea155fc1b7221471fcfb6572dcc88f68c844c0e)
=> Release - SRCH-2606, SRCH-3265, SRCH-3434

app/views/sites/shared/_footer.html.haml, db/schema.rb
- Updated a footer link from "Federalist" to "Cloud.gov Pages" on the system login page footer
=> SRCH-3543 Updated footer link

app/views/sites/shared/_footer.html.haml
- [SRCH-3543 Updated footer link](https://github.com/GSA/search-gov/commit/1026a34943e9e88a7dafc588bc5e82714ce1241a)
=> Release - SRCH-3543

config/initializers/email.rb
- This PR prevents the email initializer from failing on environments that have specified a `force_to` email address (such as staging).
=> SRCH-3604 fix email initializer

config/initializers/email.rb, lib/search_gov_interceptor.rb, spec/lib/search_gov_interceptor_spec.rb
- SRCH-3606 refactor and add specs for SearchGovInterceptor (#1062)
=> Release - SRCH-3606

app/controllers/api/v2/searches_controller.rb, app/models/filterable_search.rb, app/models/i14y_search.rb, lib/api/non_commercial_search_options.rb, spec/controllers/api/v2/searches_controller_spec.rb, spec/lib/api/non_commercial_search_options_spec.rb, spec/models/blended_search_spec.rb, spec/models/i14y_search_spec.rb, spec/models/news_search_spec.rb, spec/support/filterable_search_behavior.rb
- SRCH-3614 Add tags filtering to Results API (#1065)
=> Release - SRCH-3614

.circleci/config.yml, README.md, app/controllers/api/v2/searches_controller.rb, app/javascript/components/ResultsPage.tsx, app/models/filterable_search.rb, app/models/low_query_ctr_watcher.rb, app/models/no_results_watcher.rb, app/models/watcher.rb, db/migrate/20230106201846_rename_watcher_conditions_columns.rb, db/schema.rb, features/redesigned_searches.feature, features/vcr_cassettes/Search_-_redesign/Searching_a_domain_with_Bing_results.yml, lib/api/non_commercial_search_options.rb, lib/api/search_options.rb, spec/controllers/api/v2/searches_controller_spec.rb, spec/fixtures/users.yml, spec/lib/api/search_options_spec.rb, spec/models/low_query_ctr_watcher_spec.rb, spec/models/no_results_watcher_spec.rb, spec/models/watcher_spec.rb, spec/support/shared_sites_controller_shared_behavior.rb, spec/support/watcher_behavior.rb
- [SRCH-3293 Make ElasticSearch 7 the default for development and testing](https://github.com/GSA/search-gov/commit/87b96690dc1b56f2fe87b7018088c1a7496472a8)
- [SRCH-3617 Site_limits filtering in Results API](https://github.com/GSA/search-gov/commit/0e0b602e6fb1fe3594a24c915e9c54c28e210417)
- [SRCH-3720 Add Cucumber test for Bing results in SERP redesign](https://github.com/GSA/search-gov/commit/7ee591d002ee9ae13ead80f544dc4f6beaa9ec9b)
- [SRCH-3719 remove spec code re. 'pending_contact_information'](https://github.com/GSA/search-gov/commit/c8b8ee906d4d6a7617fd355fff3cb2a5a8c0760f)
- [SRCH-3717 rename watchers.*conditions columns to use JSON](https://github.com/GSA/search-gov/commit/2fd7adb38682d6f8271835b6605a99e59e7e9908)
Please ensure you have addressed all concerns below before …
=> Release - SRCH-3293, SRCH-3617, SRCH-3720, SRCH-3719, SRCH-3717

README.md, app/javascript/components/ResultsPage.tsx, app/javascript/components/test/ResultsPage.test.tsx, app/javascript/test/ResultsPage.test.tsx, jest.config.js, package.json, tsconfig.json, yarn.lock
This PR adds Jest and react-testing-library. Three tests have also been added for the SERP redesign React component.
=> SRCH-3671 Add Jest and react-testing-library

README.md, app/javascript/components/ResultsPage.tsx, app/javascript/test/ResultsPage.test.tsx, jest.config.js, package.json, tsconfig.json, yarn.lock
- SRCH-3671 Add Jest and react-testing-library (#1096)
=> Release - SRCH-3671

lib/api/v2/search_as_json.rb, spec/models/api_i14y_search_spec.rb
- Adds aggregations to the Results API response for an i14y query when `include_facets` is true.
=> SRCH-3739 Return aggregations in Results API

README.md, db/seeds/custom_index_data/news.rb, db/seeds/custom_index_data/videos.rb
This PR adds video seed data to facilitate testing and development. 
- ⚠️ Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
@danswick , the "checkout code" step isn't reporting back, which I'm guessing is one of the wrinkles you're working on. Is there a way to get this PR to pass?
=> SRCH-3781 add Youtube video seeds

app/controllers/api/v2/searches_controller.rb, app/controllers/application_controller.rb, spec/engines/domain_scope_options_builder_spec.rb, spec/models/i14y_search_spec.rb
- This itty-bitty PR includes no functional code changes, but is the end result of some time spent researching and documenting some discoveries from #1079 (The larger result of this effort was writing up some confluence documentation.)
- While I was poking around in some specs, I also did some rubocop cleanup.
=> SRCH-3619 sitelimit minor comments and cleanup

Gemfile.lock
This PR upgrades bundler to the latest version.
=> SRCH-3841 Upgrade bundler in search-gov

app/models/click.rb, app/models/search_impression.rb, lib/redactor.rb, lib/url_parser.rb, spec/lib/redactor_spec.rb, spec/lib/url_parser_spec.rb, spec/models/click_spec.rb, spec/models/search_impression_spec.rb
- SRCH-3908 redact PII from analytics log lines
=> Release - SRCH-3908

app/controllers/api/v2/searches_controller.rb, app/models/api_i14y_search.rb, app/models/filterable_search.rb, app/models/i14y_search.rb, lib/api/i14y_search_options.rb, lib/api/v2/search_as_json.rb, spec/controllers/api/v2/searches_controller_spec.rb, spec/fixtures/json/i14y/faq.json, spec/lib/api/i14y_search_options_spec.rb, spec/models/api_i14y_search_spec.rb, spec/models/i14y_search_spec.rb, spec/spec_helper.rb, spec/support/filterable_search_behavior.rb
- SRCH-3706 Add thumbnail_url to Results API /i14y response
- SRCH-3922 Add date filtering to Results API 
=> Release - SRCH-3706,SRCH-3922

app/javascript/components/SearchBar/SearchBar.css, app/javascript/components/SearchBar/SearchBar.tsx, app/javascript/components/SearchResultsLayout.css, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchBar.test.tsx, app/javascript/test/SearchResultsLayout.test.tsx
- SRCH-3633: fixed searchbar width and responsive issue for mobile view
=> Release - SRCH-3633

config/initializers/filter_parameter_logging.rb, spec/config/initializers/filter_parameter_logging_spec.rb
- SRCH-3929 Redact PII from request params in logs
=> Release - SRCH-3929 

lib/redactor.rb, spec/lib/redactor_spec.rb
- Redacts portions of search strings that match common US-style formatted phone numbers, while accounting for the possibility that spaces in the numbers may be URI-encoded (`+`).
=> SRCH-3919 Redact phone numbers in searches

.circleci/images/primary/Dockerfile.ruby306, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchBar/SearchBar.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/models/i14y_post_processor.rb, app/models/results_with_body_and_description_post_processor.rb, app/models/web_results_post_processor.rb, app/models/web_search.rb, features/blended_search.feature, features/step_definitions/affiliate_search_steps.rb, features/vcr_cassettes/Blended_Search/A_site_that_gets_commercial_results_and_has_a_document_collection.yml, spec/models/i14y_post_processor_spec.rb, spec/models/results_with_body_and_description_post_processor_spec.rb, spec/models/web_results_post_processor_spec.rb, spec/support/normalized_results.rb
- SRCH-4110 Paginate document collections
- SRCH-3960 Prepare backend data for SERP redesign results component 
=> Release - SRCH-4110, SRCH-3960

Gemfile, Gemfile.lock, app/jobs/searchgov_domain_indexer_job.rb, app/models/searchgov_domain.rb, app/models/searchgov_url.rb, db/migrate/20230418192652_remove_scheme_from_searchgov_domains.rb, db/schema.rb, spec/fixtures/searchgov_urls.yml, spec/jobs/searchgov_domain_indexer_job_spec.rb, spec/models/searchgov_domain_spec.rb, spec/models/searchgov_url_spec.rb
- SRCH-2469 prevent duplicate SearchgovDomainIndexerJobs from being enq…
- SRCH-4159 reduce SearchgovDomainIndexerJob lock timeout
- SRCH-3230 use 'https' for SearchgovDomains
=> Release - SRCH-2469, SRCH-3230, SRCH-4159 

db/migrate/20230426210615_drop_affiliate_twitter_settings.rb, db/migrate/20230426211104_drop_tweets.rb, db/migrate/20230426211256_drop_twitter_lists_twitter_profiles.rb, db/migrate/20230426211401_drop_twitter_profiles.rb, db/migrate/20230426211536_drop_twitter_lists.rb, db/schema.rb
- SRCH-4068 Drop Twitter-related db tables 
=> Release - SRCH-4068

app/controllers/admin/affiliates_controller.rb, app/models/searchgov_url.rb, db/migrate/20230502160301_add_hashed_url_to_searchgov_urls.rb, db/migrate/20230503151013_add_show_redesign_display_settings_to_affiliates.rb, db/migrate/20230503151057_add_use_redesigned_results_page_to_affiliates.rb, db/schema.rb, features/admin.feature, features/support/selectors.rb, lib/tasks/searchgov.rake, spec/controllers/admin/affiliates_controller_spec.rb, spec/models/searchgov_url_spec.rb
-  SRCH-4134 Add Super Admin flag to enable/disable "Show Redesign Display Settings"
-  SRCH-4135 Add Super Admin flag to enable/disable “Use Redesigned Results Page"
-  SRCH-4170 add hashed_url column to searchgov_urls
=> Release - SRCH-4170,SRCH-4135,SRCH-4134

app/controllers/sites/redesigned_displays_controller.rb, app/helpers/sites_helper.rb, app/javascript/components/Results/Results.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/views/sites/redesigned_displays/edit.html.haml, app/views/sites/shared/_manage_display_sub_nav.html.haml, config/locales/admin_center/en.yml, config/routes.rb, features/admin_center_manage_display.feature, features/redesigned_image_search.feature, features/support/paths.rb, spec/controllers/sites/redesigned_displays_controller_spec.rb
- SRCH-4104 provide alt text for img search results 
- SRCH-4130 Add Redesigned Display, preview to admin
=> Release - SRCH-4104, SRCH-4130

app/javascript/components/Header/BasicHeader.tsx, app/javascript/components/Header/ExtendedHeader.tsx, app/javascript/components/Header/index.tsx, app/javascript/components/Pagination/Pagination.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchBar/SearchBar.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchBar.test.tsx, tsconfig.json
This PR enables [TypeScript's strict mode](https://www.typescriptlang.org/tsconfig#strict), which provides additional code checks that lower the risk of bugs or unexpected behavior. TypeScript reported five new errors with strict mode enabled, which have been fixed in this PR. This has no effect on app behavior.
I've also used this PR as an opportunity to clean up how we use React props by using destructing. Again, no effect on app behavior, just cleaner code.
=> SRCH-4188 Enable TypeScript strict mode and fix new errors

app/models/govbox_set.rb, app/models/search.rb, spec/models/govbox_set_spec.rb
This PR makes text best bets data available as JSON, which will be using in upcoming tasks to integrate text best bets into the new SERP.
=> SRCH-3963 Prepare data for text best bets for SERP redesign

app/models/results_post_processor.rb, spec/models/results_post_processor_spec.rb
Due to a limit in the backend, we need to limit pagination in the redesigned SERP to 500 pages of results. This PR adds that limit.
=> SRCH-4191 Limit pagination to 500 pages in SERP redesign

app/javascript/components/Header/BasicHeader.tsx, app/javascript/components/Header/ExtendedHeader.tsx, app/javascript/components/Header/index.tsx, app/javascript/components/Pagination/Pagination.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchBar/SearchBar.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchBar.test.tsx, app/models/concerns/fetchable.rb, app/models/govbox_set.rb, app/models/indexed_document.rb, app/models/results_post_processor.rb, app/models/search.rb, app/services/sitemap_indexer.rb, package.json, spec/models/govbox_set_spec.rb, spec/models/indexed_document_spec.rb, spec/models/results_post_processor_spec.rb, spec/models/searchgov_url_spec.rb, spec/models/sitemap_spec.rb, spec/services/click_counter_spec.rb, spec/services/sitemap_indexer_spec.rb, spec/support/fetchable_behavior.rb, tsconfig.json, yarn.lock
- SRCH-4188 Enable TypeScript strict mode and fix new errors 
- SRCH-4084 Bump webpack from 5.74.0 to 5.76.0
- SRCH-3963 Prepare data for text best bets for SERP redesign
- SRCH-4191 Limit pagination to 500 pages in SERP redesign 
- SRCH-3383 enforce 'https' for SearchgovUrl and Sitemap URLs 
=> Release - SRCH-4188,SRCH-4084, SRCH-3963, SRCH-4191 ,SRCH-3383

Gemfile, Gemfile.lock, app/models/searchgov_url.rb, app/views/sites/redesigned_displays/_fonts_and_colors.html.haml, app/views/sites/redesigned_displays/edit.html.haml, config/locales/admin_center/en.yml, config/locales/dynamic_form.en.yml, db/migrate/20230504172002_add_index_on_hashed_url.rb, db/migrate/20230504173700_change_hashed_url_to_non_null.rb, db/schema.rb, features/admin_center_manage_display.feature, spec/fixtures/searchgov_urls.yml, spec/models/searchgov_url_spec.rb
- SRCH-4189 Upgrade react-rails gem in search-gov to latest version
- SRCH-4171 make hashed_url non-null
- SRCH-3383 require Searchgov URLs and sitemap URLs to use "https"
- SRCH-4141 Add redesigned "Fonts & Colors" section to Redesign Display page in Admin Center if "Show Redesign Display Settings" is true
=> Release - SRCH-4189, SRCH-4171, SRCH-3383, SRCH-4141

README.md
- Updated ReadMe for using search-gov within docker.
=> SRCH-4117 Update search-gov README about using docker

.dockerignore, .env/development/app, .env/development/resque, Dockerfile, Gemfile, Gemfile.lock, README.md, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/models/i14y_document.rb, app/models/searchgov_url.rb, app/views/searches/index_redesign.html.haml, config/secrets.yml.dev, docker/my.cnf, features/redesigned_searches.feature, package.json, spec/models/i14y_document_spec.rb, spec/models/searchgov_url_spec.rb, yarn.lock
- SRCH-3964: Integrate Text Best Bets UI Component
- SRCH-4079: Investigate and remove/bump uri from 0.10.0 to 0.10.0.1 (due by 7/11)
- SRCH-4241: SearchgovUrl#fetch should recover gracefully when "Document already exists with that ID"
=> Release - SRCH-3964, SRCH-4079, SRCH-4241

Gemfile.lock, app/engines/cached_search_api_connection.rb, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/models/i14y_post_processor.rb, app/models/results_with_body_and_description_post_processor.rb, app/models/web_results_post_processor.rb, config/environments/production.rb, config/initializers/datadog.rb, config/secrets.yml.dev, lib/faraday_middleware/exception_notifier.rb, spec/engines/cached_search_api_connection_spec.rb, spec/lib/faraday_middleware/exception_notifier_spec.rb, spec/models/i14y_search_spec.rb, spec/models/results_with_body_and_description_post_processor_spec.rb, spec/models/web_results_post_processor_spec.rb, spec/spec_helper.rb, spec/support/normalized_results.rb
- SRCH-4240 Remove unneeded nil/null attributes from web search res
- SRCH-4243 notify Datadog when the search client fails 
=> Release -SRCH-4240, SRCH-4243

Gemfile, Gemfile.lock
Quick PR to switch from Martha's fork to GSA's fork for this gem.
=> SRCH-4262 Switch to GSA fork of robotex gem

app/javascript/components/Results/BestBets/GraphicsBestBet.tsx, app/javascript/components/Results/BestBets/TextBestBet.tsx, app/javascript/components/Results/BestBets/index.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/models/govbox_set.rb, config/application.rb, features/redesigned_searches.feature, spec/models/govbox_set_spec.rb
- SRCH-3965, SRCH-3966 Prepare and integrate graphics best bets data 
=> Release - SRCH-3965, SRCH-3966 

app/models/i14y_post_processor.rb, app/models/results_post_processor.rb, app/models/results_with_body_and_description_post_processor.rb, app/models/web_results_post_processor.rb, config/routes.rb, features/redesigned_searches.feature, lib/advanced_searches_constraint.rb, spec/models/blended_search_spec.rb, spec/models/results_post_processor_spec.rb, spec/requests/advanced_searches_constraint_spec.rb
- SRCH-4105 Add highlighting HTML for web search results 
- SRCH-3494 Redirect to /search when SearchGov
=> Release - SRCH-4105, SRCH-3494

app/javascript/components/Results/Results.css, app/javascript/components/Results/Results.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/javascript/utils/index.tsx, app/models/i14y_post_processor.rb, app/models/results_post_processor.rb, app/models/results_with_body_and_description_post_processor.rb, app/models/web_results_post_processor.rb, features/redesigned_searches.feature, spec/models/results_post_processor_spec.rb
- SRCH-4086 Truncate long URLs and descriptions in SERP redesign
=> Release - SRCH-4086 Truncate long URLs and descriptions in SERP redesign 

app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/models/govbox_set.rb, app/models/searchgov_url.rb, db/migrate/20230530042618_add_index_to_searchgov_urls_searchgov_domain_id_and_last_crawled_at_and_lastmod_and_last_crawlstatus.rb, db/schema.rb, spec/fixtures/searchgov_urls.yml, spec/models/govbox_set_spec.rb, spec/models/searchgov_url_spec.rb, spec/vcr_cassettes/govbox_set/new_query_/affiliate_geoip_info_as_json_when_there_are_job_results.yml
- SRCH-3976 Prepare Backend Data for Jobs Module
- SRCH-3986 Prepare Backend Data for Federal Register Documents Module
- SRCH-3984 Prepare Backend Data for Health Topics Module
- SRCH-3380 improve SearchgovUrl#fetch_required prioritization
=> Release - SRCH-3976, SRCH-3986, SRCH-3984, SRCH-3380

app/models/news_search.rb, spec/models/news_search_spec.rb
This PR modifies the backend to pass RSS feed data to the redesigned SERP.
=> SRCH-3972 Prepare backend data for RSS feeds

package.json, yarn.lock
This PR upgrades Jest to the latest version, which should fix CI failures.
=> SRCH-4392 Upgrade jest to latest version

package.json
=> SRCH-4393 Run Jest tests serially in CI

app/javascript/components/Alert/Alert.css, app/javascript/components/Alert/Alert.tsx, app/javascript/components/Results/FedRegister/FedRegister.tsx, app/javascript/components/Results/HealthTopics/HealthTopics.tsx, app/javascript/components/Results/ImagesPage/ImagesPage.tsx, app/javascript/components/Results/Results.css, app/javascript/components/Results/Results.tsx, app/javascript/components/Results/RssNews/RssNews.tsx, app/javascript/components/Results/Videos/Videos.tsx, app/javascript/components/SearchBar/SearchBar.tsx, app/javascript/components/SearchResultsLayout.css, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/Alert.test.tsx, app/javascript/test/FedRegister.test.tsx, app/javascript/test/HealthTopics.test.tsx, app/javascript/test/ImagesPage.test.tsx, app/javascript/test/RssNews.test.tsx, app/javascript/test/Videos.test.tsx, app/models/news_search.rb, app/views/sites/api_instructions/_show_web_md.html.haml, package.json, spec/models/news_search_spec.rb, yarn.lock
- RCH-3896: Footer should extend to bottom of page when no results are shown
- SRCH-3989: Develop Search Page Alert (UI)
- SRCH-3970: Develop RSS Feed Module (UI)
- SRCH-3985: Develop Federal Register Documents Module (UI)
- SRCH-3983: Develop Health Topics Module (UI)
- SRCH-4344: Update SERP components placement and font styling as per Ginny's suggestions
- SRCH-4392: Upgrade Jest to fix search-gov CI
- SRCH-4393: Run Jest tests serially
- SRCH-3972: Prepare Backend Data for RSS Feed Page
- SRCH-4337: update API path
- SRCH-3644: Develop Videos Module UI Component
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain …
=> Release - See description below

app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/views/image_searches/index_redesign.html.haml, app/views/searches/index_redesign.html.haml, package.json, yarn.lock
This PR integrates internationalization into the SERP redesign.
=> SRCH-4271 Integrate internationalization into the SERP redesign

app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/views/image_searches/index_redesign.html.haml, app/views/searches/index_redesign.html.haml, package.json, yarn.lock
- SRCH-4271 Integrate internationalization into the SERP redesign
=> Release - SRCH-4271 Integrate internationalization into the SERP redesign

app/javascript/components/Results/NoResults/NoResults.css, app/javascript/components/Results/NoResults/NoResults.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchBar/SearchBar.css, app/javascript/components/SearchBar/SearchBar.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchBar.test.tsx, app/javascript/test/SearchResultsLayout.test.tsx
- Added component for No results
=> SRCH-3987: no results ui

app/javascript/components/Results/NoResults/NoResults.css, app/javascript/components/Results/NoResults/NoResults.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchBar/SearchBar.css, app/javascript/components/SearchBar/SearchBar.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchBar.test.tsx, app/javascript/test/SearchResultsLayout.test.tsx
- SRCH-3987: no results ui component
=> Release - SRCH-3987: no results ui component

yarn.lock
- SRCH-4356 Bump tough-cookie from 4.1.2 to 4.1.3 
- SRCH-4338 Bump word-wrap from 1.2.3 to 1.2.5 
- SRCH-4333 Bump semver from 6.3.0 to 6.3.1 
=> Release - SRCH-4356, SRCH-4338, SRCH-4333

app/javascript/components/Results/Jobs/Jobs.css, app/javascript/components/Results/Jobs/Jobs.tsx, app/javascript/components/Results/Results.css, app/javascript/components/Results/Results.tsx, app/javascript/test/Jobs.test.tsx, package.json, yarn.lock
=> SRCH-3975 jobs module UI

app/javascript/components/Results/Jobs/Jobs.css, app/javascript/components/Results/Jobs/Jobs.tsx, app/javascript/components/Results/Results.css, app/javascript/components/Results/Results.tsx, app/javascript/test/Jobs.test.tsx, package.json, yarn.lock
=> Release - SRCH-3975 jobs module UI 

Gemfile.lock
- SRCH-4402 Bump uri from 0.12.1 to 0.12.2
=> Release - SRCH-4402 Bump uri from 0.12.1 to 0.12.2

.circleci/config.yml, Gemfile.lock, spec/models/searchgov_domain_spec.rb
Update search-gov to use robotex latest changes
NOTE: Removal of Ruby 2.7.5 circleci tests requirement is needed.
=> SRCH-4440 + SRCH-3880 robotex version update & Remove Ruby 2.7 from CircleCI

.codeclimate.yml, app/javascript/components/SearchResultsLayout.tsx, app/models/govbox_set.rb, app/models/news_search.rb, app/models/results_with_body_and_description_post_processor.rb, spec/models/govbox_set_spec.rb, spec/models/results_with_body_and_description_post_processor_spec.rb
- SRCH-3995 Prepare Backend Data for Videos Page UI Component
- SRCH-3967 Prepare Backend Data for Videos Module UI Component
=> Release - SRCH-3995, SRCH-3967 (Prepare backend data for video results)

app/assets/stylesheets/legacy_sass/sayt/custom.sass, app/services/sitemap_indexer.rb, spec/services/sitemap_indexer_spec.rb, spec/vcr_cassettes/sitemap_indexer_index/_txt_sitemap_when_urls_are_extracted_from_sitemap.yml
- SRCH-1589 the sitemap indexer should process txt sitemaps
- SRCH-4387 typeahead is injecting content into partner site pages.
=> Release - SRCH-1589, SRCH-4387 

app/javascript/components/Results/Results.css, app/javascript/components/Results/Results.tsx, features/redesigned_searches.feature
- rendering html tags as readable text
=> SRCH-3638: render html tags as readable text

db/seeds/custom_index_data/news.rb
- One of our db seeds ceased to be a valid rss_feed, so we just need to update it to get CI back;
- This has no implication in production and does not require testing.
=> SRCH-4532 Update news_item seed data

app/helpers/mobile_navigations_helper.rb, app/helpers/react_helper.rb, app/javascript/components/SearchResultsLayout.tsx, spec/helpers/react_helper_spec.rb
- Setup navigations links data and send it to the `SearchResultsLayout` component
=> SRCH-3980 Prepare collections data

app/helpers/react_helper.rb, app/javascript/components/SearchResultsLayout.tsx, spec/helpers/react_helper_spec.rb
- SRCH-3990 Prepare Backend Data for Search Page Alert
=> Release - SRCH-3990 Prepare Backend Data for Search Page Alert

app/helpers/news_items_helper.rb, app/javascript/components/Results/Results.tsx, app/models/results_with_body_and_description_post_processor.rb, spec/models/news_search_spec.rb, spec/models/results_with_body_and_description_post_processor_spec.rb
- add published at date to news results
=> SRCH-4488 Add published at date to RSS news results backend data

app/helpers/news_items_helper.rb, app/javascript/components/Results/Results.tsx, app/models/results_with_body_and_description_post_processor.rb, spec/models/news_search_spec.rb, spec/models/results_with_body_and_description_post_processor_spec.rb
- SRCH-4488 Add published at date to RSS news results backend data
=> Release - SRCH-4488 Add published at date to RSS news results backend data

app/assets/javascripts/sites/edit_visual_design_form.js.coffee, app/assets/stylesheets/sites/_visual_design.less, app/controllers/admin/affiliates_controller.rb, app/controllers/sites/links_controller.rb, app/controllers/sites/visual_designs_controller.rb, app/helpers/instrumented_link_helper.rb, app/helpers/visual_design_helper.rb, app/models/affiliate.rb, app/models/footer_link.rb, app/models/identifier_link.rb, app/models/link.rb, app/models/primary_header_link.rb, app/models/secondary_header_link.rb, app/views/sites/links/_form.html.haml, app/views/sites/links/_new.html.haml, app/views/sites/links/new.js.haml, app/views/sites/visual_designs/_fonts_and_colors.html.haml, app/views/sites/visual_designs/_header_and_footer.html.haml, app/views/sites/visual_designs/_image_assets.html.haml, app/views/sites/visual_designs/_links.html.haml, app/views/sites/visual_designs/edit.html.haml, config/locales/admin_center/en.yml, config/routes.rb, db/migrate/20230901132250_add_identifier_text_fields_to_affiliates.rb, db/migrate/20230920210741_create_links.rb, db/schema.rb, features/admin_center_manage_display.feature, features/step_definitions/visual_design_steps.rb, spec/controllers/sites/links_controller_spec.rb, spec/models/link_spec.rb
- SRCH-4145 Header and footer links in admin center
=> Release - SRCH-4145 Header and footer links in admin center

app/helpers/news_items_helper.rb, app/helpers/react_helper.rb, app/javascript/components/SearchResultsLayout.tsx, spec/helpers/react_helper_spec.rb, spec/models/results_with_body_and_description_post_processor_spec.rb
- add backend data for news label and news items results 
=> SRCH-4502 Prepare backend data and integrate for News_Label

app/helpers/news_items_helper.rb, app/helpers/react_helper.rb, app/javascript/components/SearchResultsLayout.tsx, spec/helpers/react_helper_spec.rb, spec/models/results_with_body_and_description_post_processor_spec.rb
- SRCH-4502 Prepare backend data and integrate for News_Label 
=> Release - SRCH-4502 Prepare backend data and integrate for News_Label 

app/jobs/searchgov_domain_indexer_job.rb, app/models/searchgov_url.rb, db/migrate/20230926194650_remove_unused_searchgov_urls_indexes.rb, db/migrate/20230926203204_create_searchgov_urls_fetch_required_index.rb, db/schema.rb, spec/jobs/searchgov_domain_indexer_job_spec.rb
- SRCH-4528 mysql cpu optimization
=> Release - SRCH-4528 mysql cpu optimization

app/helpers/react_helper.rb, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchResultsLayout.test.tsx, features/redesigned_searches.feature, features/step_definitions/redesign_search_steps.rb
- Enables admin center users to change the header used in the redesigned SERP based on admin center settings
- Adds tests and test helpers as necessary
=> SRCH-4458 Integrate extended/basic header

config/elasticsearch_client.yml, spec/support/elasticsearch_client_behavior.rb
- [SRCH-4592 Disable Elasticsearch discovery](https://github.com/GSA/search-gov/commit/39d3f99a2a169d083b4f0c3ea64e23fa3540a983)
=> Release - SRCH-4592

app/views/layouts/searches_redesign.html.haml, app/views/shared/_affiliate_google_analytics.erb, app/views/shared/_google_tag_manager_noscript.erb, app/views/shared/_google_tag_manager_script.erb
- Add DAP GA to SERP redesign results page and remove rendering custom GA
- Add GTM for SERP redesign pages.
- Add third party tracking in SERP redesign pages.
=> SRCH-3668 Integrate DAP Google Analytics

app/views/layouts/searches_redesign.html.haml, app/views/shared/_affiliate_google_analytics.erb, app/views/shared/_google_tag_manager_noscript.erb, app/views/shared/_google_tag_manager_script.erb, app/views/sites/shared/_manage_display_sub_nav.html.haml, features/admin_center_manage_display.feature, yarn.lock
- SRCH-4591 Bump @babel/traverse from 7.20.1 to 7.23.2 
- SRCH-3668 Integrate DAP Google Analytics 
- SRCH-4530 Legacy sidebar links will disappear when Use Redesigned Dis…
- SRCH-3667 Include third party tracking codes in the new serp
- SRCH-3836 Add search team's GTM to SERP Redesign
=> Release - SRCH-4591, SRCH-3668, SRCH-4530, SRCH-3667, SRCH-3836 

app/javascript/components/VerticalNav/VerticalNav.css, app/javascript/components/VerticalNav/VerticalNav.tsx, app/javascript/test/VerticalNav.test.tsx
- The tabs navigation is made to behave very different on mobile so I had to move some styles into here
- Rearrange tabs on window resize
=> SRCH-4015 mobile tabs navigation

app/helpers/react_helper.rb, app/javascript/components/Results/Results.tsx, app/javascript/components/Results/Videos/VideosModule.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/VerticalNav.test.tsx, app/javascript/test/VideosModule.test.tsx, app/models/govbox_set.rb, features/redesigned_searches.feature, spec/helpers/react_helper_spec.rb
- SRCH-3968 videos module component
=> Release - SRCH-3968 videos module component 

config/locales/admin_center/en.yml
- Renamed label in Visual Design (new) form
=> SRCH-4639 Rename health benefits label

app/javascript/components/Pagination/Pagination.tsx, app/javascript/components/Results/HealthTopics/HealthTopics.tsx, features/redesigned_image_search.feature, features/redesigned_searches.feature, features/support/selectors.rb
- fixing 508 issues
- fixes for SRCH-4102. - Resolve svg-img-alt missing on redesigned SERP pagination component
- fixes for SRCH-4103 - Resolve empty link accessibility violation on redesigned News SERP
- Added use_redesigned_results_page flag for the missing cucumber scenarios
=> SRCH-4102, SRCH-4103 fixing 508/accessibility issues

config/locales/admin_center/en.yml
- Updates Admin Center language per ticket instructions
=> SRCH-4693 Update Admin Center text

app/javascript/components/Footer/Footer.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/contexts/StyleContext.ts, app/javascript/test/SearchResultsLayout.test.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- Integrates footer and results font into redesigned SERP pages;
- Updates snapshots; and,
- Also adds an additional snapshot test to remedy the fact we didn't previously have one that returned a page with results
=> SRCH-4448 Integrate footer and results font

Gemfile, Gemfile.lock, package.json, yarn.lock
- upgrade react-rails and react_ujs dependencies.
- Enabling StrictMode in development needs further discussion.
=> SRCH-4661 upgrade react-rails and react_ujs dependencies

Gemfile, Gemfile.lock, app/models/font_and_color_updater.rb, lib/tasks/font_and_color_updater.rake, package.json, spec/lib/tasks/font_and_color_updater_spec.rb, spec/models/font_and_color_updater_spec.rb, yarn.lock
- SRCH-4641 Rake task for updating fonts/colors
- SRCH-4661 upgrade react-rails and react_ujs dependencies 
=> Release - SRCH-4641, SRCH-4661

.codeclimate.yml, app/helpers/react_helper.rb, app/javascript/components/Header/BasicHeader.tsx, app/javascript/components/Header/ExtendedHeader.tsx, app/javascript/components/Identifier/Identifier.tsx, app/javascript/components/Identifier/IdentifierLogoWrapper.tsx, app/javascript/components/Results/FedRegister/FedRegister.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/FedRegister.test.tsx, app/javascript/test/Header.test.tsx, app/javascript/test/Identifier.test.tsx, features/redesigned_searches.feature, spec/helpers/react_helper_spec.rb
- SRCH-4465 Image assets data prep and integration
- SRCH-4643: pluralize the page count 
=> Release - SRCH-4465, SRCH-4643

app/javascript/components/Results/ResultGrid/ResultGrid.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/models/i14y_post_processor.rb, app/models/image_results_post_processor.rb, app/models/results_with_body_and_description_post_processor.rb, app/models/web_results_post_processor.rb, features/redesigned_searches.feature, spec/models/i14y_post_processor_spec.rb, spec/models/image_results_post_processor_spec.rb, spec/models/results_with_body_and_description_post_processor_spec.rb, spec/models/web_results_post_processor_spec.rb
- Send `fileType` from the backend where is a file extension in the results.
=> SRCH-4688/file_type Backend data prep and integration for FileType

features/redesigned_searches.feature
- Removes the few remaining instances of the `a11y_wip` tag from redesigned SERP cucumber tests - no new/remaining a11y violations.
=> SRCH-4556 Run a11y tests for redesigned SERP

app/javascript/components/Results/Jobs/Jobs.css, app/javascript/components/Results/Jobs/Jobs.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchBar/SearchBar.css, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/Jobs.test.tsx, features/redesigned_searches.feature
- SRCH-4642 jobs missing data integration 
- SRCH-4556 Run a11y tests for redesigned SERP
=> Release SRCH-4642, SRCH-4556

app/views/layouts/searches_redesign.html.haml
This reverts commit 0601871c1cc84056ab77c3ee7c119b6da0e2aa94.
=> Revert "SRCH-4714 Set crossorigin to anonymous (#1399)" (#1401)

app/models/govbox_set.rb
- SRCH-4711 Fix federal register documents error
=> Release - SRCH-4711

app/javascript/components/Results/ImagesPage/ImagesPage.tsx
- 2 column layout for mobile view for images
=> SRCH-4814: 2 column layout for mobile view for images

Gemfile, Gemfile.lock, app/javascript/components/Results/ImagesPage/ImagesPage.tsx, yarn.lock
- SRCH-4796 Bump follow-redirects from 1.15.3 to 1.15.4
- SRCH-4814: 2 column layout for mobile view for images 
- SRCH-4782 Bump puma from 5.6.7 to 5.6.8  
=> Release - SRCH-4796, SRCH-4814, SRCH-4782

app/helpers/react_helper.rb, app/views/image_searches/index_redesign.html.haml, spec/helpers/react_helper_spec.rb
- Add missing data to the image search layout.
- [] ⚠️ Automated checks pass. If Code Climate checks do not pass, explain reason for failures: Same Code Climate issue as in https://github.com/GSA/search-gov/pull/1343. It can be ignored for now.
=> SRCH-4773 Image view should have all the basic page components

app/javascript/components/Results/Results.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- Add `result_url_color` to RSS and Youtube results.
=> SRCH-4807 result URL color needs to respond to the admin center setting

app/javascript/components/Results/Results.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- SRCH-4807 result URL color needs to respond to the admin center setting
=> Release - SRCH-4807 result URL color needs to respond to the admin center setting

app/javascript/components/Header/ExtendedHeader.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/contexts/StyleContext.ts, app/javascript/test/SearchResultsLayout.test.tsx, app/models/affiliate.rb, config/locales/admin_center/en.yml
SRCH-4806 Rename "Secondary header background color" to "Header navigation background color"
=> SRCH-4806 Rename admin field to 'Header navigation background color'

app/javascript/components/Header/index.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- Choose the same color as the banner text color to ensure link is visible to end-users
=> SRCH-4816 Contrast issue with Here's how you know link in banner

app/javascript/components/Header/ExtendedHeader.tsx, app/javascript/components/Header/index.tsx, app/javascript/components/Results/BestBets/GraphicsBestBet.tsx, app/javascript/components/Results/Results.css, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/contexts/StyleContext.ts, app/javascript/test/SearchResultsLayout.test.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap, app/mailers/emailer.rb, app/models/affiliate.rb, config/locales/admin_center/en.yml, db/email_templates/affiliate_monthly_report.html.erb, db/email_templates/affiliate_yearly_report.html.erb, spec/mailers/emailer_spec.rb
- SRCH-4804 Order of graphics best bet links should be by columns
- SRCH-4800 updated module order 
- SRCH-4842 SRCH-4813: Logo text is not vertically centered
- SRCH-4806 Rename admin field to 'Header navigation background color
- SRCH-4840 Add commas to numbers in emailed reports
- SRCH-4816 Contrast issue with Here's how you know link in banner
=> Release -Description listed below

app/controllers/admin/odie_url_source_update_controller.rb, app/helpers/admin/odie_url_source_update_helper.rb, app/jobs/odie_url_source_update_job.rb, app/views/admin/home/index.html.haml, app/views/admin/odie_url_source_update/_form.html.haml, app/views/admin/odie_url_source_update/index.html.haml, config/i18n-tasks.yml.erb, config/locales/super_admin/en.yml, config/routes.rb, features/odie_url_source_update.feature, features/step_definitions/web_ext_steps.rb, features/support/paths.rb, spec/controllers/admin/odie_url_source_update_controller_spec.rb, spec/internationalization/i18n_spec.rb, spec/jobs/odie_url_source_update_job_spec.rb
- Allows Super Admins to trigger update of Indexed Document source from 'rss' to 'manual' for a selected affiliate
- Extends some translations to super admin through new internationalization setup 
=> SRCH-4836 ODIE url source update from Super Admin

Gemfile, Gemfile.lock, app/controllers/admin/odie_url_source_update_controller.rb, app/helpers/admin/odie_url_source_update_helper.rb, app/jobs/odie_url_source_update_job.rb, app/views/admin/home/index.html.haml, app/views/admin/odie_url_source_update/_form.html.haml, app/views/admin/odie_url_source_update/index.html.haml, config/i18n-tasks.yml.erb, config/locales/super_admin/en.yml, config/routes.rb, features/odie_url_source_update.feature, features/step_definitions/web_ext_steps.rb, features/support/paths.rb, spec/controllers/admin/odie_url_source_update_controller_spec.rb, spec/internationalization/i18n_spec.rb, spec/jobs/odie_url_source_update_job_spec.rb
- SRCH-4836 ODIE url source update 
- SRCH-4870 Bump nokogiri from 1.14.5 to 1.16.2
=> Release - SRCH-4836, SRCH-4870

app/models/govbox_set.rb
SRCH-4867 Truncate news item results descriptions
=> SRCH-4867 Truncate news item results descriptions

.rubocop.yml, app/controllers/sites/visual_designs_controller.rb, app/helpers/visual_design_helper.rb, app/javascript/components/Header/BasicHeader.tsx, app/javascript/components/Header/ExtendedHeader.tsx, app/javascript/components/Header/Logo.tsx, app/javascript/components/Identifier/Identifier.tsx, app/javascript/components/Results/FedRegister/FedRegister.tsx, app/javascript/components/Results/HealthTopics/HealthTopics.tsx, app/javascript/components/Results/Jobs/Jobs.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/Results/RssNews/RssNews.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/components/VerticalNav/DropDownMenu.tsx, app/javascript/components/VerticalNav/VerticalNav.tsx, app/javascript/contexts/StyleContext.ts, app/javascript/test/SearchResultsLayout.test.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap, app/models/affiliate.rb, app/views/sites/visual_designs/_font_selector.html.haml, app/views/sites/visual_designs/_fonts_and_colors.html.haml, config/locales/admin_center/en.yml, features/admin_center_manage_display.feature, spec/controllers/sites/visual_designs_controller_spec.rb, spec/helpers/visual_design_helper_spec.rb
- Add identifier_font_family, search_tabs_font_family, search_tabs_font_weight fields to design settings and use then on its respective components
- Refactor FontsAndColors types
- Move `visual_design_json` initialization to an `after_initialize` hook so default attributes are available right after initializing affiliate
=> SRCH-4808 SRCH-4809 SRCH-4810 SRCH-4694 Add tabs and identifier font settings

app/helpers/react_helper.rb, app/javascript/components/Header/Logo.tsx, app/javascript/components/SearchResultsLayout.css, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/Header.test.tsx, app/javascript/test/SearchResultsLayout.test.tsx
- SRCH-4839 Add link to header logo and title
=> Release - SRCH-4839 Add link to header logo and title

app/javascript/components/Header/ExtendedHeader.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- updated color for secondary links to use primary link color for mobile menu
=> SRCH-4815: updated color for secondary links to use primary link color for mobile menu

app/javascript/components/Header/ExtendedHeader.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- Fix for highlight color in primary nav has a contrast issue
=> SRCH-4812: Highlight color in primary nav

app/controllers/admin/affiliates_controller.rb, app/helpers/react_helper.rb, app/javascript/components/Header/ExtendedHeader.tsx, app/javascript/components/Results/BestBets/GraphicsBestBet.tsx, app/javascript/components/Results/BestBets/TextBestBet.tsx, app/javascript/components/Results/FedRegister/FedRegister.tsx, app/javascript/components/Results/Jobs/Jobs.tsx, app/javascript/components/Results/RelatedSearches/RelatedSearches.tsx, app/javascript/components/Results/ResultGrid/ResultGrid.tsx, app/javascript/components/Results/Results.css, app/javascript/components/Results/Results.tsx, app/javascript/components/Results/RssNews/RssNews.tsx, app/javascript/components/Results/Videos/Video.tsx, app/javascript/components/Results/Videos/VideosModule.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap, app/views/layouts/searches_redesign.html.haml, app/views/sites/shared/_manage_display_sub_nav.html.haml, app/views/sites/visual_designs/edit.html.haml, db/migrate/20240221024839_remove_show_redesign_display_settings_from_affiliates.rb, db/schema.rb, features/admin.feature, features/admin_center_manage_display.feature, features/redesigned_searches.feature, features/step_definitions/search_steps.rb, features/vcr_cassettes/Search_-_redesign/Search_with_video_results.yml, spec/controllers/admin/affiliates_controller_spec.rb
- SRCH-4879, SRCH-4851: highlight issue and graphics best bets links to
- SRCH-4868 Fix YouTube video timestamp on main search results 
- SRCH-4815: updated color for secondary links to use primary link color
- SRCH-4812: Highlight color in primary nav
- SRCH-4861 Set all search sites to show_redesign_display_settings=TRUE 
=> Release - Description in summary below

app/javascript/components/Identifier/Identifier.tsx, app/javascript/components/VerticalNav/VerticalNav.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- SRCH-4849 remove the hover from the css for the identifier
- SRCH-4858 Search tab dropdown underline hover color should use the navigation link color
=> Release - SRCH-4858, SRCH-4849

.rubocop.yml, app/controllers/clicked_controller.rb, app/helpers/react_helper.rb, app/javascript/components/Results/ResultGrid/ResultGrid.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/Header.test.tsx, app/javascript/test/ResultGrid.test.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/javascript/utils/constants.ts, app/javascript/utils/index.ts, app/models/results_with_body_and_description_post_processor.rb, package.json, spec/models/results_with_body_and_description_post_processor_spec.rb, yarn.lock
- Extends click tracking functionality to `web`, `i14y`, and `blended` verticals
=> SRCH-4915 Implement click tracking in web results

.rubocop.yml, Gemfile.lock, app/controllers/clicked_controller.rb, app/helpers/react_helper.rb, app/javascript/components/Results/ResultGrid/ResultGrid.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/Header.test.tsx, app/javascript/test/ResultGrid.test.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/javascript/utils/constants.ts, app/javascript/utils/index.ts, app/models/results_with_body_and_description_post_processor.rb, package.json, spec/models/results_with_body_and_description_post_processor_spec.rb, yarn.lock
- SRCH-4915 Implement click tracking in web results 
- SRCH-4928 Bump rack from 2.2.8 to 2.2.8.1 - LOW
=> Release - SRCH-4915, SRCH-4928

app/javascript/components/Results/ResultGrid/ResultGrid.tsx, app/javascript/components/Results/ResultGrid/ResultGridWrapper.tsx, app/javascript/components/Results/ResultGrid/ResultTitle.tsx, app/javascript/components/Results/Results.css, app/javascript/test/ResultGrid.test.tsx
- SRCH-4915 for mobile view: result div is clickable and does clickTracking
=> SRCH-4887: result div clickable in mobile view 

app/javascript/components/Results/BestBets/GraphicsBestBet.tsx, app/javascript/components/Results/BestBets/TextBestBet.tsx, app/javascript/components/Results/BestBets/index.tsx, app/javascript/components/Results/ResultGrid/ResultGrid.tsx, app/javascript/components/Results/ResultGrid/ResultTitle.tsx, app/javascript/components/Results/Results.tsx, app/javascript/test/BestBets.test.tsx, app/javascript/test/ResultGrid.test.tsx, app/javascript/utils/index.ts
- Adds click tracking for both text and graphics best bets;
- Builds upon #1488 
=> SRCH-4916 Best Bets click tracking

app/javascript/components/Results/BestBets/GraphicsBestBet.tsx, app/javascript/components/Results/BestBets/TextBestBet.tsx, app/javascript/components/Results/BestBets/index.tsx, app/javascript/components/Results/ResultGrid/ResultGrid.tsx, app/javascript/components/Results/ResultGrid/ResultTitle.tsx, app/javascript/components/Results/Results.tsx, app/javascript/test/BestBets.test.tsx, app/javascript/test/ResultGrid.test.tsx, app/javascript/utils/index.ts
- SRCH-4916 Best Bets click tracking 
=> Release - SRCH-4916 Best Bets click tracking 

app/javascript/components/Results/FedRegister/FedRegister.tsx, app/javascript/components/Results/HealthTopics/HealthTopics.tsx, app/javascript/components/Results/Results.tsx, app/javascript/test/FedRegister.test.tsx, app/javascript/test/HealthTopics.test.tsx, lib/tasks/medline.rake
- SRCH-4922: Federal register click tracking
- SRCH-4918 Health Topics click tracking
=> Release - SRCH-4922, SRCH-4918

app/controllers/admin/searchgov_domains_controller.rb, app/javascript/components/Results/Jobs/Jobs.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/Results/Videos/Video.tsx, app/javascript/components/Results/Videos/VideosModule.tsx, app/javascript/test/Jobs.test.tsx, app/javascript/test/Video.test.tsx, app/javascript/test/VideosModule.test.tsx, app/jobs/searchgov_domain_indexer_job.rb, app/models/searchgov_domain.rb, config/locales/super_admin/en.yml, config/routes.rb, spec/controllers/admin/searchgov_domains_controller_spec.rb, spec/jobs/searchgov_domain_indexer_job_spec.rb, spec/models/searchgov_domain_spec.rb
- SRCH-589 Stop Indexing
- SRCH-4920 Implement Video click tracking
- SRCH-4919: click tracking for jobs module
=> Release - SRCH-589, SRCH-4920

app/assets/stylesheets/admin.css, app/assets/stylesheets/admin_ie.css, app/assets/stylesheets/sayt.css
* Remove fingerprinting from image's url in admin stylesheets
=> SRCH-4865 bug: fix images url for admin stylesheets

app/models/image_content_updater.rb, lib/tasks/image_content_updater.rake, spec/lib/tasks/image_content_updater_spec.rb, spec/models/image_content_updater_spec.rb, spec/vcr_cassettes/image_content_updater/when_updating_image_content_when_all_ids_are_passed_to_update.yml, spec/vcr_cassettes/image_content_updater/when_updating_image_content_when_specific_ids_are_passed_to_update.yml
- Update new SERP image content settings data with old content settings data
=> SRCH-4961 Data Migration for Launch Support - ALL sites - Image Content settings

app/helpers/react_helper.rb, app/javascript/components/Results/Results.tsx, app/javascript/components/Results/SpellingSuggestion/SpellingSuggestion.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SpellingSuggestion.test.tsx, app/javascript/utils/constants.ts, app/models/header_and_footer_links_updater.rb, app/models/image_content_updater.rb, lib/tasks/header_and_footer_links_updater.rake, lib/tasks/image_content_updater.rake, spec/helpers/react_helper_spec.rb, spec/lib/tasks/header_and_footer_links_updater_spec.rb, spec/lib/tasks/image_content_updater_spec.rb, spec/models/header_and_footer_links_updater_spec.rb, spec/models/image_content_updater_spec.rb, spec/vcr_cassettes/image_content_updater/when_updating_image_content_when_all_ids_are_passed_to_update.yml, spec/vcr_cassettes/image_content_updater/when_updating_image_content_when_specific_ids_are_passed_to_update.yml, spec/vcr_cassettes/react_helper_search_results_layout/with_an_affiliate_with_type_ahead_suggestions.yml
- SRCH-4917 spelling suggestions click tracking 
- SRCH-4874 Data Migration for Launch Support - ALL sites - Content set
- SRCH-4961 Data Migration for Launch Support - ALL sites - Image Conte
=> Release - SRCH-4917, SRCH-4874, SRCH-4961

Gemfile.lock, app/controllers/admin/searchgov_domains_controller.rb, app/controllers/user_sessions_controller.rb, app/jobs/searchgov_domain_destroyer_job.rb, app/views/admin/searchgov_domains/delete_domain.html.haml, config/locales/en.yml, config/routes.rb, features/admin.feature, features/step_definitions/web_steps.rb, lib/login_dot_gov_settings.rb, spec/controllers/admin/searchgov_domains_controller_spec.rb, spec/controllers/user_sessions_controller_spec.rb, spec/internationalization/i18n_spec.rb, spec/jobs/searchgov_domain_destroyer_job_spec.rb
- SRCH-5032 send client_id instead of id_token 
- SRCH-5023 Bump json-jwt from 1.15.3 to 1.15.3.1
- SRCH-103: Super Admins should be able to destroy SearchGov domains
=> Release - SRCH-5032, SRCH-5023, SRCH-103

app/models/application_document.rb, app/models/html_document.rb, app/models/searchgov_url.rb, app/models/web_document.rb, spec/models/searchgov_url_spec.rb, spec/vcr_cassettes/searchgov_url_fetch/when_the_redirect_requires_a_cookie.yml, yarn.lock
- SRCH-5025 Bump follow-redirects from 1.15.4 to 1.15.6
- SRCH-5024 Bump webpack-dev-middleware from 5.3.3 to 5.3.4 
- SRCH-1919 use rel=canonical to avoid indexing duplicate content
=> Release -  SRCH-5025,  SRCH-5024, SRCH-1919

app/javascript/components/Header/BasicHeader.css
=> SRCH-5016: updated logo height

app/javascript/components/Pagination/Pagination.css
- updated css to show prev next buttons for mobile view
=> SRCH-5009: show prev next buttons for mobile view

.circleci/images/primary/Dockerfile.ruby330
- Adds a ruby 3.3.0 Dockerfile for circleci
- Removes the no longer needed ruby 2.7.5 Dockerfile
=> SRCH-4963 Add Ruby 3.3.0 image, remove 2.7.5

app/javascript/components/Results/ImagesPage/ImagesPage.tsx, app/javascript/components/Results/Results.tsx, app/javascript/test/ImagesPage.test.tsx
=> SRCH-4924 Images vertical click tracking

.circleci/images/primary/Dockerfile.ruby330, app/javascript/components/Header/BasicHeader.css, app/javascript/components/Pagination/Pagination.css, app/javascript/components/Results/ImagesPage/ImagesPage.tsx, app/javascript/components/Results/Results.tsx, app/javascript/test/ImagesPage.test.tsx
- SRCH-4924 Images vertical click tracking 
- SRCH-4963 Add Ruby 3.3.0 image, remove 2.7.5
- SRCH-5009: updated css to show prev next buttons for mobile view
- SRCH-5016: updated logo height
=> Release - SRCH-4924, SRCH-4963, SRCH-5009, SRCH-5016

Dockerfile, Dockerfile.dev, Gemfile, Gemfile.lock, bin/docker-entrypoint, bin/secure_docker, config/boot.rb, config/database.yml, config/initializers/recaptcha.rb
- Create Dockerfile for production
- Rename current Dockerfile to Dockerfile.dev
=> SRCH-4957 Setup search-gov production's Dockerfile

app/models/custom_font_and_color_theme_updater.rb, lib/tasks/custom_font_and_color_theme_updater.rake, spec/lib/tasks/custom_font_and_color_theme_updater_spec.rb, spec/models/custom_font_and_color_theme_updater_spec.rb
- Migrate fonts and colors from old SERP to Visual Design settings when Visual Design settings are not modified from default setting.
=> SRCH-4873 Data Migration for Launch Support - all sites with Custom theme - Visual design db column settings

app/controllers/admin/affiliates_controller.rb, app/helpers/react_helper.rb, app/javascript/components/Identifier/Identifier.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/Identifier.test.tsx, db/migrate/20240401142629_add_looking_for_government_services_to_affiliates.rb, db/schema.rb, spec/controllers/admin/affiliates_controller_spec.rb, spec/helpers/react_helper_spec.rb
SRCH-4893 Super Admin toggle for Looking for Government Services
=> SRCH-4893 Super Admin toggle for Looking for Government Services

Dockerfile, Dockerfile.dev, Gemfile, Gemfile.lock, app/controllers/admin/affiliates_controller.rb, app/helpers/react_helper.rb, app/javascript/components/Identifier/Identifier.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/Identifier.test.tsx, app/models/custom_font_and_color_theme_updater.rb, bin/docker-entrypoint, bin/secure_docker, config/boot.rb, config/database.yml, config/initializers/recaptcha.rb, db/migrate/20240401142629_add_looking_for_government_services_to_affiliates.rb, db/schema.rb, lib/tasks/custom_font_and_color_theme_updater.rake, spec/controllers/admin/affiliates_controller_spec.rb, spec/helpers/react_helper_spec.rb, spec/lib/tasks/custom_font_and_color_theme_updater_spec.rb, spec/models/custom_font_and_color_theme_updater_spec.rb
- SRCH-4957 Setup search-gov production's Dockerfile
- SRCH-4873 Data Migration for Launch Support - all sites with Custom t…
- SRCH-4893 Super Admin toggle for Looking for Government Services 
=> Release - SRCH-4957, SRCH-4873, SRCH-4893 

app/javascript/components/Header/BasicHeader.css, app/javascript/components/Header/ExtendedHeader.css, app/javascript/components/Header/index.css, app/javascript/components/Header/index.tsx, app/javascript/components/Results/Results.css
- updated the header syles to be more specific as it was interfering with identifier logo styles
- moved all the header related styles to one place at `app/javascript/componens/Header` folder
=> SRCH-5064: identifier logo bug fix

app/javascript/components/Header/BasicHeader.css, app/javascript/components/Header/ExtendedHeader.css, app/javascript/components/Header/index.css, app/javascript/components/Header/index.tsx, app/javascript/components/Results/Results.css
- SRCH-5064: identifier logo bug fix
=> Release- SRCH-5064: identifier logo bug fix 

app/models/i14y_post_processor.rb, spec/models/i14y_post_processor_spec.rb, spec/support/normalized_results.rb
SRCH-5012 Fix result snippets for I14y results
=> SRCH-5012 Fix result snippets for I14y results

app/models/i14y_post_processor.rb, spec/models/i14y_post_processor_spec.rb, spec/support/normalized_results.rb
- SRCH-5012 Fix result snippets for I14y results
=> Release - SRCH-5012 Fix result snippets for I14y results

app/javascript/components/Facets/Facets.css, app/javascript/components/Facets/Facets.tsx, app/javascript/components/SearchResultsLayout.css, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/Facets.test.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- Added Facets UI components for the desktop view
- Making filters selectable and other related work to be done with [SRCH-4988](https://cm-jira.usa.gov/browse/SRCH-4988) and [SRCH-4989](https://cm-jira.usa.gov/browse/SRCH-4989)
=> SRCH-3850 filters UI desktop

.circleci/images/primary/Dockerfile.ruby314
- Changing/renaming no-longer needed 3.2.2 dockerfile to ruby 3.1.4 (hopefully for the last time)
=> SRCH-5120 Create ruby 3.1.4 Dockerfile

.circleci/images/primary/Dockerfile.ruby314, .circleci/images/primary/Dockerfile.ruby322, app/javascript/components/Facets/Facets.css, app/javascript/components/Facets/Facets.tsx, app/javascript/components/SearchResultsLayout.css, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/Facets.test.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- SRCH-3850 filters UI desktop
- SRCH-5093 Add Ruby 3.2.2 image
- SRCH-5120 Create ruby 3.1.4 Dockerfile
=> Release -  SRCH-3850 filters UI desktop

app/javascript/components/Footer/Footer.tsx, app/javascript/components/Header/index.css, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- SRCH-5072: added padding for mobile header logo
- SRCH-5011: updated color for return to top
=> SRCH-5072, SRCH-5011: added padding for mobile header logo and updated color for return to top

config/elasticsearch_client.yml
- Use secrets for elasticsearch config
=> Continue using secrets for elasticsearch's username and password.

config/elasticsearch_client.yml
=> Continue using elasticsearch user and password from secrets (#1554)

app/javascript/components/Results/ResultGrid/ResultGrid.tsx, app/javascript/components/Results/Results.css, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/ResultGrid.test.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
=> SRCH-4987 fliter tags UI

db/migrate/20240508122013_change_default_use_redesigned_results_page_of_affiliates.rb, db/schema.rb, features/admin.feature, features/admin_center_activate_search.feature, features/admin_center_clicks_and_queries.feature, features/admin_center_dashboard.feature, features/admin_center_manage_content.feature, features/admin_center_manage_display.feature, features/admin_center_referrer_analytics.feature, features/admin_center_third_party_tracking.feature, features/admin_center_watchers.feature, features/blended_search.feature, features/image_search.feature, features/mobile_searches.feature, features/odie_url_source_update.feature, features/redesigned_image_search.feature, features/redesigned_searches.feature, features/searches.feature, features/searchgov_search.feature, features/trending_urls.feature, features/vcr_cassettes/Dashboard/Adding_a_new_site.yml, spec/controllers/image_searches_controller_spec.rb, spec/controllers/searches_controller_spec.rb, spec/fixtures/affiliates.yml, spec/system/click_tracking_spec.rb
SRCH-5150 Make use_redesigned_results_page=true the new default for new sites
https://cm-jira.usa.gov/browse/SRCH-5150
=> SRCH-5150 Make use_redesigned_results_page=true the new default for new sites

app/javascript/components/Results/ResultGrid/ResultGrid.tsx, app/javascript/components/Results/Results.css, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/ResultGrid.test.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap, db/migrate/20240508122013_change_default_use_redesigned_results_page_of_affiliates.rb, db/schema.rb, features/admin.feature, features/admin_center_activate_search.feature, features/admin_center_clicks_and_queries.feature, features/admin_center_dashboard.feature, features/admin_center_manage_content.feature, features/admin_center_manage_display.feature, features/admin_center_referrer_analytics.feature, features/admin_center_third_party_tracking.feature, features/admin_center_watchers.feature, features/blended_search.feature, features/image_search.feature, features/mobile_searches.feature, features/odie_url_source_update.feature, features/redesigned_image_search.feature, features/redesigned_searches.feature, features/searches.feature, features/searchgov_search.feature, features/trending_urls.feature, spec/controllers/image_searches_controller_spec.rb, spec/controllers/searches_controller_spec.rb, spec/system/click_tracking_spec.rb
- SRCH-5150 Make use_redesigned_results_page=true the new default
- SRCH-4987 fliter tags UI 
=> Release - SRCH-5150, SRCH-4987

app/javascript/components/Header/ExtendedHeader.css
- removed bg color from an active link on mobile on hover
=> SRCH-5083: Mobile menu active state contrast issue

bin/secure_docker
- Fix suid & sgid command
- Remove crontabs
- Remove init scripts
=> SRCH-5155 Improve container hardening

lib/es.rb
- `writer_config` needs to return an array with empty configuration when secrets file doesn't exists.
=>  SRCH-5227 Fix indexing creation

Dockerfile, lib/es.rb
- Set writer_config to return an array
- SRCH-5190 Make ASSET_HOST available during assets compilation and upd…
=> Release - SRCH-5190 

config/initializers/session_store.rb
- Use different redis for sessions
=> SRCH-5241 Use different redis for sessions

Dockerfile, config/initializers/session_store.rb
- This will potentially fix session sharing issue
=> SRCH-5241 Set session key config + SRCH-5284 Install chrome in container

.circleci/config.yml
=> SRCH-5277 - Update config.yml

.circleci/config.yml
=> SRCH-5277Update config.yml

.circleci/config.yml
=> SRCH-5277 Update config.yml

config/environments/production.rb
- Condition x_sendfile_header setting
=> SRCH-5277 Guard x_sendfile_header configuration

Dockerfile
- Install sendmail in Docker image 
=> SRCH-5325 Install sendmail in Docker image

app/javascript/components/Header/Logo.tsx, app/javascript/components/SearchBar/SearchBar.tsx
- added h1 tag to the site logo
=> fixed missing h1 - added h1 tag to site logo

app/javascript/components/UswdsOverrides/UswdsPagination.tsx
- updated aria labels for pagination to come from locales
=> SRCH-5270 updated aria labels for pagination to come from locales

app/javascript/components/Footer/Footer.tsx, app/javascript/components/Results/Results.tsx
- fixed return to top and skip to main links
=> SRCH-5266: fixed return to top and skip to main links

app/javascript/components/VerticalNav/VerticalNav.tsx
=> SRCH-5262 added aria-current tag

app/javascript/components/Header/BasicHeader.tsx, app/javascript/components/Header/ExtendedHeader.tsx, app/javascript/components/VerticalNav/VerticalNav.tsx, app/javascript/test/Header.test.tsx, config/locales/en.yml
- updated aria labels for navs
=> SRCH-5271 updated aria labels for navs

app/javascript/components/Footer/Footer.tsx, app/javascript/components/Header/index.tsx, app/javascript/components/SearchBar/SearchBar.tsx, config/locales/es.yml, features/redesigned_searches.feature
=> SRCH-5269: added missing translations

.env/development/app, app/controllers/sites/visual_designs_controller.rb, app/helpers/react_helper.rb, app/views/sites/visual_designs/_header_and_footer.html.haml, config/locales/admin_center/en.yml, config/secrets.yml.dev, db/migrate/20240806150030_add_show_vote_org_link_to_affiliates.rb, db/schema.rb, spec/controllers/admin/affiliates_controller_spec.rb
- Add `show_vote_org_link` to affiliates in admin section
- [ ⚠️ ] Automated checks pass. If Code Climate checks do not pass, explain reason for failures: A flakey rspec is failing, but it already passed here in the workflow before https://app.circleci.com/pipelines/github/krbhavith/search-gov/673/workflows/549059c7-856f-4ceb-a2d2-0d3c4a8b8489
=> SRCH-5350 Vote.gov link backend setup

.gitignore, README.md, app/javascript/components/Results/BestBets/TextBestBet.tsx, app/javascript/test/BestBets.test.tsx
- fix for best bets mobile view
=> SRCH-5473: fix for best bets mobile

app/javascript/components/Header/BasicHeader.tsx, app/javascript/test/Header.test.tsx
- showing secondary header links only for extended header
=> SRCH-4888: showing secondary header links only for extended header

buildspec_searchgov.yml
=> Cicd fix bundler

app/javascript/components/VerticalNav/VerticalNav.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- updated search tab nav color
=> SRCH-5172: updated search tab nav color

buildspec_searchgov.yml
- Add resque count env
- [x ] You have merged the latest changes from the target branch (usually `main`) into your branch.
- [x ] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.
- [x ] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
=> Add resque count env

app/javascript/components/Footer/Footer.css, app/javascript/components/Footer/Footer.tsx
- fixing width of footer links
=> SRCH-5148 fixing width of footer links

Gemfile.lock, db/migrate/20240912153029_add_not_null_constraints_to_booleans.rb
=> SRCH-5522 Migrations failing to execute on staging

app/javascript/components/Facets/Facets.tsx, app/javascript/components/Header/index.tsx, app/javascript/components/SearchBar/SearchBar.css, app/javascript/components/SearchBar/SearchBar.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- updated styling for mobile menu button
=> SRCH-5153 updated styling for mobile menu button

config/initializers/semantic_logger.rb
- Default log app name as searchgov-web
=> SRCH-5550 Default log app name as searchgov-web

config/deploy.rb
- Set puma systemctl user to system
=> SRCH-5557 Set puma systemctl user to system

config/initializers/omniauth.rb
- Make sure certificate exists before setting omniauth provider
=> SRCH-5558 Make sure certificate exists before setting omniauth provider

Gemfile, Gemfile.lock
=> Use puma and capistrano3-puma version as i14y and asis

Gemfile, Gemfile.lock
- Use puma and capistrano3-puma version as i14y and asis
=> Sync with main: Use puma and capistrano3-puma version as i14y and asis (#1690)

Gemfile, Gemfile.lock, buildspec_searchgov.yml
=> SRCH-5559 update capistrano puma version

Gemfile.lock, buildspec_searchgov.yml
=> SRCH-5559 update capistrano puma version (#1692)

Gemfile.lock, buildspec_searchgov.yml, config/deploy.rb, db/migrate/20241003164404_modify_active_storage_blobs_key_index.rb, db/schema.rb, lib/tasks/resque.rake
- This PR syncs staging with main
=> Sync staging with main

Gemfile.lock, buildspec_searchgov.yml, config/deploy.rb, config/initializers/resque.rb, db/migrate/20241003164404_modify_active_storage_blobs_key_index.rb, db/schema.rb, lib/tasks/resque.rake
=> Sync staging to main

app/models/news_item.rb, spec/models/news_item_spec.rb
=> SRCH-5565 Fix duration parsing

app/models/affiliate.rb
- Some request are failing when affiliate theme is not set
=> SRCH-5545 Make sure theme is set when loading css properties

config/application.rb
- Update configuration to the application.rb for a Rails 7.1 upgrade issue with changes to db.
- This PR syncs staging with main
=> SRCH-5543: DevToolsActivePort file doesn't exist error (#1704)

config/database.yml
* Add reconnection environment variable to DB config
=> Add reconnection environment variable to DB config (#1712)

config/database.yml, config/deploy.rb, config/sidekiq.yml
- This PR adds max threads count
=> Adds max threads count

bin/adjust_fetch_concurrency, bin/detect_future_usage, config/schedule.rb
=> SRCH-5609 Add missing cron jobs

Gemfile.lock, config/newrelic.yml
=> Setup newrelic app name based on SEARCH_ENV

config/deploy.rb
- Follow rails conventions and use WEB_CONCURRENCY for workers count.
=> Use WEB_CONCURRENCY to set puma workers.

config/schedule.rb
- Extra space is causing errors.
=> Fix for cron format

cicd-scripts/copy_non_fingerprinted_assets.sh
- This PR adds an additional copy command to the assets directory in the public directory.
=> SRCH-5621: non-fingerprinted versions of assets (symlinks). Script that runs as part of buildspec

cicd-scripts/copy_non_fingerprinted_assets.sh
- This PR adds another copy script to asset directory in public directory
=> Add copy script to asset directory in public directory

config/newrelic.yml
- Fix to match current name in newrelic
=> SRCH-5619 Setup newrelic app name as search.gov

config/database.yml, config/deploy.rb
- Update searchgov puma params to match other apps.
=> Use SEARCHGOV_THREADS and SEARCHGOV_WORKERS for puma settings

app/helpers/visual_design_helper.rb, config/locales/admin_center/en.yml, features/admin_center_manage_display.feature, spec/helpers/visual_design_helper_spec.rb
* SRCH-4889: updated header logo alt text
=> SRCH-4889: updated header logo alt text (#1711)

app/javascript/components/Facets/Facets.tsx, app/javascript/components/SearchBar/SearchBar.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/Facets.test.tsx, app/javascript/test/SearchBar.test.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/javascript/utils/index.ts
- facets shows UI checkboxes selected as per the query params
=> SRCH-4988 facets shows UI checkboxes selected as per the query params

app/javascript/components/Facets/Facets.tsx, app/javascript/test/Facets.test.tsx
- added clear button logic for facets
=> SRCH-4989: added clear filters button logic for facets

app/javascript/components/Facets/Facets.tsx, app/javascript/test/Facets.test.tsx
=> SRCH-4989: added clear button logic (#1736)

app/javascript/components/VerticalNav/VerticalNav.tsx, features/redesigned_searches.feature
- showing default tab only if there are other tabs
=> SRCH-4892: showing default tab only if there are other tabs

app/models/affiliate.rb, app/models/custom_filter.rb, app/models/filter.rb, app/models/filter_setting.rb, db/migrate/20241204172613_create_filter_settings.rb, db/migrate/20241204173320_create_filters.rb, db/schema.rb, spec/models/affiliate_spec.rb, spec/models/custom_filter_spec.rb, spec/models/filter_setting_spec.rb, spec/models/filter_spec.rb
- This PR adds new tables and models for filter settings. 
- This PR adds associations for filter settings and its affiliates.
- This PR adds specs for these new models.
- Requirements for this ticket can be found in this JIRA ticket: https://cm-jira.usa.gov/browse/SRCH-5043
=> [SRCH-5043] Add models for search filter settings for an affiliate.

buildspec_searchgov.yml, config/deploy.rb
-  Make sure scheduler is restarted after deploy
-  Remove duplicated puma and resque restarts
=> SRCH-5756 restart resque scheduler after deploy

config/resque_schedule.yml
- Update sitemap monitor job run frequency to every 4 hours
=> SRCH-5758 Update sitemap monitor job run frequency

config/resque_schedule.yml
- Set SitemapMonitorJob run frequency to every 4 hrs
=> SRCH-5758 Set SitemapMonitorJob run frequency to every 4 hrs

buildspec_searchgov.yml, config/deploy.rb, config/resque_schedule.yml
-  Sync hotfixes with main
-  Fix resque scheduler and sitemap monitor frequency
=> SRCH-5758 + SRCH-5756 Fix resque scheduler and sitemap monitor frequency

.circleci/config.yml, config/initializers/constants.rb, features/admin_center_manage_content.feature, features/support/env.rb, lib/js_fetcher.rb, spec/support/capybara.rb, spec/support/firefox_setup.rb
- Chrome is unable to parse studentaid urls but firefox can
=> SRCH-5760 Use firefox to fetch urls instead of chrome

config/deploy/development.rb
- Create capistrano deploy/development file
- Setup main branch to be use by the development environment
=> SRCH-5805 Create capistrano deploy/development file

db/migrate/20241216014720_restore_unused_searchgov_urls_indexes.rb
=> Make sure indexes doesn't exist before creation

bin/docker, db/seeds/drawer.rb
- Add main drawer to the seeds for easier local setup
=> Add main drawer to the seeds

config/initializers/es.rb, lib/search_elastic/document_repository.rb
- Example of how to pass this parameters to the task
```
NUMBER_OF_SHARDS=6 NUMBER_OF_REPLICAS=6 bin/rails search_elastic:create_index
```
=> SRCH-5849 parameterize shards and replicas

lib/js_fetcher.rb
- Update firefox settings to make sure it closes completely after crawling
- Fix user agent setting
=> SRCH-5877 SRCH-5244 Make Firefox exiting more resilient, fix user agent

app/controllers/admin/affiliates_controller.rb, app/engines/search_elastic_engine.rb, db/migrate/20250327175328_add_gets_results_from_all_domains_to_affiliates.rb, db/schema.rb, lib/js_fetcher.rb, lib/search_elastic/document_query.rb, lib/search_elastic/document_search.rb, spec/controllers/admin/affiliates_controller_spec.rb, spec/lib/search_elastic/document_query_spec.rb
- SRCH-5904 Setup affiliates to be bypass domains filter on search query
=> SRCH-5904 Setup affiliates to be bypass domains filter on search query

app/engines/bing_search.rb, app/engines/cached_search_api_connection.rb, app/engines/search_engine.rb, app/models/i14y_search.rb, spec/engines/search_engine_spec.rb
=> SRCH-5878 Fix from_cache flag in diagnostics

Gemfile, lib/data_generator/fake.rb
- The faker gem loads more than 2mb of dummy translations that are affecting the new SERP
- Moving gem to only dev and testing environments ensures production is not affected by it.
=> SRCH-5941 Use faker gem only on dev and test environments

app/controllers/admin/bulk_affiliate_delete_controller.rb, app/jobs/bulk_affiliate_delete_job.rb, app/services/bulk_uploader_base.rb, spec/controllers/admin/bulk_affiliate_delete_controller_spec.rb, spec/jobs/bulk_affiliate_delete_job_spec.rb
* Add bulk affiliate destroy upload.
---------
=> SRCH-5967 - Fix for Add bulk affiliate destroy upload (#1814)

app/views/layouts/searches.html.haml, app/views/layouts/searches_redesign.html.haml
- Add google tag manager data to old and new SERP
-Add tag manager script tags to old SERP
=> SRCH-5946 SRCH-5946 Setup google tag manager for old and new SERP

app/helpers/react_helper.rb, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/views/layouts/searches.html.haml, app/views/layouts/searches_redesign.html.haml
- Changes to Google tag manager from old SERP to new SERP
=> Latest main to staging

db/migrate/20250602213821_change_search_engine_from_affiliates.rb, db/schema.rb, features/admin.feature, features/admin_center_activate_search.feature, features/admin_center_clicks_and_queries.feature, features/admin_center_dashboard.feature, features/admin_center_manage_content.feature, features/admin_center_manage_display.feature, features/admin_center_referrer_analytics.feature, features/admin_center_third_party_tracking.feature, features/admin_center_watchers.feature, features/blended_search.feature, features/image_search.feature, features/mobile_searches.feature, features/odie_url_source_update.feature, features/redesigned_image_search.feature, features/redesigned_searches.feature, features/searches.feature, features/step_definitions/affiliate_steps.rb, features/step_definitions/web_steps.rb, features/trending_urls.feature, spec/fixtures/affiliates.yml, spec/models/affiliate_spec.rb
- Set SearchElastic as default search engine
- Update test to account for this change
=> SRCH-6022 Set SearchElastic as default search engine

app/controllers/admin/bulk_affiliate_add_controller.rb, app/jobs/bulk_affiliate_add_job.rb, app/mailers/bulk_affiliate_add_mailer.rb, app/services/bulk_affiliate_add_uploader.rb, app/views/admin/bulk_affiliate_add/index.html.haml, app/views/admin/home/index.html.haml, app/views/bulk_affiliate_add_mailer/notify.html.haml, app/views/bulk_affiliate_add_mailer/notify_parsing_failure.html.haml, config/routes.rb, spec/controllers/admin/bulk_affilate_add_controller_spec.rb, spec/fixtures/csv/add_affiliates.csv, spec/jobs/bulk_affiliate_add_job_spec.rb, spec/mailers/bulk_affiliate_add_mailer_spec.rb, spec/services/bulk_affiliate_add_uploader_spec.rb
* [SRCH-5486] Add Bulk Affiliate for user.
---------
=> [SRCH-5486] Add Bulk Affiliate for user. (#1835)

app/views/admin/home/index.html.haml
=> SRCH-6061 Add resque link to admin. (#1841)

app/helpers/mobile_navigations_helper.rb, app/helpers/navigations_helper.rb, app/views/sites/displays/_sidebar.html.haml, features/admin_center_manage_display.feature, spec/helpers/navigations_helper_spec.rb
- Avoid Images tab is still displayed on SERP.
=> SRCH-6025 Do not display images tab.

lib/search_elastic/document_query.rb
- Add new scoring function to searchelastic query that incorporates the DAP visits field.
- I have tested these query changes separately with David and Ammie 
- Tried this locally on data I loaded with this field.  Query seems to work.  Not sure what else I should test, open to ideas.
- I reviewed the spec folder and didn't see where I could improve test coverage for this change so didn't make any updates there.  Again, happy to add something if needed.
=> SRCH-6054 Add new scoring function for dap visits

app/assets/stylesheets/sites/_display.less, app/controllers/sites/users_controller.rb, app/models/user.rb, app/views/sites/users/index.html.haml, config/routes.rb, lib/tasks/user.rake, spec/fixtures/users.yml, spec/lib/tasks/user_spec.rb, spec/models/user_spec.rb
* Add 90-day timeout UI to admin users table.
---------
=> [SRCH-6057] Add 90-day timeout UI to admin users table. (#1857)
