app/views/sites/api_instructions/_commercial_keys_md.html.haml, app/views/sites/api_instructions/_show_web_md.html.haml, features/admin_center_activate_search.feature
We've had questions about the endpoint for accessing Garfield results and what the highlighting character is, so I'm updating the instructions to provide these answers proactively.
While I'm in here, I'm also removing mention of Google Site Search.
As I create this, I see that my CircleCI tests on the first two commits, but I don't know why that might be.
=> results api instrux update

app/controllers/api/v2/searches_controller.rb, app/views/sites/api_instructions/_show_web_md.html.haml, spec/controllers/api/v2/searches_controller_spec.rb
@MothOnMars it turns out that when the `/api/v2/search/i14y` endpoint was originally created, it was wired up to the wrong search options validator class. The `Api::NonCommercialSearchOptions` is just like the `Api::SearchOptions` class except that it adds the `sort_by` option which `I14yApiSearch` already knows how to properly consume.
=> [#158173466] Add sort_by=date support to /api/v2/search/i14y

app/models/i14y_search.rb, spec/models/api_i14y_search_spec.rb
The fact that we do a govbox search using i14y's spelling suggestion for the user's original search term instead of doing a govbox search using the user's original search term is causing trouble. The fix is to just use the user's original search term for the govbox search (and update the appropriate expectations in the specs, of course).
=> [#155989343] Use original i14y query instead of spelling suggestion for govbox searches

app/models/searchgov_url.rb, spec/models/searchgov_url_spec.rb
@noremmie , this change is intended to make it easier to separate domain errors in Airbrake. Currently, all domains with a '403' are lumped into the same Airbrake error, which means I can't mark an error as "resolved". (See https://usasearch.airbrake.io/projects/8947/groups/2240096797637687266?tab=overview .) 
This will also make it easier to see which domains are blocking us in Airbrake alerts.
=> include searchgov domain in domain error

spec/models/sitemap_indexer_spec.rb
@noremmie , this change is intended to prevent this spec from breaking when it's run in a different timezone, such as:
```
1) SitemapIndexer#index when the sitemap specifies a lastmod value sets the lastmod attribute
Failure/Error: expect(SearchgovUrl.last.lastmod.to_s).to match(/^2018-01-01/)
expected "2017-12-31 16:00:00 UTC" to match /^2018-01-01/
Diff:
@@ -1,2 +1,2 @@
-/^2018-01-01/
+"2017-12-31 16:00:00 UTC"
```
=> add timestamp to lastmod spec

app/models/html_document.rb, app/models/searchgov_url.rb, app/models/web_document.rb, spec/models/application_document_spec.rb, spec/models/html_document_spec.rb, spec/models/searchgov_url_spec.rb
- fix HtmlDocument#redirect_url method for quoted paths
=> [#158131076] follow client-side redirects for searchgov urls

lib/tasks/update_https.rake, spec/lib/tasks/update_https_spec.rb
- prevent update_https rake task from erroneously setting read-only
attributes
=> [#158922908] fix spec order dependency

spec/models/site_cloner_spec.rb
Ensures that RoutedQueryKeywordObserver is enabled, and that `ActiveRecord::Base.observers.enable :routed_query_keyword_observer` does not return nil.
=> Fixes spec order dependencies.

.circleci/config.yml, spec/spec_helper.rb
Changes spec_helper.rb config to run rspec tests in random order.
=> configure rspec to run with random order

app/helpers/jobs_helper.rb, features/mobile_searches.feature, spec/helpers/jobs_helper_spec.rb, spec/views/searches/index.html.haml_spec.rb
Update code so that the More jobs link no longer returns a 404 error and directs user to the correct USAJOBS page with the agencies selected.
=> SRCH-94 - fix more jobs search to not return 404

app/views/sites/displays/_govboxes.html.haml
SRCH-140 - Remove all references to Neogov
- the code is free of references to "Neogov" jobs
- the site admin display page doesn't mention Neogov jobs as a source
=> SRCH-140 - Cleanup Neogov jobs- related code

app/controllers/admin/affiliates_controller.rb, db/migrate/20181025225740_remove_nutshell_columns.rb, db/structure.sql, spec/controllers/admin/affiliates_controller_spec.rb
SRCH-21 migration to remove nutshell_id columns
- database migration to remove nutshell_id columns from the `users` and `affiliates` tables
=> Remove nutshell columns

config/secrets.yml.dev
The inclusion of the jobs secrets in the `secret_keys` section is necessary to ensure that those values will be filtered out of our VCR cassettes during test runs. (Note: there is a companion PR to update the `secrets.yml` file in `usasearch-cookbooks`: https://github.com/GSA/usasearch-cookbooks/pull/321)
=> SRCH-246 filter USAJOBS secrets from VCR cassettes

db/migrate/20181213153332_add_canonical_domain_to_searchgov_domains.rb, db/structure.sql
This migration adds the `canonical_domain` column to the `searchgov_urls` table.
=> SRCH-283 add canonical_domain to searchgov_urls table

app/models/html_document.rb, spec/models/html_document_spec.rb, spec/vcr_cassettes/searchgov_url_fetch/when_the_response_is_a_403_when_the_url_has_already_been_indexed_when_the_domain_is_unavailable.yml
This change allows us to parse the content from custom HTML tags, which we had previously been stripping out.
=> SRCH-286 retain unknown HTML tags

app/models/html_document.rb, spec/models/html_document_spec.rb
This change prevents us from indexing content that is likely to be the same on the majority of pages on a website.
=> SRCH-207 omit nav & footer elements when parsing HTML

app/assets/stylesheets/searches/custom_bootstrap/_sprites.less, deploy/before_symlink.rb
SRCH-438 - Search magnifying glass was not displaying properly
SRCH-431 - sayt compiled assets prevents users from outside using js in their landing page.
=> SRCH-438, SRCH-431 - fix the css so magnifying glass glyphicon displays properly and sayt works on main pages

app/jobs/click_counter_job.rb, app/jobs/click_monitor_job.rb, app/models/click_counter.rb, app/models/i14y_document.rb, app/models/rtu_top_clicks.rb, app/models/rtu_top_n.rb, config/resque_schedule.yml, spec/fixtures/json/rtu_dashboard/top_clicks_one_domain.json, spec/fixtures/json/rtu_dashboard/top_urls.json, spec/jobs/click_counter_job_spec.rb, spec/jobs/click_monitor_job_spec.rb, spec/jobs/sitemap_monitor_job_spec.rb, spec/models/click_counter_spec.rb, spec/models/i14y_document_spec.rb, spec/models/rtu_top_clicks_spec.rb, spec/support/searchgov_job_behavior.rb
Adds classes to calculate popular URLs for SearchgovDomains, and update the `click_count` for those URLs in the ES documents.
=> SRCH-400 update click counts for popular URLs

Gemfile, Gemfile.lock, app/models/searchgov_domain.rb, spec/models/searchgov_domain_spec.rb
SRCH-104 fix SearchgovDomain#domain validation
- remove explicit dependency on PublicSuffix gem
- clean up SearchgovDomain code per Rubocop
=> SRCH-104 fix SearchgovDomain#domain validation

app/models/click_counter.rb, spec/models/click_counter_spec.rb
This fixes a bug that I discovered when I started updating click counts in production. For URLs that have clicks but are not indexed (such as clicks from URLs that had been indexed, but are no longer available), the `ClickCounter` should log an error rather than dying completely.
=> SRCH-455 ClickCounter logs errors for missing I14y documents

.circleci/config.yml
This PR:
- upgrades our CircleCi config file to version 2.1
- uses a Docker image in our new `searchgov` Docker org instead of my personal account (which we should eventually set to be built automatically, but today is not that day)
- DRY's up our config file using some of the new 2.1 features
=> SRCH-343 use shared Docker image for CircleCi

.circleci/config.yml, .circleci/images/primary/Dockerfile
This PR adds an Elasticsearch 5.6 image to CircleCi, and runs Elasticsearch on port 9256. This will enable us to test the Logstash and custom index upgrades against a 5.6 cluster.
=> SRCH-457 run Elasticsearch 5.6 in CircleCi

Gemfile.lock, app/assets/stylesheets/searches/_main_menu.less
This PR fixes an issue where hovering over a link in the SERP "Browse" menu resulted in the link text becoming obscured by the hover highlighting. It also bumps the `scrypt` gem, which was necessary to get `bundle install` working.
=> SRCH-560 - fix hover highlight

features/admin_center_manage_content.feature, features/vcr_cassettes/Manage_Content/Add/edit/remove_RSS_Feed.yml
These cucumber tests were failing due to redirected RSS URLs. Why those weren't recorded on VCR cassettes, I have no idea. I've recorded those cassettes now, so these tests won't hit those external URLs in the future.
=> SRCH-586 update RSS feed URLs in cucumber tests

features/admin_center_manage_content.feature, features/step_definitions/rss_feed_steps.rb
@peggles2 , this is the follow-up I mentioned to https://github.com/GSA/search-gov/pull/279. This will prevent those cucumber tests from failing if/when the FDA decides to change those RSS URLs again.
=> SRCH-638 stub responses for RSS feeds in cucumber tests

spec/models/sayt_suggestion_spec.rb, spec/models/site_domain_spec.rb, spec/models/superfresh_url_spec.rb
SRCH-670 - If you are using ActionDispatch::Http::UploadedFile in your tests to upload files, you will need to change to use the similar Rack::Test::UploadedFile class instead.
=> SRCH-670 - Rails 5 new behavior when uploading files in test

config/environments/production.rb, spec/controllers/sites/query_downloads_controller_spec.rb
SRCH-696 - After rails 5 upgrade the rspec tests for query downloads failed due to slight change in the format.
=> update query_downloads_controller_spec to return correct format

Gemfile, Gemfile.lock
This PR upgrades the `sitemaps` gem to the latest version, which is compatible with Rails 5.
=> SRCH-700 update sitemaps gem to 0.2.3

spec/controllers/application_controller_spec.rb
Before Rails 5, when we forget to add template for an action, we get ActionView::MissingTemplate exception. with a 406 response. Now it returns 204 response and does not return MissingTemplate exception.
=> SRCH-714 - Rails 5 upgrade - rspec errors for missing template errors

app/views/searches/i14y.mobile.haml, features/searchgov_search.feature, features/vcr_cassettes/SearchGov_search/Video_news_search.yml
These changes were originally approved per https://github.com/GSA/search-gov/pull/292. We pulled them out per https://github.com/GSA/search-gov/pull/307, so this puts 'em back in.
=> SRCH-659 display videos on I14y SERP (#292)

app/models/user_session.rb, config/locales/authlogic.en.yml, config/locales/dynamic_form.yml, features/user_sessions.feature, spec/controllers/password_resets_controller_spec.rb
Login error message given have to be ambiguous so we updated the login failed and un-approved accounts to have the same message.
=> SRCH-689 - update generalized unauthorized message

spec/models/news_search_spec.rb, spec/support/filterable_search_behavior.rb
Rails 5 handles DateTime with better precision. 
You can see more info about it here https://blog.bigbinary.com/2016/02/23/rails-5-handles-datetime-with-better-precision.html.
The expected result should be 2014-11-30T23:59:59.999999999Z  instead of it being rounded off to 0
=> SRCH-724 - news_search_spec errors

spec/models/blended_search_spec.rb
No changes were needed except removing the pending code to comment out the tests. The problem has been resolved in:
SRCH-724 - news_search_spec.
Rails 5 handles DateTime with better precision.
You can see more info about it here https://blog.bigbinary.com/2016/02/23/rails-5-handles-datetime-with-better-precision.html.
=> SRCH-726 - blended_search_spec errors

spec/models/i14y_search_spec.rb
Same issue as SRCH-724.  The .end_of_day does not return the milliseconds that the results now return so this test fails.
=> SRCH-725-fix i14y_search_spec errors

config/environments/production.rb
SRCH-634 - Currently, the default value for `log_level` is `:info` for the production environment and `:debug` in all other environments. In Rails 5 the default value will be unified to `:debug` across all environments. To preserve the current setting, add the following line to your `production.rb`:
config.log_level = :info
=> SRCH-634 - Add default log_level to info

config/initializers/inflections.rb, spec/config/initializers/inflections_spec.rb, spec/helpers/search_helper_spec.rb
SRCH-723 - pluralize was not working for the Spanish words.
=> SRCH-723 - rails 5 upgrade search_helper_spec returns errors

app/controllers/admin/superfresh_urls_bulk_upload_controller.rb, spec/controllers/admin/superfresh_urls_bulk_upload_controller_spec.rb, spec/fixtures/txt/superfresh_urls.txt
This PR updates the `superfresh_urls_bulk_upload_controller_spec` to work with Rails 5. It also tweaks the controller code slightly to resolve a couple of Rubocop errors, including rescuing `Exception`.
=> SRCH-721 update superfresh_urls_bulk_upload_controller_spec.rb

app/models/language.rb, spec/lib/tasks/user_spec.rb
Rspec tests are now passing. This test was refactored during 
SRCH-688 - set users unapproved for inactive accounts
SRCH-726 - Bug/account approval
Just removing the pending code in the test.
=> SRCH-728 - rspec error - user_spec.rb

config/routes.rb, spec/controllers/image_searches_controller_spec.rb
SRCH-643 - In routs.rb, use concerns: :active_scaffold in resources instead of as_routes, or concerns :active_scaffold in resources block if want to disable association routes or restrict routes with only or except options
=> SRCH-643 - Fix deprecation warning for models using activescaffold

spec/models/site_cloner_spec.rb
SRCH-780 - Rails 5 -rspec site_clone returning errors.  The test was using ActiveRecord::Base.observers instead of ApplicationRecord.observers. Rails 5 we use ApplicationRecord which inherits from ActiveRecord::Base
=> SRCH-780 - Rails 5 -rspec site_clone returning errors

app/helpers/search_helper.rb
SRCH-784 - This is some code that really needs some refactoring in the future as its not following the MVC way. 
Rails 5 enforces strong params. By using permit, you have an opportunity to disallow setting attributes that you don't want passed to your url helper.
=> SRCH-784 - cucumber legacy_search.feature failing

app/controllers/help_docs_controller.rb, spec/controllers/help_docs_controller_spec.rb
SRCH-779 - Use \A and \z to match the start and end of the string, ^ and $ match the start/end of a line.
https://guides.rubyonrails.org/security.html#regular-expressions
=> SRCH-779 - update validations to use \A instead of ^

app/controllers/help_docs_controller.rb, spec/controllers/help_docs_controller_spec.rb
[SRCH-779] - update validations to use \A instead of ^
=> Release 1.15.14

.circleci/config.yml, config/secrets.yml.dev, spec/controllers/searches_controller_spec.rb, spec/lib/es_spec.rb, spec/models/elastic_boosted_content_spec.rb, spec/models/elastic_featured_collection_spec.rb, spec/models/elastic_federal_register_document_spec.rb, spec/models/elastic_news_item_spec.rb, spec/models/elastic_sayt_suggestion_spec.rb, spec/models/elastic_tweet_spec.rb, spec/models/news_search_spec.rb, spec/models/odie_search_spec.rb, spec/models/site_search_spec.rb, spec/models/web_results_post_processor_spec.rb, spec/models/web_search_spec.rb, spec/requests/api/c/rss_search_spec.rb, spec/requests/api/v2/search_spec.rb
The purpose of this PR is to get the `release/ES56_upgrade` passing, so that we can make subsequent changes with a more stable baseline. It:
- sets port 9256 for custom indices to ensure the specs run against Elasticsearch 5.6
- temporarily disables failing specs
- temporarily disables cucumber and coverage tests
=> SRCH-812 ensure ES56 upgrade branch passes CI

app/models/elastic_federal_register_document_query.rb, lib/elastic_settings.rb, spec/models/elastic_federal_register_document_spec.rb
This PR ensures that all our fields using the `ElasticSettings::KEYWORD` mapping are set to the `keyword` data type instead of `text`. It:
- adds a keyword normalizer, to replace the `case_insensitive_keyword_analyzer`
- specifies the `en_analyzer` for federal register docs (which are all in English)
- re-enables elastic_federal_register_document_spec.rb
It also removes the deprecated `standard` token filter, which does nothing in 5.6 and is removed entirely in 7.0:
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/analysis-standard-tokenfilter.html
=> SRCH-817 use 'keyword' for non-analyzed fields

spec/models/elastic_featured_collection_spec.rb
@peggles2 , these changes are similar to https://github.com/GSA/search-gov/pull/355 and https://github.com/GSA/search-gov/pull/356. I have re-enabled specs that were failing only because their searches required English text analysis (i.e. searching for `suggest` to find a doc with `suggests`). Because the per-language analysis is tested separately, I have disabled the per-language specs, and updated the other specs so they do not depend on English analyzers.
=> SRCH-823 re-enable ElasticFeaturedCollection specs where possible

spec/models/elastic_sayt_suggestion_spec.rb
@peggles2 , these changes are similar to https://github.com/GSA/search-gov/pull/355. I have re-enabled specs that were failing only because their searches required English text analysis (i.e. searching for `suggest` to find a doc with `suggests`). Because the per-language analysis is tested separately, I have disabled the per-language specs, and updated the other specs so they do not depend on English analyzers.
=> SRCH-821 re-enable ElasticSaytSuggestion specs where possible

spec/models/elastic_boosted_content_spec.rb
This PR fixes and re-enables specs that were failing erroneously. Several of the specs in elastic_boosted_content_spec.rb were failing because we have temporarily switched from per-language analyzers to the `standard` analyzer. This broke specs where, for example, a query for `carrot` is not returning results for `carrots`. The specs in question were not intended to test language analysis, so it's preferred to simplify those specs; language analysis has its own specs, which have been commented out temporarily.
=> SRCH-828 re-enable ElasticBoostedContent specs where possible

app/controllers/application_controller.rb
The proper way to return 406 error for wrong format is through defining the format in the controller then anything else will return a 406. Currently what is on production is not working and we get 500 errors for the wrong format. Rails 5 does not even go through this method anyway so taking it out.
=> SRCH-820 - remove the template_not_found method not needed for rails 5

config/initializers/callback_terminator.rb
Before Rails 5, returning false from any before_ callback in ActiveModel or ActiveModel::Validations, ActiveRecord and ActiveSupport resulted in halting of callback chain.
Rails 5 fixed this issue by adding throw(:abort) to explicitly halt callbacks.
To opt out of behavior update the initializer. But it will have to be addressed before we upgrade to Rails 5.2
=> SRCH-362 - Halt callback chain

.rubocop.yml, config/secrets.yml.dev, lib/es.rb, spec/lib/es_spec.rb, spec/support/shared_vcr_setup.rb
(Note: I'll update the JIRA story ID once we regain access to JIRA.)
This PR is intended to allow us to access Elasticsearch using basic authorization. I have added a DNM label, as it will need to be released in tandem with https://github.com/GSA/usasearch-cookbooks/pull/375.
I also tweaked rubocop.yml not to require parentheses around args passed to `require`.
=>  SRCH-?? use basic auth for elasticsearch client

app/models/elastic_data/elastic_news_item_data.rb, spec/models/elastic_news_item_spec.rb
This PR resolves a production bug that I discovered during migration testing. News items need to be indexed using the associated affiliate's "indexing locale" (accessible via the `NewsItem#owner_language_guess` method), rather than the `news_item.language` method. This ensures that news items that are not in English or Spanish will be indexed using the `babel` analyzer.
=> SRCH-914 index news items in non-standard languages

lib/es.rb, spec/lib/es_spec.rb
These changes ensure that the secrets used to configure Elasticsearch cannot be mutated.
=> SRCH-948 freeze secrets for Elasticsearch config

config/elasticsearch_client.yml, config/secrets.yml.dev, lib/es.rb, spec/lib/es_spec.rb, spec/support/elasticsearch_client_behavior.rb
This PR updates the configuration for the ES client used by the custom indices. This allows us to pass all the ES hosts directly to the client, rather than a single haproxy listener.
I am adding a "Do Not Merge" label, as this depends on a corresponding update in the cookbooks.
=> SRCH-955 pass an array of hosts to Elasticsearch client

app/views/users/_form.haml, features/step_definitions/affiliate_steps.rb
This pull request removes the password fields for edit account page. 
cleaned up a cucumber test.
Note: A lot of cucumber and rspec tests will need to be cleaned up. I am leaving this for the end. Jira ticket # SRCH-993
=> SRCH-892 - remove password fields for edit my account page

spec/controllers/help_docs_controller_spec.rb, spec/requests/api/v2/search_spec.rb, spec/requests/clicked_spec.rb, spec/requests/image_searches_spec.rb, spec/requests/sayt_spec.rb, spec/requests/searches_spec.rb, spec/requests/statuses_spec.rb
This PR resolves these deprecation warnings in our specs:
```
DEPRECATION WARNING: Using positional arguments in integration tests has been deprecated,
in favor of keyword arguments, and will be removed in Rails 5.1.
```
=> SRCH-628 resolve deprecation warnings re. positional arguments

app/controllers/sites/sites_controller.rb
removed deprecated redirect_to :back call
fixed rubocop warning about method calls without parentheses.
=> remove deprecated `redirect_to :back`

config/secrets.yml.dev, spec/lib/es_spec.rb
This PR is analogous to https://github.com/GSA/search-gov/pull/385. These changes allow us to pass an array of hosts to the analytics client config. I'm adding a `do-not-merge` label, as this release needs to be coordinated with the corresponding changes in the cookbooks.
=> SRCH-1011 pass array of hosts to ES::ELK.client_reader/writers

config/secrets.yml.dev, spec/lib/es_spec.rb
[SRCH-1011] - pass array of hosts to ES::ELK.client_reader/writers
=> Release 1.15.24 

Gemfile, Gemfile.lock
Upgraded to forked version of less-rails-bootstrap gem to address sprockets deprecation warning. The main build of this gem appears to no longer be maintained 
[https://github.com/metaskills/less-rails-bootstrap/pull/132](https://github.com/metaskills/less-rails-bootstrap/pull/132)
=> Upgraded less-rails-bootstrap gem

app/controllers/sites/youtube_profiles_controller.rb, spec/controllers/sites/youtube_profiles_controller_spec.rb
@peggles2 , this resolves a deprecation warning I missed in SRCH-631 as it only appeared in a cucumber test:
```
DEPRECATION WARNING: Passing an argument to force an association to reload is now deprecated and will be removed in Rails 5.1. Please call `reload` on the result collection proxy instead. (called from after_profile_deleted at /Users/Moth/src/GSA/search-gov-GSA/app/controllers/sites/youtube_profiles_controller.rb:15) 
```
=> SRCH-1053 resolve deprecation related to association reloading

app/models/logstash_queries/module_breakdown_query.rb, spec/models/logstash_queries/module_breakdown_query_spec.rb
This PR updates the ModuleBreakdownQuery to run on Elasticsearch 5.6.
=> SRCH-1041 update ModuleBreakdownQuery

db/migrate/20191113214448_change_uid_index.rb, db/structure.sql, spec/models/user_spec.rb
This pull request removes the uniq index so that if a user has multiple emails per uid they can still login. 
Migration file included
=>     SRCH-1059 - remove uniq index from UID

Gemfile, Gemfile.lock, app/controllers/sites/analytics_controller.rb, app/controllers/sites/click_queries_controller.rb, app/controllers/sites/query_clicks_controller.rb, app/controllers/sites/query_referrers_controller.rb, app/controllers/sites/referrer_queries_controller.rb, app/models/click_counter.rb, app/models/logstash_queries/date_range_top_n_field_query.rb, app/models/logstash_queries/date_range_top_n_missing_query.rb, app/models/rtu_monthly_report.rb, features/step_definitions/time_travel_steps.rb, features/support/hooks.rb, spec/controllers/human_sessions_controller_spec.rb, spec/controllers/sites/click_queries_controller_spec.rb, spec/controllers/sites/query_clicks_controller_spec.rb, spec/controllers/sites/query_referrers_controller_spec.rb, spec/controllers/sites/referrer_queries_controller_spec.rb, spec/jobs/searchgov_domain_indexer_job_spec.rb, spec/models/click_counter_spec.rb, spec/models/document_fetch_logger_spec.rb, spec/models/logstash_queries/date_range_top_n_field_query_spec.rb, spec/models/logstash_queries/date_range_top_n_missing_query_spec.rb, spec/models/rtu_monthly_report_spec.rb, spec/spec_helper.rb
- update DateRangeTopNMissingQuery
- update DateRangeTopNFieldQuery
- replace Timecop with ActiveSupport::Testing::TimeHelpers
=> SRCH-1039 SRCH-1040 update DateRangeTopN queries to run on ES 5.6

app/models/logstash_queries/trending_terms_query.rb, spec/models/logstash_queries/top_n_query_spec.rb, spec/models/logstash_queries/trending_terms_query_spec.rb
This PR tweaks a couple of field names. I realized when testing some queries on production that the logstash template hadn't been applied to the production 5.6 cluster. The field names have been corrected to work with the template mappings.
=> tweak raw fields

spec/models/logstash_queries/elastic_link_popularity_query_spec.rb
This PR updates the ElasticLinkPopularityQuery spec to ensure it does not raise errors in Elasticsearch. No code changes were necessary.
=> SRCH-1071 update ElasticLinkPopularityQuery spec

app/models/logstash_queries/query_breakdown_for_site_module_query.rb, spec/models/logstash_queries/query_breakdown_for_site_module_query_spec.rb
SRCH-1073 update QueryBreakdownForSiteModuleQuery for Elasticsearch 5.6
=> SRCH-1073 update QueryBreakdownForSiteModuleQuery for Elasticsearch 5.6

lib/es.rb, spec/support/elasticsearch_client_behavior.rb
symbolizing config keys so that the tests run correctly.
=> KNOLLFEAR/SRCH-988-3 Symbolizing config keys

app/models/alert.rb, app/models/flickr_profile.rb, app/models/routed_query_keyword_observer.rb
Fixing both deprecations for the rails 5.2 upgrade
1092 - DEPRECATION WARNING: Passing string to be evaluated in :if and :unless conditional options is deprecated and will be removed in Rails 5.2 without replacement.
1093 - DEPRECATION WARNING: The behavior of `attribute_was` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `attribute_before_last_save` instead.
=> Knollfear/srch 1092&1093

.circleci/config.yml, .rubocop.yml, app/models/low_query_ctr_watcher.rb, app/models/watcher.rb, features/admin_center_watchers.feature, spec/fixtures/json/watcher/low_query_ctr_watcher_body.json, spec/models/elastic_sayt_suggestion_spec.rb, spec/models/logstash_queries/watcher_low_ctr_query_spec.rb, spec/models/low_query_ctr_watcher_spec.rb, spec/models/no_results_watcher_spec.rb, spec/support/watcher_behavior.rb
This PR updates the LowQueryCtrWatcher for Elasticsearch 5.6.
=> SRCH-1048 update LowQueryCtrWatcher for Elasticsearch 5.6

app/models/site_feed_url.rb, config/initializers/http_connection.rb, spec/models/site_feed_url_spec.rb
- validate that SiteFeedUrl#rss_url is a valid URL
- use `URI.parse(url).open` instead of `Kernel.open`
=> SRCH-1102 validate SiteFeedUrl#rss_url

app/models/rtu_query_raw_human_array.rb, app/models/rtu_top_n.rb, spec/models/rtu_query_raw_human_array_spec.rb, spec/models/rtu_top_n_spec.rb
This PR:
- fixes an issue preventing top queries from appearing on the site dashboard
- adds specs for the fix
- adds logging for failed ES searches
=> SRCH-1134 display top queries on site dashboard

lib/ctrs.rb, spec/models/search_module_ctr_spec.rb
This PR fixes a bug that prevented "Search Module CTRs" data from appearing in super admin.
=> SRCH-1141 display search module CTRs in super admin

app/models/request_drilldown.rb, spec/models/request_drilldown_spec.rb
Elasticsearch 5.6 limits results to 10k. Dawn has approved this limit for CSV files downloaded from the site analytics pages.
=> SRCH-1094 limit analytics downloads to 10k results

app/models/logstash_deduper.rb, spec/models/logstash_deduper_spec.rb
This PR:
- updates the LogstashDeduper to work on ES 5.6
- adds a spec to ensure the deduper does not raise an error
=> SRCH-1143 update LogstashDeduper for Elasticsearch 5.6

app/models/youtube_profile.rb, spec/fixtures/affiliates.yml, spec/fixtures/youtube_profiles.yml, spec/models/youtube_profile_spec.rb
This pull request removes uniq and places it with distinct as uniq is deprecated in rails 5.0 and was removed in rails 5.1.
=> SRCH-1165 - Youtube rake tasks should run successfully

app/models/user.rb, spec/fixtures/users.yml, spec/models/user_spec.rb
This pull request is to create a scope in the User model to collect all users that have been not active for a given number of days. 
For example if you pass the number 76 you can get back all the users that were not active for exactly 76 days.
=> SRCH-1191 - create not_active_for scope that passes time parameter

app/models/user.rb, features/step_definitions/web_ext_steps.rb, spec/fixtures/users.yml, spec/models/user_spec.rb
[SRCH-1191] - create not_active_for scope that passes time parameter (#516 …
[external contributor, checked by Martha] - replace Kernel.open which lets data spawn shells with URI.parse to protect against RCE
=> Release 1.16.9

lib/elastic_query.rb
This change specifies the highlighter type used by Elasticsearch in order retain the current behavior once we upgrade to ES 6.8.
=> SRCH-534 specify fvh highlighter type

db/migrate/20200212183209_add_firstname_lastname_to_users.rb, db/structure.sql
This pull request is to just add 2 columns to the users table named first_name and last_name
These two columns will eventually replace contact_name column. 
DEPLOYMENT NOTES:
Migration needed on production
=> SRCH-1266 - Create first_name last_name column in users table

lib/tasks/user.rake, spec/lib/tasks/user_spec.rb
This pull request is so that our chef cookbooks would only pass a number rather than figuring out the date 76 days ago or 86 days ago. Instead it will pays the number 76 and the code will interpret that part.
=> change it so that the rake task only passes the number of days not the date

lib/tasks/user.rake, spec/fixtures/users.yml, spec/lib/tasks/user_spec.rb
This pull request fixes a bug where inactive unapproved users were getting emails. The warning emails should only be sent to approved users that have been inactive.
=> SRCH-1304 - warn only approved users

Gemfile, Gemfile.lock
[SRCH-1311] - Update Nokogiri security vulnerability for search.gov
[SRCH-1325] - Update puma 3.12.4 security vulnerability for search.gov
=> Release 1.16.20

app/models/govbox_set.rb, spec/models/govbox_set_spec.rb
This PR adds some logic to prevent searches from triggering unnecessary Elasticsearch queries.
=> SRCH-1355 prevent searches from running unnecessary Elasticsearch queries

app/mailers/emailer.rb, db/email_templates/account_deactivation_warning.html.erb, spec/mailers/emailer_spec.rb
In this pull request, the email warning wording is tweaked so costumers understand that even if their account is de-activated their sites will work just fine. 
Deployment notes
Templates need to be reloaded in the rails console on production to reflect the wording change:
EmailTemplate.load_default_templates
=> 90 deactivation email clarity 

app/controllers/sites/click_drilldowns_controller.rb, app/controllers/sites/query_drilldowns_controller.rb, app/models/logstash_queries/drilldown_query.rb, app/models/request_drilldown.rb, lib/analytics_dsl.rb, spec/controllers/sites/click_drilldowns_controller_spec.rb, spec/controllers/sites/query_drilldowns_controller_spec.rb, spec/models/logstash_queries/drilldown_query_spec.rb, spec/models/request_drilldown_spec.rb
This PR updates the analytics queries to search by the `type` field, rather than by document type, which has been deprecated.
=> SRCH-1371 update drilldowns to query by `type` field

app/models/user.rb, spec/fixtures/users.yml, spec/models/user_spec.rb
This pull request allows a user to be looked up by the unique identifier passed from login.gov. 
Sometimes users are logging in with their other email account from login.gov. Sometimes they changed their email address on login.gov.  Currently the app looks up a user by email. If the user does not exist it creates them.  Additional code is added for the following scenarios:
1) user logs in with different .gov email that does not exist in our system. 
(uid has 1 user associated in search.gov)
User account is looked up by uid and that account is pulled up. Email has to be manualy changed by admin for now
2) user logs in with different email that is non gov and does not exists in the system. 
(uid has 1 user associated in search.gov)
User account is not looked up by uid because this user is …
=> Changes made to find user by UID

app/views/users/_form.haml, features/users.feature
This pull request disables the email field email field in  /account/edit.  Adds the following message "To update your email address, please contact the Search.gov team at search@support.digitalgov.gov"
=> SRCH-1387 - disable email address field for admin center

app/models/logstash_queries/rtu_date_range_query.rb, app/models/rtu_date_range.rb, spec/models/logstash_queries/rtu_date_range_query_spec.rb, spec/models/rtu_date_range_spec.rb
This PR updates the `RtuDateRangeQuery` to filter by `"type"`, which is necessary after passing the type to the client was deprecated in ES 6.
=> SRCH-1364 update RtuDateRangeQuery for compatibility with ES 6

app/models/link_popularity.rb, app/models/logstash_queries/elastic_link_popularity_query.rb, spec/models/link_popularity_spec.rb, spec/models/logstash_queries/elastic_link_popularity_query_spec.rb
This PR updates the `ElasticLinkPopularityQuery` to filter by `"type": "click"`, which is necessary after passing the type to the client was deprecated in ES 6.
=> SRCH-1384 update LinkPopularity query search by `type` field

lib/tasks/sayt_suggestions.rake, spec/lib/tasks/sayt_suggestions_spec.rb
The usage of `size: 0` to request unlimited aggregation buckets was [deprecated in Elasticsearch 5](https://github.com/elastic/elasticsearch/issues/18838). This PR changes the default limit in the sayt_suggestion rake task from 0 (unlimited) to 1000 (which is what we use in production).
=> SRCH-1401 change sayt_suggestions default limit to 1000

app/models/low_query_ctr_watcher.rb, spec/fixtures/json/watcher/low_query_ctr_watcher_body.json
This fixes an oversight from the analytics changes; types are now passed in the query body, and should not be passed as a separate parameter to the ES search.
=> SRCH-1263 do not pass types to low query CTR watcher

app/controllers/api/v2/searches_controller.rb, app/views/sites/api_instructions/_show_web_md.html.haml, spec/controllers/api/v2/searches_controller_spec.rb, spec/controllers/searches_controller_spec.rb, spec/models/routed_query_impression_logger_spec.rb, spec/models/search_impression_spec.rb
This PR makes some changes to the routed queries feature in the API:
- Removes the need for a special parameter.
- Returns `route_to` instead of `redirect` as the key.
- Adds documentation of the feature and a vanilla javascript example.
- Refactors the routed query specs to use the fixtures
- Adds logging for api routed queries
- Adds a spec for the RoutedQueryImpressionLogger used by both the api and the app.
=> SRCH-1406 - Update routed query feature in the API

.circleci/config.yml, app/controllers/api/v2/searches_controller.rb, app/views/sites/api_instructions/_show_web_md.html.haml, config/secrets.yml.dev, spec/controllers/api/v2/searches_controller_spec.rb, spec/controllers/searches_controller_spec.rb, spec/models/routed_query_impression_logger_spec.rb, spec/models/search_impression_spec.rb, spec/support/indexable_behavior.rb
[SRCH-1261] and [SRCH-958] - run specs against Elasticsearch 6.8
[SRCH-1406] - Update routed query feature in the API
=> Release 1.16.30

spec/lib/url_status_code_fetcher_spec.rb
This PR fixes a spec that started failing due to the usa.gov URL being unreachable:
```
$ curl -I https://www.usa.gov/
curl: (60) SSL certificate problem: certificate has expired
```
In a perfect world, we'd stub the request in the spec, but that class uses a gem for requests that are not easily stubbed. So for now I'm fixing this by switching to a working URL.
=> fix url_status_code_fetcher_spec

app/assets/javascripts/legacy/application.js, app/assets/javascripts/searches/clk.js, app/helpers/search_helper.rb, spec/helpers/search_helper_spec.rb, spec/helpers/twitter_profiles_helper_spec.rb
As part of removing the [legacy SERPs](https://cm-jira.usa.gov/browse/SRCH-368), these comments can help remove some of the code used for the old way click tracking used to work. I would also look at the methods in [results_helper.rb](https://github.com/GSA/search-gov/blob/master/app/helpers/results_helper.rb), besides the first two.
=> Added comments for finding old code in srch-1525

features/admin_center_manage_content.feature
July 1st 2020 test dates fail now that we are past that date. They were [written in 2013](https://github.com/GSA/search-gov/blame/72394aa3a35990adcc24ff7394da9b465ae41229/features/admin_center_manage_content.feature#L89)! This PR pushes this same problem back a decade.
=> Push feature dates another decade. :)

app/jobs/sitemap_indexer_job.rb, app/jobs/sitemap_monitor_job.rb, spec/jobs/sitemap_indexer_job_spec.rb, spec/jobs/sitemap_monitor_job_spec.rb, spec/support/sitemap_job_behavior.rb
This PR separates the sitemap and searchgov queues. Now sitemap indexing can happen at the same time as domain indexing.  https://cm-jira.usa.gov/browse/SRCH-1356
Will need to be matched with some Chef changes that adds a worker to this new queue.
`QUEUE=sitemap rake resque:work`
`QUEUE=searchgov rake resque:work`
=> SRCH-1356 - Separate sitemap and searchgov queues

.circleci/config.yml
The Elasticsearch 6.8.6 image has been pulled from Docker, so this PR bumps the version used in CircleCi to 6.8.11.
=> Use Elasticsearch 6.8.11 in CircleCI

.gitignore
This PR resolves the following issue that I encountered in CircleCi:
https://www.alanvardy.com/post/puma-server-not-loading
Failures: https://app.circleci.com/pipelines/github/ondrae/search-gov/111/workflows/7a57fee0-4a56-4ec5-984f-177253fb6fc4/jobs/581
We used to create the `tmp/pids` directory [when setting up Redis for tests](https://github.com/GSA/search-gov/pull/587/files#diff-9042eb635a014a2e0077a0bb9f81ffdbL11), but now CircleCi will fail when it tries to spin up a server for a js-driven system spec. So this PR commits `/tmp/pids/.keep` to ensure that `/tmp/pids` will exist for spec runs. (This is the default in Rails 6.)
=> SRCH-1650 preserve tmp/pids

app/controllers/sites/click_drilldowns_controller.rb, app/controllers/sites/query_drilldowns_controller.rb, lib/csv_responsive.rb, spec/controllers/sites/click_drilldowns_controller_spec.rb, spec/fixtures/json/rtu_dashboard/drilldown_clicks.json, spec/lib/csv_responsive_spec.rb
This PR ensures that the click module in the downloaded CSV appears as a string (`BWEB`), regardless of whether it is stored in Elasticsearch as an array or a string.
=> SRCH-1678 format click module as a string in drilldown CSV

app/controllers/sites/click_tracking_api_instructions_controller.rb, app/views/sites/shared/_activate_search_sub_nav.html.haml, features/admin_center_activate_search.feature
This PR removes the link to the click tracking API instructions, enabling us to do a soft release of the click tracking changes.
=> SRCH-1649 temporarily remove link to click API instructions

app/controllers/api/v2/click_controller.rb, spec/requests/api/v2/click_spec.rb
This fixes a bug that prevented API users from sending referrer data for a click.
=> SRCH-1685 enable click referrer tracking for API users

app/models/click.rb, spec/models/click_spec.rb
This PR fixes a bug that blocked click tracking for certain encoded  URLs.
=> SRCH-1687 log clicks on encoded URLs

spec/system/click_tracking_spec.rb
This fixes an intermittent spec failure caused by a missing user agent at the time the click tracking system spec is run. This sets the user agent explicitly and adds a spec for the user agent logging.
=> SRCH-1683 fix intermittent spec failure

app/controllers/api/v2/click_controller.rb, app/controllers/clicked_controller.rb, config/routes.rb, spec/controllers/human_sessions_controller_spec.rb, spec/requests/api/v2/click_spec.rb, spec/requests/clicked_spec.rb, spec/support/click_tracking_behavior.rb, spec/system/click_tracking_spec.rb
This PR updates our click API behavior by automatically extracting browser data from a client-side click request, rather than requiring it in the API params. It also includes some refactoring to DRY up the click controllers & specs.
=> SRCH-1697 extract browser info from client-side click api requests

config/secrets.yml.dev, spec/lib/twitter_client_spec.rb
This PR was originally going to update the keys for the credentials from the deprecated `oauth_*` keys to `access_*`, but it turns out that the old `tweetstream` gem requires the old keys. So for now, I'm just adding a comment to that effect, and a simple unit test for the Twitter client itself, to verify that nothing blows up when the client is initialized.
=> SRCH-1706 add comment re. Twitter credentials

.rubocop.yml
- Weakened indentation requirements for multi-method
chaining (e.g. fluent interfaces). Rubocop's strong style for this is
not the team's preference.
- Turned off block length cop for selected RSpec blocks.
- Turned off Rspec cops for example length and block nesting depth.
=> Tweaks to RuboCop settings file.

config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb
Disabled force_ssl for /healthcheck. Our ELB's use that path as a
health check, and won't work right if we try to force SSL for it.
=> Turned on secure cookies.

app/models/sayt_suggestion_discovery.rb, spec/models/sayt_suggestion_discovery_spec.rb
This PR bumps the minimum # of searches required to create a type-ahead suggestion from 5 to 100. (Long-term, we should make this configurable in the cookbooks, but this will suffice for now.)
=> SRCH-1866 increase suggestion threshold to 100

app/controllers/sites/click_tracking_api_instructions_controller.rb, app/views/sites/api_instructions/_show_tos_md.html.haml, app/views/sites/click_tracking_api_instructions/_show_md.html.haml, app/views/sites/shared/_activate_search_sub_nav.html.haml, features/admin_center_activate_search.feature
This PR:
- updates the click tracking API instructions
- adds a link to them from the admin center
- enables the relevant cucumber test
=> SRCH-1680 add instructions for click tracking API

features/admin_center_clicks_and_queries.feature, features/step_definitions/site_analytics_steps.rb
This PR resolves the following cucumber failure:
```
Scenario: Viewing the Site's Analytics
When I follow "csv"
Message:
Ambiguous match, found 2 elements matching visible link "csv" (Capybara::Ambiguous)
```
=> SRCH-1094 fix cucumber test for monthly queries downloads

.circleci/config.yml, .circleci/images/primary/Dockerfile.ruby255
This PR updates the Dockerfile used to create our our custom Ruby 2.5.5 image: https://hub.docker.com/repository/docker/searchgov/ruby
It also  updates our CircleCi config to use the updated image. This lays the groundwork necessary to run our search-gov specs against multiple Ruby versions in CircleCi. I
=> SRCH-1926 update CircleCi config to use updated ruby 2.5.5 image

features/user_sessions.feature, spec/controllers/user_sessions_controller_spec.rb
The RuboCop comment in `user_sessions_controller_spec.rb` could be replaced by an exclusion in the appropriate config file, since it's disabling the ScatteredSetup cop for the whole file. I judged it better to use the pseudo-comment facility, because the exclusion results from what the specs are doing, rather than from the type (system, controller, etc.) of the spec.
=> Logout tests.

app/models/tweet.rb, db/migrate/20210317234859_add_index_on_tweets_published_at.rb, db/structure.sql, spec/models/tweet_spec.rb
This PR fixes the broken `Tweet.expire` method. It also adds a meaningful spec for that method, adds an index on the `published_at` column to support the query used by that method, and resolves several Rubocop offenses.
=> SRCH-1915 fix Tweet.expire method

.rubocop.yml
This PR ensures that `IgnoredMethods` for certain cops as specified by the `searchgov_style` gem are merged with `IgnoredMethods` specific to this repo. It also removes the existing `IgnoredMethods: ['require']` line for the `Style/MethodCallWithArgsParentheses` cop, as that is specified in searchgov_style:
https://github.com/GSA/searchgov_style/blob/main/.default.yml#L112
=> SRCH-1982 merge "IgnoredMethods" in Rubocop config

features/searches.feature, features/vcr_cassettes/Search/Affiliate_search_on_affiliate_with_connections.yml, features/vcr_cassettes/Search/No_results_when_searching_on_Spanish_site_with_active_RSS_feeds.yml, features/vcr_cassettes/Search/No_results_when_searching_with_active_RSS_feeds.yml, features/vcr_cassettes/Search/Search_with_no_results.yml, features/vcr_cassettes/Search/Searchers_see_English_Medline_Govbox.yml, features/vcr_cassettes/Search/Searchers_see_Spanish_Medline_Govbox.yml, features/vcr_cassettes/Search/Searching_a_domain_with_Bing_results_that_match_a_specific_news_item.yml, features/vcr_cassettes/Search/Searching_for_site_specific_results_using_query.yml, features/vcr_cassettes/Search/Searching_for_site_specific_results_using_sitelimit.yml, features/vcr_cassettes/Search/Searching_news_items_using_time_filters.yml, features/vcr_cassettes/Search/Searching_news_items_with_custom_dublin_core_mappings.yml, features/vcr_cassettes/Search/Searching_news_items_with_default_dublin_core_mappings.yml, features/vcr_cassettes/Search/Searching_on_sites_with_Boosted_Contents.yml, features/vcr_cassettes/Search/Searching_on_sites_with_Featured_Collections.yml, features/vcr_cassettes/Search/Searching_with_active_RSS_feeds.yml, features/vcr_cassettes/Search/Searching_with_malformed_query.yml, features/vcr_cassettes/Search/Visiting_English_affiliate_search_with_multiple_domains.yml, features/vcr_cassettes/Search/Visiting_Spanish_affiliate_search_with_multiple_domains.yml, features/vcr_cassettes/Search/When_a_searcher_enters_a_query_with_invalid_Lucene_character.yml, features/vcr_cassettes/Search/When_there_are_relevant_Tweets_from_Twitter_profiles_associated_with_the_affiliate.yml
This PR is the first in a series intended to get all our SERP tests, most of which currently run against the "legacy SERP", running against our current, responsive SERP. When reviewing, you can mostly ignore the auto-generated files in `features/vcr_cassettes`, which are recordings of external requests made during the feature runs. The new `features/searches.feature` is mostly a straight copy and paste from `features/legacy_search.feature`. It has been slightly tweaked to run the features against the current SERP. Failing scenarios have been tagged with `@wip`, and will be updated and re-enabled in subsequent tickets. (The `features/searches.feature` will be cleaned up and refactored going forward, but for now this is intended as a warts-and-all, copy and paste dump intended to get our …
=> SRCH-2014 run legacy SERP features against responsive SERP

app/controllers/admin/rss_feed_urls_controller.rb, app/models/low_query_ctr_watcher.rb
This PR silences the following warnings related to the now-disabled LineLength cop:
```
/Users/Moth/src/GSA/search-gov/app/controllers/admin/rss_feed_urls_controller.rb: Warning: no department given for LineLength. Run `rubocop -a --only Migration/DepartmentName` to fix.
/Users/Moth/src/GSA/search-gov/app/controllers/admin/rss_feed_urls_controller.rb: Warning: no department given for LineLength. Run `rubocop -a --only Migration/DepartmentName` to fix.
/Users/Moth/src/GSA/search-gov/app/models/low_query_ctr_watcher.rb: Warning: no department given for LineLength. Run `rubocop -a --only Migration/DepartmentName` to fix.
/Users/Moth/src/GSA/search-gov/app/models/low_query_ctr_watcher.rb: Warning: no department given for LineLength. Run `rubocop -a --only Migration/DepartmentName` to fix. …
```
=> SRCH-2013 remove references to disabled LineLength cop

features/searches.feature, features/step_definitions/within_steps.rb, features/vcr_cassettes/Search/Searching_for_site_specific_results_using_sitelimit.yml
This PR updates and enables the "Searching for site specific results using sitelimit" to run against the responsive SERP. I have simplified the feature significantly, as most of the sitelimit behavior that was tested against the legacy SERP (namely, the sitelimit persisting from search to search) has not been implemented for the responsive SERP.
=> SRCH-2040 update and enable searching with sitelimit feature

features/searches.feature
This PR removes the `Searching news items with custom dublin core mappings` feature, which is not relevant to the current SERP.
=> SRCH-2049 remove feature re. searching with custom Dublin core mappings

.circleci/config.yml
Also added a nice name display for the matrixed build versions.
=> SRCH-2221 Remove Ruby 2.5 from search-gov CircleCI

features/mobile_searches.feature, features/mobile_searches_bing_v7.feature, features/step_definitions/agency_steps.rb, features/step_definitions/job_steps.rb, features/vcr_cassettes/Searches_using_mobile_device/Agency_job_search.yml
This PR adds an integration test for a job search by agency. I realized during the legacy SERP removal that this feature was not well covered by existing tests.
https://search.gov/manual/govbox-jobs.html
=> SRCH-2299 add integration test for agency job search

spec/helpers/news_search_helper_spec.rb
This PR adds specs for a method that was previously only tested through another method that will be removed along with the legacy SERP code.
=> SRCH-2308 add specs for NewsSearchHelper#current_time_filter_description

spec/fixtures/affiliates.yml, spec/models/web_search_spec.rb, spec/vcr_cassettes/api_controller_search/options.yml, spec/vcr_cassettes/searches_controller/searching_on_a_routed_keyword_referrer_matches_redirect_url_it_should_behave_like_a_routed_query_that_matches_the_referrer.yml, spec/vcr_cassettes/searches_controller/searching_on_a_routed_keyword_referrer_matches_redirect_url_when_the_match_is_exact_except_that_the_referring_url_is_http_and_the_routed_query_url_is_https_it_should_behave_like_a_routed_query_that_matches_the_referrer.yml, spec/vcr_cassettes/searches_controller/searching_on_a_routed_keyword_referrer_matches_redirect_url_when_the_match_is_exact_except_that_the_referring_url_is_https_and_the_routed_query_url_is_http_it_should_behave_like_a_routed_query_that_matches_the_referrer.yml, spec/vcr_cassettes/searches_controller/when_affiliate/force_mobile_format_true.yml, spec/vcr_cassettes/searches_controller_docs/when_the_request_is_from_a_mobile_device.yml
This PR updates the `basic_affiliate` fixture to use the default search engine (currently BingV7) instead of the deprecated Google search engine. It also includes updates to the VCR cassettes and some Rubocop fixes. The remaining Rubocop failures are preexisting issues that I am not refactoring as part of this PR.
=> SRCH-2331 the basic_affiliate fixture uses the default search engine

Gemfile, Gemfile.lock
- add comments re. deprecated gems
=> SRCH-2108 remove bcrypt-ruby gem

spec/controllers/admin/query_ctrs_controller_spec.rb, spec/controllers/admin/search_module_ctrs_controller_spec.rb, spec/controllers/admin/site_ctrs_controller_spec.rb, spec/controllers/admin/superfresh_urls_bulk_upload_controller_spec.rb, spec/controllers/api/v1/agencies_controller_spec.rb, spec/controllers/api/v2/agencies_controller_spec.rb, spec/controllers/health_checks_controller_spec.rb
Changed be_success to be_successful in all specs that used it
Rails 6 is removing the success? predicate; successful? is the
recommended replacement. Besides, this way reads better.
=> SRCH-2293 Fix specs that depend on `success?`

lib/external_faraday.rb, spec/lib/external_faraday_spec.rb
- Minor changes to remove rspec test suite waning: 
> DEPRECATION WARNING: Accessing hashes returned from config_for by non-symbol keys is deprecated and will be removed in Rails 6.1. Use symbols for access instead.
=> SRCH-2655 Resolve non-symbol keys warning in rspec

app/models/user.rb
Resolves the following Rails 6.1 deprecation warning: 
> DEPRECATION WARNING: Class level methods will no longer inherit scoping from `create` in Rails 6.1. To continue using the scoped relation, pass it into the block directly. To instead access the full set of models, as Rails 6.1 will, use `User.default_scoped`. (called from from_omniauth at /Users/Moth/src/GSA/search-gov/app/models/user.rb:139) 
by adding `User.default_scoped` to the `from_omniauth` method.
Also, removes duplicate `validates :email, presence: true` incidentally discovered during the above work.
=> SRCH-2656 Resolve inherited scoping warning

spec/controllers/admin/affiliates_controller_spec.rb
This PR resolves the following deprecation warnings from the `active_scaffold` gem:
```
search-gov (master)$ bundle exec rspec spec/controllers/admin/affiliates_controller_spec.rb | grep -i deprec
...
DEPRECATION WARNING: use visible_columns.map(&:name) (called from block (5 levels) in <top (required)> at /Users/Moth/src/GSA/search-gov/spec/controllers/admin/affiliates_controller_spec.rb:97)
DEPRECATION WARNING: use visible_columns.map(&:name) (called from block (5 levels) in <top (required)> at /Users/Moth/src/GSA/search-gov/spec/controllers/admin/affiliates_controller_spec.rb:115)
DEPRECATION WARNING: use visible_columns.map(&:name) (called from block (5 levels) in <top (required)> at /Users/Moth/src/GSA/search-gov/spec/controllers/admin/affiliates_controller_spec.rb:109)
DEPRECATION …
```
=> SRCH-2716 resolve active_scaffold deprecation warnings

features/searches.feature, features/vcr_cassettes/Search/Searching_with_spelling_suggestions.yml, spec/helpers/spelling_suggestions_helper_spec.rb
- Updates `spec/helpers/spelling_suggestions_helper_spec.rb` to confirm that the href attribute of a spelling suggestion is actually tested (instead of silently passing with an unused parameter warning); and,
- Adds cucumber test for bing-driven spelling suggestions.
Note: This will improve this test coverage under Capybara 2.x, but is also a necessary prerequisite for [SRCH-2382](https://cm-jira.usa.gov/browse/SRCH-2382) as the Capybara 3.x upgrade will result in these tests failing.
N/A
N/A
=> SRCH-2726 update spelling suggestions helper tests

app/helpers/search_helper.rb, spec/helpers/search_helper_spec.rb
- Updates `app/helpers/search_helper.rb` to ensure that queries passed to "no results pointer" and/or "page one more results pointer" are properly URI encoded;
- Updates `spec/helpers/search_helper_spec.rb` to confirm that the href attribute of a `link_to_other_web_results` generated link is being checked (instead of silently passing with an unused parameter warning); and,
- Very minor spelling, spacing, indentation, double/single quote changes as identified by my linter/rubocop.
While the use of `Addressable::URI.encode` was recommended in the dev approach, this did not properly % encode ampersands.
```
[1] pry(main)> query = "Bill & Ted's Excellent"
=> "Bill & Ted's Excellent"
[2] pry(main)> Addressable::URI.encode(query)
=> "Bill%20&%20Ted's%20Excellent"
[3] pry(main)> …
```
=> SRCH-2725 Encode no results pointer query params

Gemfile, Gemfile.lock, features/mobile_searches.feature, features/step_definitions/timeline_steps.rb, features/step_definitions/web_ext_steps.rb, features/step_definitions/web_steps.rb, spec/system/admin/bulk_url_upload_spec.rb, spec/views/admin/query_ctrs/show.html.haml_spec.rb, spec/views/admin/search_module_ctrs/show.html.haml_spec.rb, spec/views/admin/site_ctrs/show.html.haml_spec.rb
- Bumps Capybara to ~> 3.26 to support Rails 6.1 upgrade.  Tests in a Rails 6.1 upgrade branch throw `LoadError: can't activate capybara (>= 3.26), already activated capybara-2.18.0. Make sure all dependencies are added to Gemfile.` without this change.
- Minor changes to tests to support this upgrade, namely centering on how whitespace is handled in `Node#text` and related matchers.  (For more, see: https://github.com/teamcapybara/capybara/blob/master/UPGRADING.md)
Ongoing precursor work necessary for Rails 6.1 upgrade is to use the feature/rails_6_1 branch.
=> SRCH-2382 bump capybara to ~> 3.26

Gemfile, Gemfile.lock
This PR locks `dry-configurable` to `0.13.0`, as `0.14.0`, as `0.14.0` is incompatible with ruby 2.6. 
=> SRCH-2753 limit dry-configurable to 0.13.0

.circleci/images/primary/Dockerfile.ruby275
This PR adds a Dockerfile for Ruby 2.7.5 (the image has already been pushed to Docker Hub). Our previous image for 2.7.4 used a legacy ruby image with support for PhantomJS, which we are removing from our repo. This is also based on a newer `cimg/ruby` image, instead of the older `circleci/ruby` images. 
=> SRCH-2780 add Ruby 2.7.5 Dockerfile

spec/controllers/users_controller_spec.rb
Fix inconsistently failing user controller test by:
- Separating test setup in the before block from test assertions by switching from `expect` to `allow`;
- Moving to one `activate_authlogic` in one top-level before, instead of scattering them in all over the place; and,
- Ensure other saves (e.g. from authlogic) run normally, before stubbing the response we need for `update_account` (credit to: @MothOnMars).
Additional Background:
SRCH-1389 was filed just a couple months after these tests were initially contributed, so I suspect these have always been a bit flaky.
Test change only.
N/A
=> SRCH-1389 Fix flaky user controller tests

app/controllers/admin/affiliates_controller.rb, app/views/sites/displays/edit.html.haml, db/migrate/20220301164315_remove_advanced_search_enabled_from_document_collections.rb, db/migrate/20220301170006_remove_search_consumer_columns_from_affiliates.rb, db/migrate/20220301201803_drop_affiliate_templates_table.rb, db/migrate/20220301202004_drop_templates_table.rb, db/schema.rb, db/seeds/affiliate.rb, spec/controllers/admin/affiliates_controller_spec.rb, spec/models/affiliate_spec.rb, spec/models/document_collection_spec.rb
Drops now defunct search consumer related db columns and tables.  One additional affiliates column not noted in JIRA - template_schema - was identified during the course of this work as needing to be removed.  Also includes:
- Related changes to `app/controllers/admin/affiliates_controller.rb`
- Removal of the 'sc_enabled' affiliate from `db/seeds/affiliate.rb` (doing this here is necessary to keep tests passing after removing the 'search_consumer_search_enabled' from the db)
- Removing conditional in `app/views/sites/displays/edit.html.haml` (tests fail without this change here since 'search_consumer_search_enabled' has been removed from the db)
- Removing related specs
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a …
=> SRCH-2718 Search consumer database migrations

app/models/affiliate.rb, spec/models/affiliate_spec.rb
- SRCH-2853 remove sc_search_engine method & specs
=> SRCH-2853 remove sc_search_engine method & specs

lib/indexable.rb
This PR adds the `include_type_name: true` parameter to the index creation call during index migration, for compatibility with ES 7. This is similar to https://github.com/GSA/search-gov/pull/866 (there's an opportunity to DRY up the two index creation methods, but I decided to keep the refactoring to a minimum, as I plan to skip manual testing for this change). I've also cleaned up some Rubocop offenses (there are still more to do in this file, but I timeboxed the Rubocop cleanup).
=> SRCH-2845 specify include_type_name when migrating index

config/routes.rb
This PR removes a route related to the `affiliate_notes` table, which was deprecated/dropped in 2015:
https://github.com/GSA/search-gov/commit/429adb359262ff5f038b94de4409e3e1900c997
=> SRCH-2861 remove affiliate_notes route

Gemfile, Gemfile.lock, spec/spec_helper.rb
This PR removes the `rspec-json_expectations` gem, which was only used in specs that we have removed.
=> SRCH-2859 remove the rspec-json_expectations gem

app/models/custom_index_queries/elastic_boosted_content_query.rb
- Resolves "minimum_should_match" deprecation warnings in boosted contents
- Debugging statements confirm no test queries are changed aside from the test query that throws the warning: `"Should clauses in the filter context will no longer automatically set the minimum should match to 1 in the next major version. You should group them in a [filter] clause or explicitly set [minimum_should_match] to 1 to restore this behavior in the next major version."`
=> SRCH-2828 Minimum should match in boosted contents

app/services/sitemap_indexer.rb, spec/services/sitemap_indexer_spec.rb
This PR reloads the relevant `SearchgovDomain` record before calling `#index_urls`. This prevents `SitemapIndexer` jobs running in parallel from enqueuing duplicate `SearchgovDomainIndexer` jobs for the same domain, as a domain with an `indexing` status won't trigger a new `SearchgovDomainIndexer` job. Currently, two `SitemapIndexer` jobs for the same domain each try to call `#index_urls`, and succeed in enqueuing duplicate `SearchgovDomainIndexer` jobs. This change ensures that one of them will detect that the domain has an `indexing` status, and will not enqueue the indexer job.
There is still the possibility of a race condition if they are reloading and calling `index_urls` simultaneously, but it will be much less likely than it is now. This fix is a bit of a band-aid on a larger …
=> SRCH-2897 reload SearchgovDomain record before calling #index_urls

spec/controllers/users_controller_spec.rb
- After a lot of trial and effort, it seems the intermittent failures with the UsersController#create tests stem from the `verify_recaptcha` at https://github.com/GSA/search-gov/blob/master/app/controllers/users_controller.rb#L18 returning false **only** when these tests are run after https://github.com/GSA/search-gov/blob/master/spec/system/admin/user_spec.rb
- `verify_recaptcha` should never run in a test environment (https://github.com/ambethia/recaptcha#testing)
- Ultimately the fix is just to ensure that verify_recaptcha returns true no matter what in the UsersController tests
To replicate a failing scenario against master, `rspec spec/controllers/users_controller_spec.rb spec/system/admin/user_spec.rb --seed 23764 --format documentation`.  Note the system spec will throw a …
=> SRCH-2849 Fix flaky UsersController#create tests

.circleci/config.yml
This PR resolves the following warning in CircleCi:
> You’re using a [deprecated Docker convenience image.](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) Upgrade to a next-gen Docker convenience image.
I've also bumped the orbs, and added a workaround to prevent the Chrome installation from failing.
=> SRCH-2924 use next-gen MySQL image in CircleCi

.codeclimate.yml, Gemfile, Gemfile.lock
This PR clarifies the instructions on upgrading `searchgov_style` and `rubocop`, and locks the `rubocop` version and channel to `1.23.0`.
=> SRCH-2920 specify rubocop version & channel

app/models/logstash_queries/module_sparkline_query.rb, app/models/logstash_queries/monthly_histogram_query.rb, spec/models/logstash_queries/module_sparkline_query_spec.rb, spec/models/logstash_queries/monthly_histogram_query_spec.rb, spec/models/logstash_queries/overall_sparkline_query_spec.rb
This PR resolves the following deprecation warning:
> 'y' year should be replaced with 'u'. Use 'y' for year-of-era. Prefix your date format with '8' to use the new specifier.
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/breaking-changes-7.0.html#_joda_based_date_formatters_are_replaced_with_java_ones
This change is analogous to https://github.com/GSA/search-gov/pull/865.
=> SRCH-2862 resolve deprecation warnings re. year format

app/models/searchgov_domain.rb, spec/jobs/searchgov_domain_indexer_job_spec.rb, spec/models/searchgov_domain_spec.rb
- SearchgovDomain#check_status now returns a non-OK_STATUS rather than raising an exception when its domain is unreachable.
- Logic is still a bit tortured; I'm open to suggestions for improvement.
- :warning: You have run `bundle update` and committed your changes to Gemfile.lock; depending on this operation having been done by the recently merged [SRCH-3224](https://cm-jira.usa.gov/browse/SRCH-3224)
=> SRCH-3154 searchgov_domain.check_status should not raise errors

app/models/searchgov_domain.rb, spec/jobs/searchgov_domain_indexer_job_spec.rb, spec/models/searchgov_domain_spec.rb
- SRCH-3154 searchgov_domain.check_status should not raise errors 
- ⚠️  You have run `bundle update` and committed your changes to Gemfile.lock.  Gemfile changes rolled in SRCH-3224 per https://github.com/GSA/search-gov/pull/965
=> Release - SRCH-3154

.github/pull_request_template.md
- Removing squashing commit from PR Checklist
:warning: You have run `bundle update` and committed your changes to Gemfile.lock. - not doing this as part of the changes
=> SRCH-3297 remove squash requirement

app/models/html_document.rb, spec/fixtures/html/page_with_dc_metadata.html, spec/fixtures/html/page_with_og_metadata.html, spec/models/application_document_spec.rb, spec/models/html_document_spec.rb, spec/models/searchgov_url_spec.rb
Primarily serves to update the parsing logic for `keywords` for search-gov crawled urls.
- Previously, keywords originated from either the first `metadata['keywords']` or, if not present, the first `dublin_core_data['dc.subject']`; now, all values in any/all of the following fields are gathered, deduplicated, and combined in the final keywords string:
- dublin_core_data['dc.subject'],
- dcterms_data['dcterms.subject'],
- dcterms_data['dcterms.keywords'],
- metadata['keywords']&.join(', '),
- metadata['article:tag']&.join(', '),
- metadata['article:section'];
- Because we wanted to support parallel descriptions (more in inline comment), additional tweaks were made to existing/non-keyword methods;
- The first commit includes required/necessary spec changes, as well as an new spec in …
=> SRCH-3158 update parsing logic for tags field

app/models/i14y_document.rb, app/models/searchgov_url.rb, spec/models/i14y_document_spec.rb, spec/models/searchgov_url_spec.rb
* SRCH-3110 specify mime_type when indexing SearchgovUrls via I14y
=> Release - SRCH-3110

app/models/searchgov_url.rb, db/migrate/20220831184226_add_js_renderer_to_searchgov_domain.rb, db/schema.rb
- Add a new boolean column `js_renderer` to `SearchgovDomain` table default set to true.
- This can be used to opt-in/out of JS Rendering.
=> SRCH-3330: create js_renderer boolean

spec/models/low_query_ctr_watcher_spec.rb, spec/models/news_item_spec.rb, spec/models/no_results_watcher_spec.rb, spec/models/tweet_spec.rb, spec/models/twitter_list_spec.rb, spec/models/watcher_spec.rb, spec/models/youtube_playlist_spec.rb
This PR:
- adds some model specs for serialized columns in a number of tables. This allows us to make changes to those columns more safely and easily (as we will be doing for SRCH-3206 which will change the serialization method for those columns). 
- cleans up a number of Rubocop offenses in the specs
⚠️  You have run `bundle update` and committed your changes to Gemfile.lock.
I did not `bundle update`, as these changes are only in the spec files, and should not require a separate deployment.
=> SRCH-3451 add unit tests for serialized columns

db/migrate/20221111205138_change_default_is_bing_image_search_enabled_on_affiliates_to_false.rb, db/schema.rb, features/admin_center_manage_display.feature, features/searches.feature, spec/models/image_search_spec.rb
This PR adds a migration to set `Is bing image search enabled` to `false` by default for new affiliates.
=> SRCH-2606 Disable Bing image search by default

app/controllers/admin/searchgov_domains_controller.rb, app/models/searchgov_domain.rb, features/admin.feature, features/step_definitions/web_steps.rb, spec/controllers/admin/searchgov_domains_controller_spec.rb
- New "Edit" button to update Searchgov Domains for Super Admin. So that admin can access functionality of enable/disable ''js_renderer" from UI for Searchgov Domains.
=> SRCH-3434 expose JS indexing option to domains table for super admins

config/initializers/email.rb, lib/search_gov_interceptor.rb, spec/lib/search_gov_interceptor_spec.rb
This PR refactors the `SearchGovInterceptor` class to moves it out of the initializer, which allows us to run automated tests on it. This is a follow up to https://github.com/GSA/search-gov/pull/1060.
=> SRCH-3606 refactor and add specs for SearchGovInterceptor

app/helpers/twitter_profiles_helper.rb, app/views/sites/twitter_profiles/index.html.haml, app/views/sites/twitter_profiles/new.html.haml, features/admin_center_manage_content.feature
- Commented out the twitter list checkbox in admin center, setting cannot be enabled for users in going forward from the view.
=> SRCH-3556 Disable the twitter list setting in the admin center

app/engines/api_rate_limiter.rb, app/helpers/federal_register_documents_helper.rb, app/helpers/jobs_helper.rb, app/models/sayt_suggestion.rb, app/models/tweet.rb, app/views/superfresh/index.rss.builder, lib/api/v2/search_as_json.rb, lib/tasks/sayt_suggestions.rake, spec/fixtures/federal_register_documents.yml, spec/fixtures/news_items.yml, spec/fixtures/searchgov_urls.yml, spec/fixtures/users.yml, spec/lib/tasks/sayt_suggestions_spec.rb
This PR resolves some Rails 7 deprecation warnings such as:
- `DEPRECATION WARNING: TimeWithZone#to_s(:db) is deprecated. Please use TimeWithZone#to_fs(:db) instead. (called from get_binding at /Users/marthacthompson/src/GSA/search-gov/spec/fixtures/users.yml:83)`
- `DEPRECATION WARNING: Time#to_s(:rfc822) is deprecated. Please use Time#to_fs(:rfc822) instead. (called from block (2 levels) in _app_views_superfresh_index_rss_builder__3951269083807529362_356960 at /home/circleci/search-gov/app/views/superfresh/index.rss.builder:7)`
- `DEPRECATION WARNING: Date#to_s(:number) is deprecated. Please use Date#to_fs(:number) instead. (called from block (3 levels) in <top (required)> at /home/circleci/search-gov/lib/tasks/sayt_suggestions.rake:7)`
Please ensure you have addressed all concerns …
=> SRCH-3685 resolve deprecation warnings re. Date/TimeWithZone#to_s(:db)

spec/models/med_topic_spec.rb
This prevents intermittent spec failures for `MedTopic.download_medline_xml`. The `debug` gem makes various calls to `File.exist?` under the hood during a spec run. This change ensures that method calls from `debug` function as desired while allowing us to stub the return value when the method is called with specific arguments.
=> SRCH-3684 fix intermittent spec failures for .download_medline_xml

.circleci/config.yml, README.md
This PR removes ElasticSearch v6.x from the CircleCI matrix and also updates the `README` to reference ElasticSearch v7.x. This PR should not be merged until `search-services` is modified so that ElasticSearch 7 runs on the default 9200 port.
=> SRCH-3293 Make ElasticSearch 7 the default for development and testing

spec/fixtures/users.yml, spec/support/shared_sites_controller_shared_behavior.rb
This PR removes some spec code for the User status `pending_contact_information`, as that status was deprecated in 2013:
https://github.com/GSA/search-gov/commit/9fe3154a5a4a6552a800ec554c71118b2a5f3bda#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29b
=> SRCH-3719 remove spec code re. 'pending_contact_information'

app/models/low_query_ctr_watcher.rb, app/models/no_results_watcher.rb, app/models/watcher.rb, db/migrate/20230106201846_rename_watcher_conditions_columns.rb, db/schema.rb, spec/models/low_query_ctr_watcher_spec.rb, spec/models/no_results_watcher_spec.rb, spec/models/watcher_spec.rb, spec/support/watcher_behavior.rb
This PR renames the `watchers.*conditions` columns to use the new JSON column insead of the old, unsafe YAML column. The YAML column will be dropped per SRCH-3465.
=> SRCH-3717 rename watchers.*conditions columns to use JSON

.circleci/config.yml
This PR adds Jest JavaScript tests to the CircleCI pipeline. A coverage report is generated for Jest tests, and the `report results` job has been updated to include coverage data from Jest.
=> SRCH-3728 Add Jest tests to CircleCI and push Jest coverage metrics to Code Climate

Gemfile, Gemfile.lock
- This PR replaces the development gem `awesome_print` with `amazing_print` to avoid errors related to `awesome_print`, which is no longer maintained.
- ⚠️  Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
@danswick , this is another PR hung up on Circle Ci. The branch has passed CI:
https://app.circleci.com/pipelines/github/MothOnMars/search-gov/2670/workflows/8428b8c9-46cf-49d8-af46-b26ab16b796b
=> SRCH-3783 replace awesome_print with amazing_print

Gemfile, Gemfile.lock
This PR prevents the `SearchgovDomainIndexerJob` from opening a new database connection each time the job is run for a domain that is using Javascript rendering.
=> SRCH-3788 lock selenium-webdriver to 4.7.1

.circleci/images/primary/Dockerfile.ruby275, .circleci/images/primary/Dockerfile.ruby305
- This PR contains the new Docker image for `Ruby-3.0.5`
=> SRCH-3421 push custom Docker images for Ruby 3.0.5

app/models/rtu_popular_raw_human_array.rb, spec/models/rtu_click_raw_human_array_spec.rb, spec/models/rtu_query_raw_human_array_spec.rb
Follow-up to a similar PR: https://github.com/GSA/search-gov/pull/1135
This PR fixes a production bug caused by our upgrade to Elasticsearch 7, in which sites with more than ~65k unique queries in a year were unable to generate yearly reports. This limits the # of "popular" queries or clicks to the top 50k, which is under the cluster max_buckets limit of 65,546. (The fixes for the two issues are quite similar, and there *may* be opportunity for DRYing up the code. However, the analytics code is not covered very well by automated tests, so I erred on the side of making minimal changes.)
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ …
=> SRCH-3895 limit "popular" analytics buckets to 50k

Gemfile, Gemfile.lock
This PR temporarily locks the version of `uri` to resolve an error seen with Fullstaq Ruby 2.7.5. This will be removed once we upgrade to Fullstaq Ruby 3.x.
=> SRCH-3921 Lock version of URI gem

.circleci/config.yml
- Adds ruby 3.0.5 to the CircleCI test matrix for rspec and cucumber (leaving at the current/prod version of 2.7.5 for jest for the time being as this should be updated up as part of SRCH-3884);
- Bumps the ruby orb version to current latest;
- Increases the number of report parts as needed:
- cucumber parallelism 10 x 2 test matrices = 20
- rspec parallelism 6 x 2 test matrices = 12
- jest run = 1
- summed up == 33 parts
- Cucumber/rspec all green for both versions of ruby
=> SRCH-3797 Add ruby 3.0.5 to test matrix

app/controllers/api/v2/searches_controller.rb, lib/api/i14y_search_options.rb, lib/api/non_commercial_search_options.rb, spec/controllers/api/v2/searches_controller_spec.rb, spec/lib/api/i14y_search_options_spec.rb, spec/lib/api/non_commercial_search_options_spec.rb
- Moves I14y api search options out of the shared `Api::NonCommercialSearchOptions` and into its own `Api::I14ySearchOptions`
- As mentioned on [this code review](https://github.com/GSA/search-gov/pull/1079#pullrequestreview-1233217226), we risk confusion by continuing to add api search options to this shared class that are not expected to have any impact on blended and video searches
- Making this change now, before adding more i14y-only search options - namely, date filtering
- Added specs to confirm options are dropped when they are not recognized attributes for the specific class
- Also includes additional rubocop-necessitated changes/comments
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot …
=> SRCH-3923 Create I14y search options

app/controllers/api/v2/searches_controller.rb, app/models/filterable_search.rb, app/models/i14y_search.rb, lib/api/i14y_search_options.rb, spec/controllers/api/v2/searches_controller_spec.rb, spec/lib/api/i14y_search_options_spec.rb, spec/support/filterable_search_behavior.rb
- Adds date filtering functionality to the I14y Results API (has no impact on other Results API searches);
- Mild refactoring of `app/models/filterable_search.rb` to break out various bits of logic in `initialize_date_attributes`
- Basic date validation in `lib/api/i14y_search_options.rb`
- New tests
- Rubocop tidying, especially in spec/controllers/api/v2/searches_controller_spec.rb
- See comments in SRCH-3806 investigation for more on the decisions the influenced this implementation
- Acceptance testing is already spelled out in SRCH-3922 if you want to further interrogate the expected behavior
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ …
=> SRCH-3922 Add date filtering to Results API

config/initializers/filter_parameter_logging.rb, spec/config/initializers/filter_parameter_logging_spec.rb
- Two additions to `filtered_parameter_logging` to ensure potentially sensitive queries do not end up in our searchgov logs:
- Fully filters the `q` param to ensure sayt searches don't divulge sensitive information;
- Runs the values of the `query` parameters through `Redactor.redact` to ensure potentially sensitive strings (and _only_ potentially sensitive strings) are redacted
=> SRCH-3929 Redact PII from request params in logs

Gemfile, Gemfile.lock, app/views/sites/click_tracking_api_instructions/_show_md.html.haml, config/initializers/markdown.rb
- Replaced gem `github-markdown` with `redcarpet`.
- Few tweaks to preserve code block format in `app/views/sites/click_tracking_api_instructions/_show_md.html.haml`
=> SRCH-4072 Replace gem github-markdown with redcarpet

Gemfile, Gemfile.lock, README.md, features/redesigned_image_search.feature, features/redesigned_searches.feature, features/support/env.rb, features/support/hooks.rb
- Implements a means to run axe accessibility testing in the two redesigned cucumber features (though the tests are all flagged off - see below);
- Scenarios with an `@a11y` tag (but not an `@a11y_wip` tag) will be subject to accessibility testing in an after hook (defined in `hooks.rb`);
- All existing redesigned pages are currently failing, so the `@a11y_wip` tag has been added... subsequent tickets have been filed to investigate/remedy these failures (SRCH-4012, SRCH-4013, and SRCH-4014);
- Open to discussions on how hooks/tags were applied here -- I was trying to deliver what the ticket requested, but wasn't part of the initial decision making to use tags/hooks.
Also updates the readme per the ACs in the ticket.
Please ensure you have addressed all concerns below before marking a PR …
=> SRCH-3666 implement axe accessibility testing

Gemfile.lock, app/jobs/searchgov_domain_indexer_job.rb, spec/jobs/searchgov_domain_indexer_job_spec.rb
This is a minor follow-up to https://github.com/GSA/search-gov/pull/1194. I realized belatedly that I was being far too conservative with the specified `lock timeout` for the de-duped `SearchgovDomainIndexerJob`s. 30 minutes should be more than sufficient to ensure we are not processing parallel sets of indexing jobs for the same domain.
=> SRCH-4159 reduce SearchgovDomainIndexerJob lock timeout

app/models/i14y_document.rb, app/models/searchgov_url.rb, spec/models/i14y_document_spec.rb, spec/models/searchgov_url_spec.rb
This PR handles the scenario where multiple processes attempt to index the same new SearchgovUrl record simultaneously:
- raise a new custom `I14yDocument::DuplicateID` error when calling `I14yDocument.create` with a pre-existing ID
- rescue and log that error when indexing `SearchgovUrl` records (we don't want to rescue that error in the `I14yDocument` class, as the business logic for some other process creating docs may differ)
=> SRCH-4241 rescue 'Document already exists' errors

Gemfile, Gemfile.lock
- Initial task was to bump gem version. Since the gem is not required after Ruby 3.x upgrade, removed gem URI from `search-gov`
=> SRCH 4079 Investigate and remove/bump uri from 0.10.0 to 0.10.0.1 

app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/SearchResultsLayout.test.tsx, app/models/i14y_post_processor.rb, app/models/results_with_body_and_description_post_processor.rb, app/models/web_results_post_processor.rb, spec/models/results_with_body_and_description_post_processor_spec.rb, spec/models/web_results_post_processor_spec.rb, spec/support/normalized_results.rb
This PR removes `nil`s (which become `null`s in React) from web search results used in the SERP redesign. These values have no use and only clutter up the code.
=> SRCH-4240 Remove unneeded `nil`/`null` attributes from web search results data in SERP redesign

Gemfile.lock, app/engines/cached_search_api_connection.rb, config/environments/production.rb, config/initializers/datadog.rb, config/secrets.yml.dev, lib/faraday_middleware/exception_notifier.rb, spec/engines/cached_search_api_connection_spec.rb, spec/lib/faraday_middleware/exception_notifier_spec.rb, spec/models/i14y_search_spec.rb, spec/spec_helper.rb
This PR ensures that error information is sent to Datadog when the search client is unable to reach the API host. The errors will be tagged with the namespace of the search API (`I14y`, `bing_v6`, etc.). It also ensures that search connection failures (such as 4xx, 5xx reponses from the various search APIs) will no longer be silent failures.
- ⚠️  Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
The failure is for too many lines of code in `i14y_search_spec.rb`.  The spec I added isn't absolutely …
=> SRCH-4243 notify Datadog when the search client fails

config/routes.rb, lib/advanced_searches_constraint.rb, spec/requests/advanced_searches_constraint_spec.rb
- Adds a constraint that redirects `/search/advanced` to `/search` when the affiliate is a SearchGov affiliate;
- Preserves parameters on redirect;
- Avoids known errors described in story.
=> SRCH-3494 Redirect to /search when SearchGov

app/models/searchgov_url.rb, db/migrate/20230421151911_add_indices_to_searchgov_urls_enqueued_for_reindex_and_lastmod.rb, db/migrate/20230530042618_add_index_to_searchgov_urls_searchgov_domain_id_and_last_crawled_at_and_lastmod_and_last_crawlstatus.rb, db/schema.rb, spec/fixtures/searchgov_urls.yml, spec/models/searchgov_url_spec.rb
- Updated prioritization for `fetch_required` scope.
- Added indices `enqueued_for_reindex` and `lastmod` to searchgov_urls table to increase the query speed.
=> SRCH-3380 improve SearchgovUrl#fetch_required prioritization

lib/advanced_searches_constraint.rb, spec/requests/advanced_searches_constraint_spec.rb
Do not raise errors when affiliate doesn't exists.
Instead of accessing the `search_engine` property on an affiliate that can not be found this change leverages the database to check if an affiliate with the specified name and "SearchGov" as `search_engine` exist. If affiliate doesn't exist it returns false.
Issue: [here](https://cm-jira.usa.gov/browse/SRCH-4469).
=> SRCH-4469 Fix undefined method `search_engine`

app/helpers/react_helper.rb, app/javascript/components/SearchBar/SearchBar.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/components/VerticalNav/VerticalNav.tsx, app/javascript/test/VerticalNav.test.tsx, app/views/searches/index_redesign.html.haml, spec/helpers/react_helper_spec.rb
- Create react view helper to house react components rendering and move SearchResultsLayout rendering call to it
- Pass related sites label and link to SearchResultsLayout
- Display related sites on dropdown menu
Stories [SRCH-4467](https://cm-jira.usa.gov/browse/SRCH-4467) + [SRCH-4470](https://cm-jira.usa.gov/browse/SRCH-4470).
=> SRCH-4467 + SRCH-4470 Display related sites links for affiliate

app/jobs/searchgov_domain_indexer_job.rb, app/models/searchgov_url.rb, db/migrate/20230926194650_remove_unused_searchgov_urls_indexes.rb, db/migrate/20230926203204_create_searchgov_urls_fetch_required_index.rb, db/schema.rb, spec/jobs/searchgov_domain_indexer_job_spec.rb
- Refactor `SearchgovDomainIndexerJob` to execute only one database query instead of two per execution
- Refactor `SearchgovUrl.fetch_required` to use `last_crawled_at` instead of `last_crawl_status` for ordering
- Create an specific index based for the `fetch_required` query executed in `SearchgovDomainIndexerJob`
- Remove unused indexes created for the same purpose
=> SRCH-4528 mysql cpu optimization

config/elasticsearch_client.yml
- [SRCH-4514 Enable TLS for Elasticsearch connections](https://github.com/GSA/search-gov/commit/70658a228fd89d966dfb8439809d35322733a439)
=> Release - SRCH-4514

app/javascript/components/Results/Jobs/Jobs.tsx, app/javascript/components/Results/Results.tsx, app/javascript/components/SearchResultsLayout.tsx, app/javascript/test/Jobs.test.tsx, app/models/govbox_set.rb, spec/models/govbox_set_spec.rb
- Replace `position_location_display` with `position_location` value in jobs. Using existing logic to display multiple locations count is > 1.  
- Currently, `position_location_display` is using location different than existing SERP.
=> "Multiple Locations" is not coming for jobs belonging to multiple locations for the SERP

app/views/layouts/searches_redesign.html.haml
- Set crossorigin tag on assets to avoid CORS errors.
- The [Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#crossorigin) indicate that this will fix the error but since the error is not happening either locally nor on staging it's hard to know if it will actually fix it but regardless we need this for security reasons anyway.
=> SRCH-4714 Set crossorigin to anonymous

app/views/layouts/searches_redesign.html.haml
This reverts commit 0601871c1cc84056ab77c3ee7c119b6da0e2aa94 due new SERP being completely broken
=> Revert "SRCH-4714 Set crossorigin to anonymous (#1399)"

app/models/govbox_set.rb
This PR fixes an issue with federal register documents where an error appears when some documents have missing fields.
=> SRCH-4711 Fix federal register documents error

app/javascript/components/Identifier/Identifier.css, app/javascript/components/Identifier/Identifier.tsx, app/javascript/components/Results/Results.tsx
- [SRCH-4854](https://cm-jira.usa.gov/browse/SRCH-4854) Identifier background color on usa-identifier class should not be black
- [SRCH-4852](https://cm-jira.usa.gov/browse/SRCH-4852) There's a random "0" character showing at the extreme left of the No Results page for i14y-powered search results
=> SRCH-4854, SRCH-4852: updated bg color to be transparent for identfier and remove 0 from results count

app/javascript/components/Identifier/Identifier.tsx, app/javascript/components/VerticalNav/VerticalNav.tsx, app/javascript/test/__snapshots__/SearchResultsLayout.test.tsx.snap
- Fix for [SRCH-4858](https://cm-jira.usa.gov/browse/SRCH-4858) Search tab dropdown underline hover color should use the navigation link color
- Fix for [SRCH-4849](https://cm-jira.usa.gov/browse/SRCH-4849) remove the hover from the css for the identifier
=> SRCH-4858, SRCH-4849: remove the hover from the css for the identifier and Search tab dropdown underline hover color

.rubocop.yml, app/controllers/admin/searchgov_domains_controller.rb, app/jobs/searchgov_domain_indexer_job.rb, app/models/searchgov_domain.rb, config/locales/super_admin/en.yml, config/routes.rb, spec/controllers/admin/searchgov_domains_controller_spec.rb, spec/jobs/searchgov_domain_indexer_job_spec.rb, spec/models/searchgov_domain_spec.rb
- Adds link to stop indexing
- When the link is clicked the domain's activity goes to idle
- SearchgovDomainIndexerJob won't index if job is in idle
=> SRCH-589 Stop Indexing

app/javascript/components/Results/Results.tsx, app/javascript/components/Results/RssNews/RssNews.tsx, app/javascript/test/RssNews.test.tsx, app/javascript/utils/constants.ts
- Adds click tracking for RSS News items in both the primary and news verticals;
- Builds upon prior click tracking work like: #1488, #1490, #1493 , etc.
=> SRCH-4921 Implement RSS News click tracking

.circleci/config.yml, lib/url_status_code_fetcher.rb
SRCH-5141 Removing Ruby 3.0 and MySQL 5.7 from Circle CI
- Updating CircleCI to only use Ruby 3.1.4
- Updating CircleCI to only use MySQL 8.0
=> SRCH-5141 Removing Ruby 3.0 and MySQL 5.7 from Circle CI

config/deploy.rb
- Remove hardcoded ruby version from deploy.rb. Capistrano will use the default ruby version comming from .ruby-version
=> SRCH-5549 Remove hardcoded ruby version from deploy.rb

app/controllers/api/v2/searches_controller.rb, app/models/api_search_elastic.rb, spec/controllers/api/v2/searches_controller_spec.rb, spec/models/api_search_elastic_spec.rb
Use a `selected_engine` method to select the appropriate search affiliate search engine.
=> SRCH-6066 Allow api endpoint to respect affiliate's engine selection.
